### ISSUE TITLE
bug: simulateContract can return `undefined` account but type is incorrect

### ISSUE THREAD

**Issue by KholdStare** [wevm/viem#1284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.10.3

### Current Behavior

There is a cast on the return value of `simulateContract`: https://github.com/wagmi-dev/viem/blob/309b5832426db3e5c216ef61c826db14c39a15fe/src/actions/public/simulateContract.ts#L157-L172

The problem is in the input `callRequest`, the `account` is optional, but in the return `callRequest`, `account` is required. As such the types are incorrect.

**Comment by jxom** [comment]
Fixed in v2 alpha: https://github.com/wagmi-dev/viem/commit/aa3019ffd82e95a6b6228bae05c73686dcc7d18b

Will close once released.

**Comment by joaofranciscoguarda** [comment]
> Fixed in v2 alpha: [aa3019f](https://github.com/wagmi-dev/viem/commit/aa3019ffd82e95a6b6228bae05c73686dcc7d18b)
> 
> Will close once released.

V2 will be released when?

**Comment by jxom** [comment]
Fixed in v2
