### ISSUE TITLE
bug: ContractFunctionExecutionError: The total cost (gas * gas fee + value) of executing this transaction exceeds the balance of the account.

### ISSUE THREAD

**Issue by silverline99** [wevm/viem#1542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.9

### Current Behavior

viem @ 1.19.9
wagmi @ 1.4.7
Metamask @ 11.5.1

Hey, this is the first issue I have posted on Github, so dont expect it to be perfect :))

I am trying to call a **payable** function of a smartcontract deployed to ANVIL network (forked mainnet) from the app frontend via MetaMask wallet.

![image](https://github.com/wevm/viem/assets/76785193/b04f046f-755c-4bf0-96bd-d6e0050d6228)

The error says there are not enough funds which is **simply not right** because I set the sender account (0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266) one of those generated when Anvil is iniciated with the balance of 1000 ETH and the sending value is set to value: parseEther("0.0000000000001"),

On the other hand, I am able to successfully call a nonpayable funciton using this const { config } = usePrepareContractWrite() in another part of my app.

Here is the body of usePrepareContractWrite()

![image](https://github.com/wevm/viem/assets/76785193/82322ebd-e85a-486a-ae86-06bf053fdf94)

**Comment by jxom** [comment]
It's a bit hard to see what is going on without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). A minimal reproduction will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

From first glance though, are you sure you are connected to the Anvil node in your [Viem Transport](https://viem.sh/docs/clients/transports/http.html)?

Will reopen this issue when a reproduction is added.

**Comment by cristianopolicarpo** [comment]
I have a similar problem when added "gasPrice" in writeContract.

A real example:

Account balance: 2.3 ETH
gasPrice: 120 Gwei

Deposit of 1 ETH, this works normally.
Deposit of 2 ETH, error: not enough funds for transfer with given value

When the transaction passes without error it costs about 0.003 Eth of gas. So I imagine that the check that triggers the error must be requesting a balance greater than gas fee + deposit amount. On the network I'm working on, any transaction fails if the wallet does not have an extra amount greater than 1.2 eth when "gasPrice" in writeContract.

`Raw Call Arguments:
  from:      0xdF10eC6977E05C8F16d9B5F416b9E8bac0EE8370
  to:        0x53389BFFA22e77E015D60cf2300967A7dd43BDb8
  value:     2 ETH
  data:      0xd0e30db0
  gasPrice:  120.75597394 gwei
 
Contract Call:
  address:   0x53389BFFA22e77E015D60cf2300967A7dd43BDb8
  function:  deposit()
  sender:    0xdF10eC6977E05C8F16d9B5F416b9E8bac0EE8370

Docs: https://viem.sh/docs/contract/simulateContract
Details: not enough funds for transfer with given value
Version: viem@2.9.31
    at getContractError (chunk-QYSRIIY6.js?v=f06dc677:207:10)
    at simulateContract (chunk-QYSRIIY6.js?v=f06dc677:1595:11)
    at async simulateContract2 (chunk-HGQXFDDX.js?v=f06dc677:2825:31)
    at async Proxy.deposit (WireSwap.vue:101:5)`

**Comment by cristianopolicarpo** [comment]
> It's a bit hard to see what is going on without a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). A minimal reproduction will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).
> 
> From first glance though, are you sure you are connected to the Anvil node in your [Viem Transport](https://viem.sh/docs/clients/transports/http.html)?
> 
> Will reopen this issue when a reproduction is added.

I have a similar problem when added "gasPrice" in writeContract.

A real example:

Account balance: 2.3 ETH
gasPrice: 120 Gwei

Deposit of 1 ETH, this works normally.
Deposit of 2 ETH, error: not enough funds for transfer with given value

When the transaction passes without error it costs about 0.003 Eth of gas. So I imagine that the check that triggers the error must be requesting a balance greater than gas fee + deposit amount. On the network I'm working on, any transaction fails if the wallet does not have an extra amount greater than 1.2 eth when "gasPrice" in writeContract.

`Raw Call Arguments:
  from:      0xdF10eC6977E05C8F16d9B5F416b9E8bac0EE8370
  to:        0x53389BFFA22e77E015D60cf2300967A7dd43BDb8
  value:     2 ETH
  data:      0xd0e30db0
  gasPrice:  120.75597394 gwei
 
Contract Call:
  address:   0x53389BFFA22e77E015D60cf2300967A7dd43BDb8
  function:  deposit()
  sender:    0xdF10eC6977E05C8F16d9B5F416b9E8bac0EE8370

Docs: https://viem.sh/docs/contract/simulateContract
Details: not enough funds for transfer with given value
Version: viem@2.9.31
    at getContractError (chunk-QYSRIIY6.js?v=f06dc677:207:10)
    at simulateContract (chunk-QYSRIIY6.js?v=f06dc677:1595:11)
    at async simulateContract2 (chunk-HGQXFDDX.js?v=f06dc677:2825:31)
    at async Proxy.deposit (WireSwap.vue:101:5)`
