### ISSUE TITLE
bug: Block at number could not be found

### ISSUE THREAD

**Issue by chybisov** [wevm/viem#1543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-beta.6

### Current Behavior

Sometimes we get this error when sending transactions and using `waitForTransactionReceipt` right after. It's completely random and looks like it depends on the RPC performance.

![image](https://github.com/wevm/viem/assets/18644653/285de381-b350-4bd3-ba3a-5415de36ff6e)

![image](https://github.com/wevm/viem/assets/18644653/3c65bbbf-3d91-46a6-8d2c-5e0c9266261a)

### Expected Behavior

`viem` should continue polling and both transaction and block can be found later.

Maybe it makes sense to make a number of retries, polling intervals, etc. configurable so everyone can find a viable setup.

### Steps To Reproduce

Go to LI.FI Playground and try to make a swap or bridge.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://playground.li.fi/

### Anything else?

During the investigation of this issue, I noticed that when the block is not found `viem` throws an error but maybe we should continue polling and both transaction and block can be found later? 

As you can see, the first error was `TransactionReceiptNotFoundError` and that's reasonable because the transaction was not included in the block `50211188`, but included in the `50211191`. So I guess it is safe to continue polling as you do when a replacement transaction is not found.

https://polygonscan.com/tx/0xf9951903555ae70faef9f0f2798713370d6c5b3273ecfc3beec6d8cd0bbcd04c

![image](https://github.com/wevm/viem/assets/18644653/86254d03-796a-434b-858d-28a7c977d9bb)

As I see from GitHub issues and [Discord discussions](https://discord.com/channels/1156791276818157609/1176486178795569282), this happens to others as well: https://github.com/wevm/viem/issues/1378 https://github.com/wevm/viem/issues/1056

Using private RPC is not an option because our product can be a part of other dApps and we can't whitelist all of them. Also, I think public RPC shouldn't be an issue for using viem.

**Comment by imaksp** [comment]
I also think that there is no harm in continuing polling on such error, as block can be found later in some rpc provider (even for non public provider, I also get such error with ethers.js & Alchemy sometimes for getLogs call).

**Comment by jxom** [comment]
I will add in some polling for this. Hold tight.

**Comment by jxom** [comment]
Try `viem@1.19.11`.

Should be published to NPM soon.

**Comment by chybisov** [comment]
We use `2.0.0-beta.6`. Could you please add those changes there? Thank you! 🙏

**Comment by chybisov** [comment]
> Try `viem@1.19.11`.
> 
> Should be published to NPM soon.

We use 2.0.0-beta.6. Could you please add those changes there? Thank you! 🙏

**Comment by chybisov** [comment]
@tmm thank you so much! I'll give it a try 🙂

**Comment by chybisov** [comment]
> Releasing `viem@2.0.0-beta.7` https://github.com/wevm/viem/actions/runs/7046636507

It looks like the job was skipped, and the package has not yet been released. Could you please re-run it? Thank you! 😊

**Comment by chybisov** [comment]
@tmm @jxom please run the job again 🙂
