### ISSUE TITLE
[BUG] UnknownRpcError: An unknown RPC error occurred

### ISSUE THREAD

**Issue by vienalpha** [wevm/viem#1549]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Package Version

1.19.7

### Current Behavior

![image](https://github.com/wevm/viem/assets/132975621/03b21bc4-1ebc-459f-9578-3af538bcd334)
Have issue when i try with metaa mask

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
