### ISSUE TITLE
bug: Contract instance with undefined address

### ISSUE THREAD

**Issue by RND332** [wevm/viem#1552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.11

### Current Behavior

Viem allow you to pass undefined as contract address for getContract and get valid contract instance.

### Expected Behavior

Throw Error OR Warning.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-7nw3du?file=index.ts

### Anything else?

This is a pretty bad issue and I don't think what I'm writing in the expected behavior should really be implemented.

The reason I made this issue is that on my setup `mobx + react + viem + anvil`, this leads to an error that is very difficult to understand.

In my environment, the viem will return the following error to you, if you try to estimate gas/simulate call/call function: 
`
ContractFunctionExecutionError: The contract function "swap" reverted with the following reason:
EVM error Opcode Not Found
`
And this is not true, there is nothing related to opcodes, in fact, the problem was that I passed undefined to `getContract` instead of the real address and I spent quite a lot of time trying to figure it out.

So anyone who run into same error message on local anvil, check all places where you create contract instances.

**Comment by jxom** [comment]
TypeScript should error when passing `undefined` as a value, so compilation should fail. 

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgcwKYwMIQHYygQwGN4BfOAMyghDgHIA3YVEWgKFbUxzyJgAoErOHHwATUVFQBnKQC44AV2yjU5YNlSiANEJEAjYPIDaAXVYkAlEA

**Comment by RND332** [comment]
> TypeScript should error when passing `undefined` as a value, so compilation should fail.
> 
> https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgcwKYwMIQHYygQwGN4BfOAMyghDgHIA3YVEWgKFbUxzyJgAoErOHHwATUVFQBnKQC44AV2yjU5YNlSiANEJEAjYPIDaAXVYkAlEA

Not if you parse json from backend and typescript refers to it as any
