### ISSUE TITLE
bug: neonMainnet chain missing from the docs page

### ISSUE THREAD

**Issue by mnedelchev-vn** [wevm/viem#1558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.11

### Current Behavior

So we have made a PR to add **neonMainnet** chain to viem and it was merged successfully, this can be verified here:
1. [https://github.com/wevm/viem/blob/main/src/chains/definitions/neonMainnet.ts](https://github.com/wevm/viem/blob/main/src/chains/definitions/neonMainnet.ts)
2. [https://github.com/wevm/viem/blob/main/src/chains/index.test.ts#L101](https://github.com/wevm/viem/blob/main/src/chains/index.test.ts#L101)

**neonMainnet** is also part of the @wagmi/core/chains dependency, But then **neonMainnet** chain is still missing from the docs page here [https://wagmi.sh/core/chains](https://wagmi.sh/core/chains).

What else has to be done on our side or this is a bug?

### Expected Behavior

**neonMainnet** chain to be added at [https://wagmi.sh/core/chains](https://wagmi.sh/core/chains)

**Comment by tmm** [comment]
You are welcome to submit a PR to the [Wagmi docs](https://github.com/wevm/wagmi/blob/main/docs/pages/core/chains.en-US.mdx#L36) to update this for Wagmi v1. Wagmi v2 pulls in [chains automatically to the docs](https://beta.wagmi.sh/react/api/chains#available-chains).
