### ISSUE TITLE
WebSocket Connection Issue in Viem 1.19.11

### ISSUE THREAD

**Issue by izzetemredemir** [wevm/viem#1563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.11

### Current Behavior

Websocket not working

### Expected Behavior

The WebSocket connection should be established seamlessly, facilitating real-time data communication.

### Steps To Reproduce

**Environment**:
- Viem Package Version: 1.19.11
- TypeScript Version: 5.0.4
- Node.js Version: v20.7.0

```javascript
const publicClient = createPublicClient({
  chain: avalanche,
  transport: webSocket("wss://api.avax.network/ext/bc/C/ws"),
});
```

**Comment by tmm** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
