### ISSUE TITLE
bug: unable to retrieve events of contract

### ISSUE THREAD

**Issue by arthurlejay** [wevm/viem#1580]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.13

### Current Behavior

When using Viem (with Wagmi as a wrapper) in a React component, I am unable to retrieve the past events of a smart contract (I receive an empty array of events).

### Expected Behavior

I am using the `getLogs` method of the `viem` package in order to retrieve past events of a specific smart contract.
I am expecting to be able to read those events in a list, and access the parameters of those events.

**Note :** The response of the RPC is indeed an empty array, so I guess either the request is crafted incorrectly, or I'm missing something.

### Steps To Reproduce

1. Deploy a smart contract (let's say an ERC721 token)
2. Create events (mint a few tokens)
4. Use the given Minimal Reproducible Example, and change the address with the address of the deployed contract.
5. The message should indicate that it hasn't detected any past logs on this contract.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-3qgl25?file=index.ts

**Comment by jxom** [comment]
You’ll need to make all 3 args `indexed`, instead of just `from` and `to` as your contract indexes the token ID.

**Comment by arthurlejay** [comment]
> You’ll need to make all 3 args `indexed`, instead of just `from` and `to` as your contract indexes the token ID.

The code you are referencing is commented, the default example (without conditions on the event) is not working. 
The issue has nothing to do with event parameters being set as indexed or not.

![image](https://github.com/wevm/viem/assets/52758887/deca0155-29f6-4aa2-b6fb-ab63dbd99e47)

**Comment by arthurlejay** [comment]
Found the answer : fromBlock parameter should be mandatory, because if it's not provided then no matter the RPC you simply won't get any logs returned
