### ISSUE TITLE
bug: `getLogs` from beta version didn't translate `blockNumber` from hex string to bigint

### ISSUE THREAD

**Issue by runjuu** [wevm/viem#1611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-beta.16

### Current Behavior

`blockNumber`, `transactionIndex` and `logIndex` are hex strings.

### Expected Behavior

`blockNumber`, `transactionIndex` and `logIndex` should be bigint or number types

### Steps To Reproduce

```ts
import { createPublicClient, http } from 'viem';
import { crossbell } from 'viem/chains';

const client = createPublicClient({ chain: crossbell, transport: http() });

client
  .getLogs({
    event: {
      inputs: [
        { indexed: true, name: 'characterId', type: 'uint256' },
        { indexed: true, name: 'creator', type: 'address' },
        { indexed: true, name: 'to', type: 'address' },
        { indexed: false, name: 'handle', type: 'string' },
        { indexed: false, name: 'timestamp', type: 'uint256' },
      ],
      name: 'CharacterCreated',
      type: 'event',
    },
    fromBlock: 51419487n,
    toBlock: 52820341n,
  })
  .then(console.log);
```

<img width="657" alt="image" src="https://github.com/wevm/viem/assets/12002941/6d8d9b67-2f5a-4a7d-97cf-1892871efe21">

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/nestjs-typescript-starter-xyivpk?file=src%2Fmain.ts&terminal=start

### Anything else?

It seems like the bug is introduced by [468a4ae3160c738046de115cec2a7e5ab7286a01](https://github.com/wevm/viem/commit/468a4ae3160c738046de115cec2a7e5ab7286a01#diff-f42569be6ae968be945f24d9d4fc8cab6d302928a4077c6337de122d3cc50f58L209-L238), as `formatLog` was only applied to the logs without `events`.

**Comment by jxom** [comment]
Fixed in `2.0.0-rc.1`. Many thanks.
