### ISSUE TITLE
bug: Get "Expected 0 arguments, but got 1" when using defineChain

### ISSUE THREAD

**Issue by hcwilk** [wevm/viem#1633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.18.0

### Current Behavior

As of now, I keep receiving a Typescript error when trying to build the following code

```
export const zora = defineChain({
    id: 7777777,
    name: 'Zora',
    network: 'zora',
    nativeCurrency: {
        decimals: 18,
        name: 'Ether',
        symbol: 'ETH',
    },
    rpcUrls: {
        default: {
            http: ['https://rpc.zora.energy'],
            webSocket: ['wss://rpc.zora.energy'],
        },
        public: {
            http: ['https://rpc.zora.energy'],
            webSocket: ['wss://rpc.zora.energy'],
        },
    },
    blockExplorers: {
        default: { name: 'Explorer', url: 'https://explorer.zora.energy' },
    },
    contracts: {
        multicall3: {
            address: '0xcA11bde05977b3631167028862bE2a173976CA11',
            blockCreated: 5882,
        },
    },
})

```

No matter the information I put into this function, I just get this error

```
./libs/services/new_wallet/Web3Modal.tsx:10:33
Type error: Expected 0 arguments, but got 1.

   8 |
   9 |
> 10 | export const zora = defineChain({
     |                                 ^
  11 |     id: 7777777,
  12 |     name: 'Zora',
  13 |     network: 'zora',
- info Linting and checking validity of types ...
```

### Expected Behavior

I'm able to successfully define a custom chain using defineChain()

### Steps To Reproduce

- Use version 1.18.0 of this library
- Try and define a custom chain
- Doesn't work with the chain provided in the docs or other EVM chains I've tried

**Comment by tmm** [comment]
Works fine for me in this [TS Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUGEAWAhtnAL5zpQQhwDkAbsKiLXAPRtwwCeYqAzgC44ARgB0IgBxiADACg5qAB6RYcAMYQs-eAC9ohOAF4UGbHiLYAFAjlw4wZMIDsrt84A0duFkIhUwrQAWga0XvY4MADu0ADWgfpQhGHevjDA9HgArlBQqFjq3MK29vZo6qCEADZCopLhpb7+gQCiMPioUCmlcPzcIABGEFWtACoAEt1kDVBg6gCqUDXF3mUYhFlVMCs99vgwMGDCANq0+4dCHLPqYomEYvmdAObctAC6DT1RqAMAyhDqWKobZwU5RfiXNjXW4GB44KAvd6faarOBgLIDKrAdQ7XbnI6gs4HMCQ6F3OHPV4fVH2b5-AFAkFgiGCK5zGFJCkIqnI0gNPneTEMloqKrQTq1EqlNDoDZbYo+PwBOgisBivJdDxwHIjOj4yHKNXiqAc+6PbmsAX2K0aLQwJLqGCS1EgTbpdTVKoAZlxPUIyGQeRZdBkSnUAEERCIBmgZABWACcrgGXoAbF6o6nnDIAEySSSpnMDFo5wgiZxepOp3CRkRTHpCwG4PKEGCoJxwOP5nO8-leUgASjkQA). Can you attach a minimal reproduction?

**Comment by hcwilk** [comment]
Figured out I needed to upgrade my project's version of typescript. My bad!
