### ISSUE TITLE
bug: Cannot find type declarations of viem/op-stack

### ISSUE THREAD

**Issue by 0xdeployer** [wevm/viem#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0

### Current Behavior

![image](https://github.com/wevm/viem/assets/87840072/e7899839-956d-4d78-ad87-401b68b872c2)

### Steps To Reproduce

Just import the package

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-varadu?file=index.ts

**Comment by tmm** [comment]
Need to add a proxy package at `src/op-stack` for some tools to resolve the types.

**Comment by jxom** [comment]
Should be fixed on 2.0.2.
