### ISSUE TITLE
bug: args typing regression

### ISSUE THREAD

**Issue by matmilbury** [wevm/viem#1655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.3

### Current Behavior

since `2.0.0`, `args` property type is inferred to `unknown[]` instead of the correct type.

### Expected Behavior

`args` should be inferred to `[number]` in provided example.

It works properly in version `1.21.4`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-nnlghk?file=index.ts

**Comment by tmm** [comment]
Will take a look. In addition, your minimal reproduction ABI doesn't have any payable or nonpayable functions.

**Comment by matmilbury** [comment]
@tmm good point. This is just an error in the example, it doesn’t infer types properly with write function either.
