### ISSUE TITLE
bug: Deploy Contract example in Sepolia network breaks because of gas limited to 21k

### ISSUE THREAD

**Issue by oleggrib** [wevm/viem#1698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

Hi. 
This example works good at least for hardhat/mumbai but fails (gas limit 21K) for Sepolia
https://github.com/wevm/viem/blob/main/examples/contracts_deploying-contracts/index.tsx

### Expected Behavior

Deploy contract succesfully

### Steps To Reproduce

Open
https://github.com/wevm/viem/tree/main/examples/contracts_deploying-contracts
Click "Open in StackBlitz"
Change network from from `goerli` to `sepolia` in `https://stackblitz.com/github/wevm/viem/tree/main/examples/contracts_deploying-contracts?file=index.tsx`
Click "Connect"
Click "Deploy"
Check browser console for error "Details: intrinsic gas too low: needed 213536, allowed 21000"

**Comment by jxom** [comment]
Viem doesn't set a gas limit when deploying contracts. Your wallet does this, so I'd assume the wallet is providing an invalid gas limit to the transaction. 

I would suggest to calculate the gas beforehand with `estimateGas`, and then pass that value as `gas` to `deployTransaction`.
