### ISSUE TITLE
bug: ENS resolution inconsistencies in getEnsAvatar and getEnsName

### ISSUE THREAD

**Issue by alvaroraminelli** [wevm/viem#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.5.0

### Current Behavior

The getEnsName function correctly resolves addresses for some ENS names (e.g., renanmav.eth and graynewfield.eth) and fails for others alvaroraminelli.eth

The getEnsAvatar function is only successful for some ENS names (e.g., graynewfield.eth) and fails for others.

### Expected Behavior

Resolve name and avatar for the following names:

renanmav.eth 
alvaroraminelli.eth
graynewfield.eth

### Steps To Reproduce

[here](https://stackblitz.com/edit/viem-getting-started-aejylo?file=index.ts)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-aejylo?file=index.ts

**Comment by tmm** [comment]
`alvaroraminelli.eth` doesn't work right now because there is an issue with ENS's CDN `euc.li`, where it's not returning a `'content-type'` header anymore.

**Comment by jxom** [comment]
Looks like the address `0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41` (ref: alvaroraminelli.eth) also doesn't have a primary name set.

As for the contract revert, the `universalResolverAddress` only accepts ENS UniversalResolver contracts (not other resolvers).

@TateB might be able to chip in here if needed.

**Comment by alvaroraminelli-cb** [comment]
getEnsName works after setting up the primary name. the only issue now is `getEnsAvatar` not working for `renanmav.eth` which is in the resolver address `0x231b0Ee14048e9dCcD1d247744d114a4EB5E8E63`

**Comment by TateB** [comment]
> `getEnsName` works after setting up the primary name. the only issue now is `getEnsAvatar` not working for `renanmav.eth` which is in the resolver address `0x231b0Ee14048e9dCcD1d247744d114a4EB5E8E63`

`renanmav.eth`'s avatar is an NFT, and the NFT metadata endpoint (https://nft-tokens.habbo.com/portraits/metadata/7805.json) doesn't have CORS setup. this means that it's data can't be fetched from any other origin, and can't be resolved in-browser.

**Comment by TateB** [comment]
this is something that we should look out for on the ENS app though when selecting an NFT avatar, i'll add a check for it in the near future.
