### ISSUE TITLE
bug: waitForTransactionReceipt does not throw on reverted transaction

### ISSUE THREAD

**Issue by alex-grover** [wevm/viem#1767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.1

### Current Behavior

According to the docs, `waitForTransactionReceipt` should throw on reverted transactions. Instead, it does not throw and returns a transaction receipt with `status: 'reverted'`.

### Expected Behavior

https://viem.sh/docs/actions/public/waitForTransactionReceipt

> If the Transaction reverts, then the action will throw an error.

### Steps To Reproduce

Run `node index.js` in this repo: https://github.com/alex-grover/viem-wait-for-tx-receipt/tree/main

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/alex-grover/viem-wait-for-tx-receipt/tree/main

**Comment by jxom** [comment]
The docs are lying.
