### ISSUE TITLE
decodeEventog & parseEventLogs missing properties and correct arguments order

### ISSUE THREAD

**Issue by Manuelandro** [wevm/viem#1774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.2

### Current Behavior

As you can see in the attachments, both methods miss args informations like type, baseType and indexed compared to ethers. Also the order of the args does not match the index topic, cause it is not an array but rather an object

<img width="661" alt="Screenshot 2024-02-03 alle 14 29 22" src="https://github.com/wevm/viem/assets/3776546/99e3afaa-7832-4ca7-ac73-e1950b984219">

<img width="603" alt="Screenshot 2024-02-03 alle 16 39 57" src="https://github.com/wevm/viem/assets/3776546/378c95d6-d09b-482d-b2cb-41518cf60f39">

### Expected Behavior

To have all the args informations and the correct order of topics

**Comment by jxom** [comment]
The log parameter information shouldn’t need to be returned in `decodeEventLog`. You can use `getAbiItem` instead to retrieve this information and pass `topics[0]` to `name` to extract it from the ABI.

https://viem.sh/docs/abi/getAbiItem#name
