### ISSUE TITLE
bug: Not using specified RPC endpoint

### ISSUE THREAD

**Issue by critesjosh** [wevm/viem#1777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.2

### Current Behavior

I keep getting errors when trying to call view functions, like this:

```
        Details: execution reverted
        Version: viem@2.7.2
            at withRetry.delay.count.count (file:///home/josh/Documents/Github/a-frame-in-100-lines/node_modules/viem/_esm/utils/buildRequest.js:35:31)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
            at async attemptRetry (file:///home/josh/Documents/Github/a-frame-in-100-lines/node_modules/viem/_esm/utils/promise/withRetry.js:12:30) {
          details: 'execution reverted',
          docsPath: undefined,
          metaMessages: [
            'URL: https://cloudflare-eth.com',
            'Request body: {"method":"eth_call","params":[{"data":"0xdc8ff968000000000000000000000000cc8a0fb5ab3c7132c1b2a0109142fb112c4ce51500000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000007200000000000000000000000000000000000000000000000000000000000000d40000000000000000000000000000000000000000000000000000000000000001","to":"0x76152c311630bBE2b472afE779f478B293CFAed3"},"latest"]}'
          ],
```

It says it's using `URL: https://cloudflare-eth.com`, but I am specifying Alchemy and Infura as providers in the public client setup, like so:

```js
  const alchemy = http(process.env.ALCHEMY_URL)
  const infura = http(process.env.INFURA_URL)

  const client = createPublicClient({
    chain: mainnet,
    transport: fallback([alchemy, infura]),
  })
```
Failures are intermittent.

### Expected Behavior

It should use infura or alchemy providers

### Steps To Reproduce

Set up a public client as described above. Try to call a view function. 

You can reproduce by trying to run [this](https://github.com/critesjosh/testing-farcaster-frames/blob/main/scripts/interact.ts) script.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/critesjosh/testing-farcaster-frames/blob/main/scripts/interact.ts

**Comment by critesjosh** [comment]
My Infura and Alchemy dashboards indicate that no traffic is going through the associated URLs.

**Comment by critesjosh** [comment]
Maybe this only happens when running the script on localhost? Seems to be working on prod...

**Comment by tmm** [comment]
Double check that your environment variables are set.

**Comment by jxom** [comment]
Missing environment variables are most likely the cause. I can't seem to reproduce.
