### ISSUE TITLE
bug: Changing the networks 

### ISSUE THREAD

**Issue by Solniechniy** [wevm/viem#1778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.3

### Current Behavior

Our dapp has Eth, Linea, Aurora and we try to add Blast.
If the user was connected to mainnet, aurora or linea and login out then request for blast not working and failing with error no data (0x)
![image](https://github.com/wevm/viem/assets/26657914/fc97c21b-0d7f-40f0-8934-55f613a697a3)
If the user connected to blast and login out, then view request  for mainnet, aurora or linea not working
https://www.youtube.com/watch?v=NLXZgR9Myiw

----- 

also there is strange behavior for publicClient for Linea - it stop working when I was trying to create separate publicClients for resolving my issue.

### Expected Behavior

View methods working well for all users despite the network he was connected before.

### Steps To Reproduce

1) connect wallet, switch network to any from Ethereum, Aurora, Linea, disconnect wallet - switch wallets and get the view request under the Ethereum, Aurora, Linea - everything works fine, switching the Blast will return uknown error. 
2) connect wallet, switch network to Blast, disconnect the wallet - view request will load information ONLY from Blast. Ethereum, Aurora, Linea view request will show the error

### Anything else?

"viem": "^2.7.3",
"wagmi": "^2.5.5",    
"@tanstack/react-query": "^5.18.0",
"@wagmi/core": "^2.6.3",
"@web3modal/wagmi": "4.0.0-alpha.3",

**Comment by tmm** [comment]
Please create a [new issue](https://github.com/wevm/wagmi/issues/new?assignees=&labels=&projects=&template=bug_report.yml) on the Wagmi repo **with a minimal reproduction**.
