### ISSUE TITLE
writeContract() args typing regression is still unresolved

### ISSUE THREAD

**Issue by Honour-d-dev** [wevm/viem#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.5

### Current Behavior

the `args` parameter of `writeContract()` accepts any argument list provided , an issue was previously opened on this and was closed but the issue still persists

**Comment by tmm** [comment]
Please share a minimal reproduction in a [TypeScript Playground](https://www.typescriptlang.org/play).
