### ISSUE TITLE
bug: docs search is missing results

### ISSUE THREAD

**Issue by holic** [wevm/viem#1782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.6

### Current Behavior

There's no search results for "ishex" but there def is an `isHex` function and page

![image](https://github.com/wevm/viem/assets/508855/39f16c1e-e512-4024-8dc8-ccbf2737f34b)

### Expected Behavior

I'd expect `isHex` function to show up for this search

### Steps To Reproduce

Type "ishex" into viem docs search bar

**Comment by jxom** [comment]
Fixed
