### ISSUE TITLE
bug: PublicClient type is not compatible with opStack client

### ISSUE THREAD

**Issue by donaldinho** [wevm/viem#1784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.6

### Current Behavior

When creating a public client on the opstack there is a type error for variables that have the PublicClient type.

### Expected Behavior

No type error

### Steps To Reproduce

```

publicClient: PublicClient;

constructor() {
      this.publicClient = createPublicClient({
            chain: optimism,
            transport: http(),
        });

```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/github-vr7nbp-3yjm9j?file=index.ts

**Comment by donaldinho** [comment]
figured out that you can do

`publicClient: PublicClient<Transport, typeof optimism>;`

to make this work.
If it's not possible to make it work with just using the PublicClient type it would be good to get the above added to the docs

**Comment by jxom** [comment]
Yep, that is correct. `optimism` has formatters which modifies the types of parameters/return types for blocks, transactions, etc (to cater for OP Stack specific attributes). As a result, the type becomes a little bit stricter, and is unable to match against the widened type (`PublicClient`). So the correct (and best practice) approach would be to pass in your chain to the type like what you have done.
