### ISSUE TITLE
createWalletClient is not working in mobile devices.

### ISSUE THREAD

**Issue by narutodev123** [wevm/viem#1797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.19.11

### Current Behavior

The code below is working fine in web browser but not working mobile web browser. Please suggest
createWalletClient({
                        chain: polygonMumbai,
                        transport: custom(window?.ethereum)
                    })

> 

### Expected Behavior

It should work properly.

**Comment by tmm** [comment]
Please add a minimal reproduction.

**Comment by tmm** [comment]
My guess is `window.ethereum` is not available.

**Comment by narutodev123** [comment]
Thank you @tmm. Yes window.ethereum is not available in mobile so it is coming in catch block  in mobile device web browser how to fix this issue. I have metamask app installed in mobile device.

**Comment by narutodev123** [comment]
Please provide some solution on this. You closed this bug.

**Comment by tmm** [comment]
It's not a bug. It's user error that's why it was closed.

**Comment by narutodev123** [comment]
Can you let me know how to get this same code working in both web browser and mobile browser with viem.
