### ISSUE TITLE
bug: type infernce is not allowing uint8array for eip721

### ISSUE THREAD

**Issue by wanderer** [wevm/viem#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

     "viem": "^1.20.0"

### Current Behavior

to following doesn't work for me
```
    const signature = await wallet.signTypedData({
      types: {
        EIP712Domain: [
          { name: "name", type: "string" },
          { name: "version", type: "string" },
          { name: "chainId", type: "uint256" },
          { name: "verifyingContract", type: "address" },
        ],
        StoreManifest: [
          {
            name: "event_id",
            type: "bytes32",
          },
        ],
      },
      primaryType: "StoreManifest",
      domain: {
        name: "stuff",
        version: "1",
        chainId: BigInt(1),
        verifyingContract: 0xsomeaddress,
      },
      message: {
        event_id: new Uint8Array(32),
        },
    });

```

Results in "type Uint8Array is not assignable to `0x${string}"

### Expected Behavior

I would expect it to take a Uint8Array

### Steps To Reproduce

above

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-kayums?file=index.ts

**Comment by wanderer** [comment]
@tmm why is this to be expected? here 
(https://abitype.dev/config#bytestype) it says bytes is `{ inputs: `0x${string}` | Uint8Array; outputs: `0x${string}` }`

**Comment by tmm** [comment]
ABIType docs are outdated in this case. See the source here: https://github.com/wevm/abitype/blob/main/packages/abitype/src/register.ts#L93
