### ISSUE TITLE
bug: createWalletClient with http transport does not throw error or show type mismatch

### ISSUE THREAD

**Issue by 0xBombadil** [wevm/viem#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.9

### Current Behavior

Creating a wallet client  using `createWalletClient` with a `http()` transport throws no error.

Then trying to perform an action which involves the wallet throws the following error:

```
Uncaught (in promise) MethodNotFoundRpcError: The method does not exist / is not available.

URL: https://cloudflare-eth.com
Request body: {"method":"wallet_addEthereumChain","params":[{"chainId":"0xa","chainName":"OP Mainnet","nativeCurrency":{"name":"Ether","symbol":"ETH","decimals":18},"rpcUrls":["https://mainnet.optimism.io"],"blockExplorerUrls":["https://optimistic.etherscan.io"]}]}

Details: Method not found
Version: viem@2.7.9
    at withRetry.delay.count.count (chunk-D2QXKRKN.js?v=1f13751e:1684:19)
    at async attemptRetry (chunk-D2QXKRKN.js?v=1f13751e:1654:22)
```

### Expected Behavior

Creating a wallet client  using `createWalletClient` with a `http()` transport should either have a type mismatch, or throw an error like:
```
WalletClientInvalidTransport: The transport must allow wallet methods.
```

### Steps To Reproduce

Create an client with http transport.
```
import { createWalletClient, http, type Address} from 'viem';
import { mainnet, optimism } from 'viem/chains';

const client = createWalletClient({ chain: mainnet, account: address, transport: http() });
```
No error or type warning is shown. 

Try adding a new chain.
```
client.addChain({chain: optimism})
```

Get error
```
Uncaught (in promise) MethodNotFoundRpcError: The method does not exist / is not available.

URL: https://cloudflare-eth.com
Request body: {"method":"wallet_addEthereumChain","params":[{"chainId":"0xa","chainName":"OP Mainnet","nativeCurrency":{"name":"Ether","symbol":"ETH","decimals":18},"rpcUrls":["https://mainnet.optimism.io"],"blockExplorerUrls":["https://optimistic.etherscan.io"]}]}

Details: Method not found
Version: viem@2.7.9
    at withRetry.delay.count.count (chunk-D2QXKRKN.js?v=1f13751e:1684:19)
    at async attemptRetry (chunk-D2QXKRKN.js?v=1f13751e:1654:22)
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-bxnwkw?file=index.ts

**Comment by jxom** [comment]
Not really a bug. We can’t determine this eagerly as we would have to perform an RPC request to every known (and ever growing) wallet RPC endpoint at time of instantiation, which is very inefficient!
