### ISSUE TITLE
bug: no search results for `getContract`

### ISSUE THREAD

**Issue by holic** [wevm/viem#1816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.10

### Current Behavior

There's no results for `getContract`, even though it's definitely an exported method from viem:
<img width="1071" alt="image" src="https://github.com/wevm/viem/assets/508855/5d7c9b7e-1a9e-461d-80e2-78826c6d6484">

### Expected Behavior

I would expect this page to have shown up in results:
<img width="989" alt="image" src="https://github.com/wevm/viem/assets/508855/36510640-3628-45b4-bc20-6eaa04726472">

**Comment by jxom** [comment]
Will look into it. Rolled back to a previous deployment for now.
