### ISSUE TITLE
bug: Type 'K' cannot be used to index type

### ISSUE THREAD

**Issue by Spacylion** [wevm/viem#1828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.11

### Current Behavior

When attempting to compile TypeScript files with viem version 2.7.11, a series of errors are encountered, preventing successful compilation.

### Expected Behavior

I expected the TypeScript files to compile successfully without encountering any errors.

### Steps To Reproduce

1. Clone the following GitHub repository: [viem_test](https://github.com/Spacylion/viem_test)
2. Install dependencies by running npm install.
3. Attempt to compile TypeScript files using the command tsc -p tsconfig.json

Full explanation:
# Reproducing TypeScript Compilation Error with viem

This guide will walk you through the steps to reproduce the TypeScript compilation error when using the viem library.

## Prerequisites

Before starting, ensure that you have Node.js and npm installed on your system.

## Steps

1. Create a new directory and navigate into it:

    ```bash
    mkdir VIEM_TEST
    cd VIEM_TEST
    ```

2. Initialize a new npm project:

    ```bash
    npm init -y
    ```

3. Install the viem library:

    ```bash
    npm install viem@2.7.11
    ```

4. Create a TypeScript file named `index.ts` with the following content:

    ```typescript
    // index.ts
    import { createPublicClient } from "viem/_types/clients/createPublicClient";
    import { createWalletClient } from "viem/_types/clients/createWalletClient";


    function greet(name: string): string {
        console.log( createPublicClient);
        console.log(  createWalletClient);
        
        return `Hello, ${name}!`;
        
    }

    const personName: string = "John";
    console.log(greet(personName));

    ```

5. Create a `tsconfig.json` file with the following configuration:

    ```json
    {
        "compilerOptions": {
            "forceConsistentCasingInFileNames": true,
            "newLine": "lf",
            "noFallthroughCasesInSwitch": true,
            "noImplicitReturns": true,
            "noUncheckedIndexedAccess": true,
            "noUnusedParameters": true,
            "strict": true,
            "target": "ES2019",
            "moduleResolution": "node",
            "esModuleInterop": true
        },
        "include": [
            "src/**/*.ts"
        ]
    }

    ```

6. Run the TypeScript compiler:

    ```bash
    tsc --build
    ```

You should see the following error:
> errors.txt

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/Spacylion/viem_test

### Anything else?

The compilation errors occur primarily in the 
**node_modules/viem/_types/utils/formatters/transaction.d.ts** 
and 
**node_modules/viem/_types/utils/formatters/transactionRequest.d.ts** 
files.

These errors hinder the compilation process and need to be addressed for smooth integration with viem version 2.7.11.
[errors.txt](https://github.com/wevm/viem/files/14346330/errors.txt)

**Comment by jxom** [comment]
Please enable `skipLibCheck`
