### ISSUE TITLE
bug: createClient: Type "fallback" is not assignable to type "http"

### ISSUE THREAD

**Issue by LufyCZ** [wevm/viem#1840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.11

### Current Behavior

A const object with multiple chains, where at least one uses the `fallback` transport cannot be dynamically indexed for use in `createPublicClient`. Indexing the object with a specific chain works fine, as the type gets reduced to that specific chain.

### Expected Behavior

no error

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwBYxmANHAZgQwDZ4BGOAxgNaYlQCmOM1ACgK6F7AkDCb1AdjAL7YoEEHADkAN2DUQYgFChIsRDiiFgMKExAA5CBJyZCEYoKzDRk6SAD0JJDmA8AzvLkkIL+BwdOAkgAmcAC8iHJwEXAARACCAEoAQn4AKnEAqgCyAPo6APIAajFRAFxwAIzo4ZFRCbkJRaUATHL8cnLUAB5K8B5ecDgDOCFhEQDaPo48gQB08UmpmTkFMQC6pQhVEfaTparqmtp6BpWRcJo4Lt2lKGgAFJuRAAY3YM7FNjZE0wFQYCTT0AA5jYIIDfiQAPw8agwADu0DIwT2Gi0IAAtDx9DgAGQBMjUACewQAJAgfn9AvxHidIgBKGn8Sqtdw0OiMFhsTjcPi3QY4ca+KYBWaJFLpbJ5QorWltTrdOC9ZzwQgqwjDDZjCb+YVzMWLSWrdYPbZOXZqFGHLE0iLnS7QGDXVBge6nCLPJ1vD5fcn-IEgsF-KEw+FQRHIg7ozEGXH4omkn2U6kPelVRlVAWTGa1eprEaRE08UrGYjWs5QC7OK7YfBEUhkF2u0YPU4vW7FnDTcFpKB4Zzfai4Jh4GDTF6jAAM0tLLadtzEL09NhoYE5HZwBg603b02hcIRYhTrrgK2neaP5Z4ZFKB2op7Tp0PcDTzKotHozFY7C40h5qsIozKRoAGZ+mcOBYwgLAzgJMBqEguA-2lIA

**Comment by jxom** [comment]
Resolved as per TG chat.

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwBYxmANHAZgQwDZ4BGOAxgNaYlQCmOM1ACgK6F7AkDCb1AdjAL7YoEEHADkAN2DUQYgFChIsRDiiFgMKExAA5CBJyZCEYoKzDRk6SAD0JJDmA8AzvLkkIL+BwdOAkgAmcAC8iHJwEXAARACCAEoAQn4AKnEAqgCyAPo6APIAajFRAFxwAIzo4ZFRCbkJRaUATHKCOM5wHl5yctQAHkrwnc7wOKM4IWERANo+jjyBAHTxSamZOQUxALqlCFUR9nOlquqa2noGlZFwmjguA6UoaAAUe5EABo9gzsU2NkQLASgYBIC2gAHMbBAwUCSAB+HjUGAAd2gZGCxw0WhAAFoePocAAyAJkagAT2CABIEIDgYF+G9LpEAJSM-iVfjdKi0ejMVjsLjSPhPMY4Ga+eYBJaJFLpbJ5QqbJndPoDDqeYZwQhawgTXYRX5XQ0APVhVTFc0Wyxla3lWx2rwOTiOakxZ3xjIiNzu0BgD1QYBehrgH3931+-xpIPBkOhwPhiJRUDRGNOOLxBiJJPJVMjdIZrxZVTZZtm-kltXq20mkUdPFKxmIHuuUFuznu2HwRFIZEDhqmryunyeDZwCxhaSgeGcAOouCYeBgC0+UwADIqm4P-U8xJ8wzYaGA2CRRzgDL0FiOFgjkaixIWg5sN9Wgy2eGRSqdqE-i1d73Bi607RDDAnI0HQjAsEeAq8DAw7alMZSKkAA
