### ISSUE TITLE
bug: type cannot be inferred without a reference to .../celo/types

### ISSUE THREAD

**Issue by LufyCZ** [wevm/viem#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.11

### Current Behavior

Using the celo chain with the following entries in `tsconfig`

```
{
  "moduleResolution": "node16",
  "declaration": true
}
```

causes an error.

### Expected Behavior

no error

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-wvwoer?file=index.ts

**Comment by jxom** [comment]
Fixed: 0c2b6b2e574e95fe5cb900030c46251cb405bef2
