### ISSUE TITLE
bug: serializeTransaction does not handle chainId correctly for legacy transactions

### ISSUE THREAD

**Issue by niklasnatter** [wevm/viem#1849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.8

### Current Behavior

Hey,
I had an interesting error today where i could not reproduce the hash of an included transaction. I recently moved this part of my code from ethers to viem. By debugging the intermediate values of the previous/new implementation, I suspect that the `serializeTransaction` util of viem does not handle legacy transactions with an explicit `chainId` correctly.

### Expected Behavior

The result of the `serializeTransaction` util should match the published transaction.

### Steps To Reproduce

```ts
const hash =
  '0x6ed21df69b02678dfb290ef2a43d490303562eb387f70795766b37bfa9d09bd2';

const client = createPublicClient({
  chain: mainnet,
  transport: http(),
});
const tx = await client.getTransaction({ hash });

const serializedWithChainId = serializeTransaction(
  { ...tx, data: tx.input },
  tx
);

console.log(keccak256(serializedWithChainId) === hash);
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-sifxxk?file=index.ts

### Anything else?

By removing the `chainId` property from the transaction, I am able to match the hash of the published transaction:
```ts
if (tx.type === 'legacy') {
    delete tx.chainId;
}
```

**Comment by jxom** [comment]
Hmm weird. We do have tests for this. Will have a look today.

**Comment by niklasnatter** [comment]
Wow, thanks a lot for the quick response! Everything works as expected with version `2.7.14`
