### ISSUE TITLE
bug: the combination of scroll and base chains causes the resulting publicClient to not be compatible with the PublicClient type

### ISSUE THREAD

**Issue by LufyCZ** [wevm/viem#1855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.13

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-3dustt?file=index.ts%2Cchains.ts%2Ctsconfig.json

**Comment by jxom** [comment]
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwFBzgCxjMAaFcDCaAhsAHa6owCeYApnAAoCuARgDbADG+HtpM+CKQBmwAOYU4nKLSIxazdlx7A+MSdToFe-DTXqKO3HerwAVKEVIBnSLFwBfOMKgQQcAOQA3VSA9JQO3hkVBYia1pJa2kINjZJEBJSUlpTJxc3Tx9aEAB6TmIya38kWgAPIKkha3hCJIBJABM4AF5EPAAhAEEAZQBRAC44AA4AFgBWAGZJHvwAJQB5ABkloanRyfGAJkc4cKqbGFKK6HhNejqyJta4AApziGECQtImgEoAbQBrWipHuAeT0ur0aAF0kMdKpxqvAwKwjBYrLZTtYbiE4B9gU0AHTdfqgoYYLC3ABEJLekkxLxxs0WKwJ6EwYFJ5N2+2hhzg1jkwGsoloqLmtGhUEaAB4sY1sHBETYggA+CHlKEwuBwpTcF6otofPBhCJRGJxXCgvaojk1Lk8vmqQWyRpCNhUCUvD6gxWQ04HS3qowqNSCETiNF4KkNRq43p9Bno1AFJJDfWRPCUSxy05DX1cWXI2DWMNXCN46OSByUyXY2nLJYxlNSF5DaKuY11mBp3MwTPw7PtoL5itV+mltnm1XcmC8-l2kXivCSySGZQmQOiMRwABkiHrCbugLV3c1SWsn1ITBALFoUFNDiQHot8HjhZuAEYzXBT+fLxD71JhGu2lmxiqPwK7iB8j4gm+Px-E8e6Af6IFCKu4JID+nAmK+bTSLI8iLkBai3OiEFDJwf7YhBGi9hmv5iNibZIkEjhvAA3BCYipLc6HATAz5vBCwhMKQnATkIcDsTAYoQXA5TyKQjSosCcAAD5wIJjS0KIKSNPKnEmFsQx4QhEk5ox25kPKbztHG1SxLQ2JsBAYiktYTBgCS0pcWoWzYkQnDQoJMB8Q4QA
