### ISSUE TITLE
bug: Cannot destructure property 'abi'  of paramaters as it is undefined

### ISSUE THREAD

**Issue by MhAliCakmak** [wevm/viem#1857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.13

### Current Behavior

I was using the simulateContract() function before calling the writeContract() function. and I was getting an error with the value parameter coming from msg.value.

### Expected Behavior

simulateContract fonksiyonunda value parametresinden hata olmamasını bekliyorudum

### Steps To Reproduce

I was using the simulateContract() function before calling the writeContract() function. and I was getting an error with the value parameter coming from msg.value. code below 
![image](https://github.com/wevm/viem/assets/79807829/d10f3bc0-a549-4f72-9c06-d6479cfedf61)

error message 
![image](https://github.com/wevm/viem/assets/79807829/b43ac5e4-e0bf-428e-9d8e-591099b10bc1)

but when i use just writeContract without simulateContract work. i think here is a bug in simulateContract function for value parameter.
![image](https://github.com/wevm/viem/assets/79807829/7dec268d-00b2-4263-8b5b-4667375130e1)
in here everything is work in here

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
