### ISSUE TITLE
bug: viem docs search remembers last query

### ISSUE THREAD

**Issue by holic** [wevm/viem#1880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.16

### Current Behavior

When I type `viem.sh` into my browser, I hit cmd+k to pop open search to find docs, but the query is already filled in with my most recent query. I have to clear this before I can start searching again.

### Expected Behavior

I would expect the search query to be empty so that I can immediately start typing what I am searching for, like MacOS Spotlight, etc.

**Comment by tmm** [comment]
This is [intentional](https://github.com/wevm/vocs/blob/main/src/app/components/SearchDialog.tsx#L29) at the moment, but makes sense to remove. Feel free to submit a PR to Vocs and this can flow downstream to Viem.
