### ISSUE TITLE
zksync deployment: Failed to serialize transaction: toAddressIsNull

### ISSUE THREAD

**Issue by wighawag** [wevm/viem#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.12

### Current Behavior

The following (setup with zk chain  fails:
```
const txHash = await client.wallet.deployContract({
  abi: ZKSyncGreeter.abi,
  bytecode: ZKSyncGreeter.bytecode as `0x${string}`,
  args: ["hello"]
});
```

It fails with the following error:

```
Failed to serialize transaction: toAddressIsNull
```

### Expected Behavior

I expect to be able to use viem walletClient.deployContracts on zksync network

### Steps To Reproduce

compile a contract with zksolc and execute:
```
const txHash = await client.wallet.deployContract({
  abi: ZKSyncGreeter.abi,
  bytecode: ZKSyncGreeter.bytecode as `0x${string}`,
  args: ["hello"]
});
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-xixyhc?file=index.ts

**Comment by kvmanas** [comment]
It seems like the problem is that you're not passing the `account.address` value to the `deployContract` method. 
**Here's how you might adjust your code:**

```javascript
const txHash = await walletClient.deployContract({
    account: account.address,
    abi: Greeter.abi,
    bytecode: Greeter.bytecode,
    args: ['hello'],
  });
```

### Link: 
[https://stackblitz.com/edit/viem-getting-started-ownffh?file=index.ts](https://stackblitz.com/edit/viem-getting-started-ownffh?file=index.ts)

**Comment by wighawag** [comment]
@kvmanas your example has the following error

```
TransactionExecutionError: The method does not exist / is not available. URL: https://sepolia.era.zksync.dev Request body: {"method":"eth_sendTransaction","params":[{"data":"0x...","from":"0x903CF92d3Ff6174f943ddF9679AF099d5017d7B5"}]} Request Arguments: from: 0x903CF92d3Ff6174f943ddF9679AF099d5017d7B5 data: 0x... Details: Method not found Version: viem@2.7.16
```

this is because when you specify the account, it will try to use `eth_sendTransaction` on the rpc endpoint instead of signing the tx locally via the privateKeyAccount

So this is not the solution here

**Comment by jxom** [comment]
This error message seems to be coming from the JSON-RPC API (ie. `https://sepolia.era.zksync.dev`), and that it doesn't allow gas estimation with a nullish `to` (though it should be valid for contract deployments). Will follow up with the zkSync team.

**Comment by wighawag** [comment]
Feel like this issue should be reopened until there is doc and example that works.

**Comment by wighawag** [comment]
As it stands, the issue is that deployContract need to have all its parameter defined 

see : https://github.com/zkSync-Community-Hub/zksync-developers/discussions/465
and : https://github.com/zkSync-Community-Hub/zksync-developers/discussions/433

zksync team says they are working on improving it but in the meantime, having proper typing for these required fields would be helpful
