### ISSUE TITLE
bug: `sendTransaction` returns a null hash when rejecting a transaction with Rainbow wallet

### ISSUE THREAD

**Issue by ted-palmer** [wevm/viem#1893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^2.7.12

### Current Behavior

Normally, when rejecting a transaction in your wallet, viem throws a TransactionExecutionError. When using Rainbowkit and Rainbow wallet, `sendTransaction` returns 'null' as a string

### Expected Behavior

An error is thrown

### Steps To Reproduce

Reject any transaction while using Rainbow in Rainbowkit. See minimal reproducible example below

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/devbox/rainbow-wallet-rejection-demo-63kgpf?file=%2Fpackage.json%3A9%2C24

### Anything else?

It's possible that this is an issue on Rainbow's side, but I don't think sendTransaction should ever return null. Lmk if I can provide any more details

**Comment by jxom** [comment]
To conform to the spec for `eth_sendTransaction`, wallets should either return a hash or throw an error. In this case, I would expect the wallet to throw an error with a [4001 – User rejected request](https://eips.ethereum.org/EIPS/eip-1193#:~:text=4001,rejected%20the%20request.) RPC error.
