### ISSUE TITLE
bug: wrong calculation for gasLimit used in L2ToL1MessagePasser's initiateWithdrawal() when calling buildInitiateWithdrawal

### ISSUE THREAD

**Issue by freepoi** [wevm/viem#1903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.9

### Current Behavior

``` TS
const publicClientL1 = createPublicClient({
    chain: l1,
    transport: http(),
 }).extend(publicActionsL1())
 
 const args = await publicClientL1.buildInitiateWithdrawal({
    account: address,
    to: address,
    value: amount,
    // gas: any BigInt
  });
```
I'm using OP Stack feature. If I want to withdraw an amount which is more than the balance I have on L1. 
`buildInitiateWithdrawal` will report an error: `failed with 50000000 gas: insufficient funds for gas * price + value: address 0x53d0765Cf432Db8447a975A23b99884b99D57518 have 199910429611794338 want 290000000000000000`.

### Expected Behavior

No error

### Steps To Reproduce

Any OP stack with L1 and L2.
Here are contract addresses what we have already set up. L1 is sepolia:
(Can refer to our OP stack's bridge UI: https://op-bridge.alt.technology/deposit?id=20240219)
```
    l1: {
      ...networks.sepolia,
      AddressManager: "0x45daA0C6BE4D09987D422b29503A9A78E8f25584",
      L1CrossDomainMessengerProxy: "0xbDC643756A28F3A745A32772747Ea37dc88817Ba",
      L1StandardBridgeProxy: "0x4AAAC6Bc2CbFdD2D6491524D781eFf50F3427875",
      L2OutputOracleProxy: "0x38A5aAC01e89b9523515a73e7e5b4679EC625D3E",
      OptimismPortalProxy: "0xed76cb607DE400d528129f2D190F137bdE59575F",
    }
    l2: {
      id: 20240219,
      name: "OP Demo Testnet",
      network: "l2",
      nativeCurrency: {
        decimals: 18,
        name: "Ethereum",
        symbol: "ETH",
      },
      rpcUrls: {
        public: { http: ["https://op-demo.alt.technology/"] },
        default: { http: ["https://op-demo.alt.technology/"] },
      },
      blockExplorers: {
        default: {
          name: "explorer",
          url: "https://op-demo-explorer.alt.technology/",
        },
      },
      iconUrl: `${window.location.origin}/chains/alt.svg`,
    }
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://op-bridge.alt.technology/deposit?id=20240219

### Anything else?

I checked source code, `gas` argument in buildInitiateWithdrawal is used for second argument in OP' s contract `L2ToL1MessagePasser.sol`:
https://github.com/ethereum-optimism/optimism/blob/b36eb5515cc2a34a15383b2eee488dbac83d6caf/packages/contracts-bedrock/src/L2/L2ToL1MessagePasser.sol#L73

If I don't provide `gas`  for `buildInitiateWithdrawal()`, it will total wrongly estimate gas.
This is payload in JSON-RPC what it actually sent, (0x53d0765Cf432Db8447a975A23b99884b99D57518 is my account):
```
{
  "jsonrpc": "2.0",
  "id": 10,
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0x53d0765Cf432Db8447a975A23b99884b99D57518",
      "to": "0x53d0765Cf432Db8447a975A23b99884b99D57518",
      "value": "0x2a303fe4b530000"
    }
  ]

```
You can see `to` is not address of `L2ToL1MessagePasser` , but my receipt address provided in arguments of `buildInitiateWithdrawal`

This is the call track of `buildInitiateWithdrawal`, 
> https://github.com/wevm/viem/blob/8553a287ff1589c1d22223f26241c793df32336e/src/chains/opStack/actions/buildInitiateWithdrawal.ts#L104
> https://github.com/wevm/viem/blob/8553a287ff1589c1d22223f26241c793df32336e/src/actions/wallet/prepareTransactionRequest.ts#L259

**Comment by FreePoi** [comment]
Hi. Is this issue confirmed?

**Comment by joeydefi** [comment]
May be related with this issue we've been stuck with for almost 2 weeks:

https://github.com/wevm/viem/discussions/1909#discussioncomment-8841870

**Comment by jxom** [comment]
Not sure if this is actually an issue. We need to calculate the estimated gas of execution on the L1, which is sent via `L2ToL1MessagePasser.initiateWithdrawal`.
