### ISSUE TITLE
bug: TransactionReciept's blockNumber should be Hex instead of bigint

### ISSUE THREAD

**Issue by KorbinianK** [wevm/viem#1911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.11

### Current Behavior

The `TransactionReceipt` Type uses `bigint` as type for blockNumbers, when in reality they are `Hex`

Can easily be verified by calling `eth_getTransactionReceipt` on any transaction Hash. (see steps to reproduce)

```typescript
export type TransactionReceipt<
  TQuantity = bigint,
  TIndex = number,
  TStatus = 'success' | 'reverted',
  TType = TransactionType,
> = {
...
  /** Number of block containing this transaction */
  blockNumber: TQuantity
...
}
```

### Expected Behavior

```typescript
export type TransactionReceipt<
  TQuantity = bigint,
  TIndex = number,
  TStatus = 'success' | 'reverted',
  TType = TransactionType,
> = {
...
  /** Number of block containing this transaction */
  blockNumber: Hex // <---
...
}

```

### Steps To Reproduce

```bash
curl --location 'https://ethereum-rpc.publicnode.com' \
--header 'Content-Type: application/json' \
--data '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_getTransactionReceipt",
  "params": ["0xa5474db942386108779f05be0e579aecdb779bf9307599402a238e13c0610bd4"]
}'
```

returns:

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0x8e3bdebe1c215bbccc8c8a1c1b3e5018844050f89192b790e82d2ad341664115",
        "blockNumber": "0x127aa02", // <---
        "contractAddress": null,
        
       }
}
 ```

**Comment by jxom** [comment]
This is intentional.

**Comment by KorbinianK** [comment]
@jxom can you elaborate why the type should differ from the actual response?

**Comment by jxom** [comment]
Viem decodes RPC response values (encoded quantities, indexes, data, etc) – and also keeps consistent with other tooling. If you want the raw response, you can use `client.request({ method: 'eth_getTransactionReceipt', params: ['0x...'] })`
