### ISSUE TITLE
bug: TypeScript 5.4.2 cannot distinguish overloaded contract methods.

### ISSUE THREAD

**Issue by jxom** [wevm/viem#1916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.20

### Current Behavior

TypeScript 5.4.2 cannot distinguish overloaded contract methods.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/wevm/viem/actions/runs/8179252748/job/22364947936

**Comment by jnsdls** [comment]
this bit me as well, I might get around to put up a PR sometime later this week if it's not fixed by then

**Comment by dalechyn** [comment]
![Screenshot 2024-03-28 at 20 29 06](https://github.com/wevm/viem/assets/35642018/aaf874b5-eeb1-48d4-9485-885b817435f9)
shows correct type when `as const` is added to `args` array.
