### ISSUE TITLE
bug: incorrect `l1Fee` calculations for `opStack` chains

### ISSUE THREAD

**Issue by Ncookiez** [wevm/viem#1918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.9

### Current Behavior

Current functions from `viem/op-stack` to estimate L1 fees are incorrect. This is probably due to a typo on the Optimism docs.

In multiple places, the Optimism docs state that the following should be sent to the `getL1Fee` method on the gas oracle contract:
![image](https://github.com/wevm/viem/assets/22108522/fec5603d-dc02-4c79-8a7d-26b4ead0f5a9)

This is incorrect - the contract takes in an **unsigned** serialized transaction. This can be observed in the following:
- [Parameter description on the contract itself](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L2/GasPriceOracle.sol#L35)
- [Usage on Optimism's own SDK](https://github.com/ethereum-optimism/optimism/blob/ee058e413/packages/sdk/src/l2-provider.ts#L74)
- [Usage on Rainbow Wallet](https://github.com/rainbow-me/browser-extension/blob/9b0cd4bc9e7ecc1173d0de07fcb0497e36985b5c/src/core/utils/gas.ts#L513) (which is, in my experience, very accurate)

This means that where `viem` is inputting a signature to to the serialized transaction, transaction l1 fee estimates are being overpriced. Some locations where this is being done (there might be more):
- [estimateL1Fee#L129](https://github.com/wevm/viem/blob/main/src/chains/opStack/actions/estimateL1Fee.ts#L129)
- [estimateL1Gas#L129](https://github.com/wevm/viem/blob/main/src/chains/opStack/actions/estimateL1Gas.ts#L129)

This also applies to the `getL1GasUsed` method in the gas oracle contract.

### Expected Behavior

When calling the `getL1Fee` or `getL1GasUsed` methods to estimate L1 gas/fees, no signature should be passed to the serialization function.

### Steps To Reproduce

I shared many code examples above, but to reproduce this easily the best way would probably be to:

1. Estimate L1 fees for a transaction on an OP Stack chain using `viem`.
2. Immediately submit that transaction.
3. See that the resulting L1 fee onchain is lower than estimated.

**Comment by roninjin10** [comment]
Nice catch @Ncookiez you are correct the gas price oracle assumes worst case in terms of how many bytes the sig is and expects an unsigned tx

**Comment by roninjin10** [comment]
@Ncookiez Where all in the optimism docs did you see this bug? I only found one instance here https://github.com/ethereum-optimism/docs/pull/547/files

**Comment by roninjin10** [comment]
So the optimism docs are correct. The confusion is the docs you screenshotted are talking about the actual gas that the protocol charges not the gas estimation function which naturally is going to overestimate.

HOwever you are correct that viem shouldn't be including a signature stub

**Comment by Ncookiez** [comment]
> the docs you screenshotted are talking about the actual gas that the protocol charges not the gas estimation function

Not sure I fully understand - but I might just be ignorant of some of the intricacies of rollups in general...

I'm sure after 4844 the docs will have to be cleaned up somewhat, so if some a clarification can be added there I'm sure others would appreciate it as well.

Either way, thank you for the quick response! I'm happy it seems like an easy fix on `viem` for now. I was also going to make a PR on the Optimism docs but I guess it's good I waited a bit.
