### ISSUE TITLE
bug: toFunctionSelector throws error when given string input

### ISSUE THREAD

**Issue by goblinoats** [wevm/viem#1936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.22

### Current Behavior

Calling toFunctionSelector with string input will throw the error Error: expected Uint8Array, got object

 ❯ toBytes node_modules/.pnpm/@noble+hashes@1.3.2/node_modules/@noble/hashes/src/utils.ts:105:25
 ❯ hashC node_modules/.pnpm/@noble+hashes@1.3.2/node_modules/@noble/hashes/src/utils.ts:177:63
 ❯ keccak256 node_modules/.pnpm/viem@2.7.22_typescript@5.3.3/node_modules/viem/utils/hash/keccak256.ts:29:14
 ❯ hash node_modules/.pnpm/viem@2.7.22_typescript@5.3.3/node_modules/viem/utils/hash/hashSignature.ts:6:33
 ❯ hashSignature node_modules/.pnpm/viem@2.7.22_typescript@5.3.3/node_modules/viem/utils/hash/hashSignature.ts:14:10
 ❯ toSignatureHash node_modules/.pnpm/viem@2.7.22_typescript@5.3.3/node_modules/viem/utils/hash/toSignatureHash.ts:16:10
 ❯ Module.toFunctionSelector node_modules/.pnpm/viem@2.7.22_typescript@5.3.3/node_modules/viem/utils/hash/toFunctionSelector.ts:23:9

### Expected Behavior

It should return the function selector in hex encoded bytes. 

If I write my code in the following way below, I get the expected result:

const signature = sliceHex(keccak256(toHex(toBytes('myFunction(((uint256,uint256)[],(uint256,uint256,uint256,uint256)[]))'))), 0, 4);

### Steps To Reproduce

try this call somewhere: 

 toFunctionSelector('myFunction()');

**Comment by tmm** [comment]
Works fine for me. Can you attach a minimal reproduction and I'll open this again.
