### ISSUE TITLE
bug: signTransaction throws error

### ISSUE THREAD

**Issue by aarifkhamdi** [wevm/viem#1937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.4

### Current Behavior

[Here](https://github.com/wevm/viem/blob/86e06fcd1790e20e5ff16b3c214f9ae99525baf1/examples/clients_wallet-client/index.tsx#L22) example for sendTransaction is provided. I try to replace sendTransaction with signTransaction and it throws error "
Details: unknown account"

```
const t = await walletClient.signTransaction({
      account,
      to: '0x0000000000000000000000000000000000000000',
      value: 1n,
      nonce: 10,
      gas: 100500n,
      gasPrice: 1234n,
});
console.log(t);
```

### Expected Behavior

No errors, transaction signed successfully

### Steps To Reproduce

Try to use "signTransaction" method in browser with rabby wallet

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/aarifkhamdi/viem/blob/main/examples/clients_wallet-client/index.tsx

**Comment by jxom** [comment]
Closing as Rabby issue.
