### ISSUE TITLE
bug: Cannot destructure property 'gasLimit' of '(intermediate value)' as it is null.

### ISSUE THREAD

**Issue by karacurt** [wevm/viem#1946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.22

### Current Behavior

Randomly (usually when loads the page and click it fast), the `writeContract` function from wagmi, reverts with `Cannot destructure property 'gasLimit' of '(intermediate value)' as it is null.`

This print bellow show that the error happens in metamask and in viem package. This print was made from DevTools console log of Google Chrome:

![image](https://github.com/wevm/viem/assets/38267570/b6a456de-4fd3-4769-ab98-2f2f2a04af5f)
`{
    "code": -32603,
    "message": "Cannot destructure property 'gasLimit' of '(intermediate value)' as it is null.",
    "data": {
        "originalError": {}
    }
}`
![image](https://github.com/wevm/viem/assets/38267570/8a91187b-aaa0-44a8-ad4a-fa7c1b81eb72)
![image](https://github.com/wevm/viem/assets/38267570/6b0787d9-ebca-44ac-8d6a-b05395a569fc)

### Expected Behavior

Should open metamask pop-up to execute transaction

### Steps To Reproduce

1. Call writeContract in wagmi (2.5.7) in a NextJs (13.4.19) project

**Comment by jxom** [comment]
This is an internal error coming from the RPC server.
