### ISSUE TITLE
bug: `getBlobBaseFee` is not exported from public clients decorators

### ISSUE THREAD

**Issue by 0xpolarzero** [wevm/viem#1949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.6

### Current Behavior

The public action `getBlobBaseFee` (along with the types) are not exported from the public clients decorators. Thus, it can't be accessed from the provider, although it is very well present in the codebase.

### Expected Behavior

I believe it should be imported & returned along other public actions [in clients/decorators/public.ts](https://github.com/wevm/viem/blob/main/src/clients/decorators/public.ts).

**Comment by jxom** [comment]
Added. Releasing shortly.
