### ISSUE TITLE
bug: incompatible types

### ISSUE THREAD

**Issue by aarifkhamdi** [wevm/viem#1955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.6

### Current Behavior

OP_STACK chains are incompatible with chain property of createPublicClient

### Expected Behavior

it is possible to pass optimism/base to the chain property

### Steps To Reproduce

1. clone my repo https://github.com/aarifkhamdi/viem-bug
2. `pnpm i`
3. open https://github.com/aarifkhamdi/viem-bug/blob/f4f3a9f59883987f41e56feb4af69ed521453434/src/main.ts#L6

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/aarifkhamdi/viem-bug

**Comment by jxom** [comment]
Works for me in TS Playground: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjgQwMUMADOfDt14DhogPTIGGYFVUTJkgBQZVATyrI4lgJRwAvAD5EkuCgin4ZEoadxR0LFxCEnJgmEsEH18UIxMALgUlFXVaRN8YKAxTWRh0phYXHN82ZylE5H9VeGIIZABrADk8EAI0KFCMAHdjQNiAOgBzNBgAISIWjq6eqBda33rTCCI0UbnxywADWfm4KkXe9IASBGa2zu7etn2ayWqVoA

Make sure you have `"strict": true` in your TS config.

**Comment by aarifkhamdi** [comment]
> Works for me in TS Playground: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjgQwMUMADOfDt14DhogPTIGGYFVUTJkgBQZVATyrI4lgJRwAvAD5EkuCgin4ZEoadxR0LFxCEnJgmEsEH18UIxMALgUlFXVaRN8YKAxTWRh0phYXHN82ZylE5H9VeGIIZABrADk8EAI0KFCMAHdjQNiAOgBzNBgAISIWjq6eqBda33rTCCI0UbnxywADWfm4KkXe9IASBGa2zu7etn2ayWqVoA
> 
> Make sure you have `"strict": true` in your TS config.

viem does not follow `{ "exactOptionalPropertyTypes": true }`

**Comment by aarifkhamdi** [comment]
@jxom https://www.typescriptlang.org/play?exactOptionalPropertyTypes=true#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjgQwMUMADOfDt14DhogPTIGGYFVUTJkgBQZVATyrI4lgJRwAvAD5EkuCgin4ZEoadxR0LFxCEnJgmEsEH18UIxMALgUlFXVaRN8YKAxTWRh0phYXHN82ZylE5H9VeGIIZABrADk8EAI0KFCMAHdjQNiAOgBzNBgAISIWjq6eqBda33rTCCI0UbnxywADWfm4KkXe9IASBGa2zu7etn2ayWqVoA

**Comment by tmm** [comment]
[Previous PR](https://github.com/wevm/viem/pull/453) to get Viem working with `"exactOptionalPropertyTypes"`. Someone needs to revive it and push it over the finish line :)

**Comment by jxom** [comment]
It'll need a decent rebase 😂
