### ISSUE TITLE
bug: boolean conversion in `encodeAbiParameters` yields bad bytestring output

### ISSUE THREAD

**Issue by colinnielsen** [wevm/viem#1960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.10

### Current Behavior

[Sandbox Link](https://codesandbox.io/p/sandbox/viem-test-36lnnz)

When attempting to serialize a inputs against an abi, the value: "true" is not coerced correctly, and yields "NaN" inline in the bytestring output
<img width="187" alt="Screenshot 2024-03-15 at 5 19 20 PM" src="https://github.com/wevm/viem/assets/33375223/49005346-8de0-4a27-91e1-d4fd47f343ba">

### Observations
- Occurs in in standard inputs, as well as nested arrays or structs.
- "1", "0", 0, 1, 0n, 1n are all "coerced" properly
- "1235" is put into the bytestring as 1235.... (this makes the bytestring invalid)

### Expected Behavior

- Should coerce "true" or "false" to `true` and `false` OR throw an error.
- "1235" should throw an error

### Steps To Reproduce

abi encode a bool with any of the above inputs

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/viem-test-36lnnz

**Comment by jxom** [comment]
Our lords and saviors at TypeScript will save us from these issues, but I have added a condition just incase.
