### ISSUE TITLE
bug: client side error on viem documentation website

### ISSUE THREAD

**Issue by LeTamanoir** [wevm/viem#1962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.0.0

### Current Behavior

A client side error is thrown when clicking the share link button of the `Getting started with zkSync` title on [https://viem.sh/zksync](https://viem.sh/zksync)

### Steps To Reproduce

- go to https://viem.sh/
- then hover the `Extensions` navbar menu
- click zksync
- click the copy link button of `Getting started with zkSync`
<img width="513" alt="image" src="https://github.com/wevm/viem/assets/51637671/6b1ed1fd-665c-45a4-8280-eb8c631b4f15">

- and you will get this
<img width="998" alt="image" src="https://github.com/wevm/viem/assets/51637671/55616e76-60c6-4f4a-ae09-bc477ce69fe5">

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://viem.sh/zksync

**Comment by tmm** [comment]
Works fine for me. What browser are you using?

**Comment by Yuripetusko** [comment]
Getting the same when clicking this link
<img width="160" alt="image" src="https://github.com/wevm/viem/assets/666169/45ab0fa8-0e8d-47e0-ab7f-cd45dfdf9d2b">


Arc browser (chromium)

**Comment by jxom** [comment]
Fresh build will fix.
