### ISSUE TITLE
bug: getContractAddress (CREATE2) yield a different address

### ISSUE THREAD

**Issue by fabdarice** [wevm/viem#1964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.19

### Current Behavior

The address output from `getContractAddress` is different than the one generated by my solidity factory.

### Expected Behavior

The address should be identical.

### Steps To Reproduce

Typescript

```
      const bytecode = "0x..." // Output from `forge inspect ERC20 bytecode` 
      const name = "hello";
      const symbol = "HEL";
      const creationCodeWithArgs = toBytes(
        bytecode +
          encodeAbiParameters(parseAbiParameters('string, string'), [name, symbol]).slice(2),
      );

      const saltBytes = toHex(1, { size: 32 });
      address = getContractAddress({
        bytecode: creationCodeWithArgs,
        from: "0x.....", // Address of the Factory contract
        opcode: 'CREATE2',
        salt: saltBytes,
      });
```  

Solidity 
```
    function createToken(string memory name, string memory symbol, bytes32 salt) public returns(address) {
        ERC20 token = new ERC20{salt: salt}(name, symbol);
        return address(token);
     }
```

**Comment by jxom** [comment]
I can't reproduce this when I deploy my ERC20 contract via a Create2 Factory. 

Please reopen with a minimal reproducible example.

**Comment by jxom** [comment]
Here is my reproduction if helpful: https://github.com/wevm/viem/pull/new/1964

Feel free to break it.
