### ISSUE TITLE
bug: `normalize` crashes on certain ens names

### ISSUE THREAD

**Issue by magiziz** [wevm/viem#1965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.10

### Current Behavior

When doing something like `normalize("yīnyáng.eth")` it throws an error. Here is the ens name for more details: https://app.ens.domains/0x2031734704dcc0c56f5588dc737851154b44651b

### Expected Behavior

It shouldn't crash if there is a disallowed character.
![image](https://github.com/wevm/viem/assets/53529533/a89d894a-88dc-454f-828d-98f42e9d7e57)

### Steps To Reproduce

Copy paste this  `normalize("yīnyáng.eth")` into your app

**Comment by jxom** [comment]
Seems to fail validation here: https://adraffy.github.io/ens-normalize.js/test/resolver.html#y%C4%ABny%C3%A1ng.eth
