### ISSUE TITLE
bug: Token approval failed TypeError: hex_.replace with deployContract

### ISSUE THREAD

**Issue by RichelleJi** [wevm/viem#1976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

    "viem": "^2.8.12",

### Current Behavior

 await walletClient.deployContract({
        abi: AirdropABI,
        account: account,
        bytecode: process.env.AIR_DROP_CONTRACT_BYTECODE as `0x${string}`,
        args: [rootHash, tokenAmounts[0]],
      });

the error message reads:  Token approval failed TypeError: hex_.replace

### Expected Behavior

address deployed

**Comment by jxom** [comment]
Thanks for reporting. Can you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) via https://new.viem.sh or a separate repo? It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

Please reopen this issue when a reproduction is added.
