### ISSUE TITLE
bug: Document breaking change for `isAddress` utility

### ISSUE THREAD

**Issue by mpeyfuss** [wevm/viem#1989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.x.x

### Current Behavior

Currently the docs do not mention that there is breaking behavior for the `isAddress` utility. 

In 1.x.x, the function accepts any string and just tests against the regex. 

In 2.x.x, the function checks the regex but then also has a few other checks after the regex passes. First, it checks if the address is not checksummed at all and if it's all lowercase, returns `true`. Then, if the `strict` option is enabled (which it is by default), it checks strictly for checksum (if not all lowercase). 

Overall, this change in behavior can break existing implementations of `isAddress` and should be documented.

### Expected Behavior

Document the change in `isAddress` functionality

**Comment by mpeyfuss** [comment]
Also, `isAddress` is used by `getAddress` which includes this breaking change from 1.x.x and should really be documented

**Comment by mpeyfuss** [comment]
this also affects abi encoding addresses - this is a pretty major breaking change that should be documented imo.

**Comment by jxom** [comment]
Thanks. This was an oversight. Added in https://github.com/wevm/viem/commit/4f7a6b1c4e81933417c0e4b5503d55cdde162a4e.

**Comment by mpeyfuss** [comment]
Thanks! You're doing great work here :)
