### ISSUE TITLE
bug: Inconsistent results when reading event logs of a contract

### ISSUE THREAD

**Issue by nvnx7** [wevm/viem#2013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.22

### Current Behavior

I'm trying to filter & read event logs given a contract address and event abi, using the `PublicClient.getLogs` method. It turns out that every time I read for a list of logs, I get a different length array of logs. Sometimes shorter length array before, sometimes bigger. 

### Expected Behavior

I would expect the same result every time, given no new events have been emitted. But even if new transactions result in emitted events, it wouldn't be so random.

### Steps To Reproduce

I ran this:

```
import { createPublicClient, http, parseAbiItem } from 'viem';
import { mainnet } from 'viem/chains';

export const publicClient = createPublicClient({
  chain: mainnet,
  transport: http(<rpc-url>),
});

const address = '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48';
const abi = parseAbiItem('event Transfer(address indexed from, address indexed to, uint256 value)');

const main = async () => {
  const filter = await publicClient.createEventFilter({
    address,
    event: abi,
  });

  //@ts-ignore
  const logs = await publicClient.getLogs({
    address,
    event: abi,
  });

  console.log(logs);
  console.log('Length:', logs.length);
};

main();
```

What am I doing wrong?

**Comment by jxom** [comment]
Not sure what RPC Provider you are using (Alchemy, Infura, QuickNode, etc), but they usually limit their block range for log calls (usually past 10,000 blocks). You are probably seeing a variation in length as it is querying from the "latest" block each time. You can specify block ranges with the `fromBlock` and `toBlock` properties on `getLogs` if you want to control this.

**Comment by nvnx7** [comment]
I see, I was using Alchemy. Explicity setting `fromBlock` and `toBlock` resolves the issue here.

But still when I'm reading events of one of my own test contract which has <10 transactions, it gives inconsistent results. 
I compared the same with ethers and it works fine.  Also viem does not yield decoded event args.

My contract: [here](https://mumbai.polygonscan.com/address/0x813a791E43d8EF3a519656a84e5B424555F17d75)

Viem code:
```
export const publicClient = createPublicClient({
  chain: polygonMumbai,
  transport: http('https://polygon-mumbai.g.alchemy.com/v2/demo'),
});

const address = '0x813a791E43d8EF3a519656a84e5B424555F17d75';
const abi = parseAbiItem('event Announcement(uint256 leafIndex, uint256 commitment, bytes memo)');

const main = async () => {
  const filter = await publicClient.createEventFilter({
    address,
    event: abi,
  });

  //@ts-ignore
  const logs = await publicClient.getLogs(filter);

  console.log('Logs:', logs);
  console.log('Length:', logs.length);
};

main();
```

Ethers v6 code:
```
import { JsonRpcProvider, Contract } from 'ethers';
import { parseAbiItem } from 'viem';

const abi = parseAbiItem('event Announcement(uint256 leafIndex, uint256 commitment, bytes memo)');
const address = '0x813a791E43d8EF3a519656a84e5B424555F17d75';
const rpcProvider = new JsonRpcProvider('https://polygon-mumbai.g.alchemy.com/v2/demo');
const contract = new Contract(address, [abi], rpcProvider);

const main = async () => {
  const filter = contract.filters.Announcement();
  const logs = await contract.queryFilter(filter);

  console.log(logs);
  console.log('Length:', logs.length);
};

main();
```

Am I still missing something?

**Comment by nvnx7** [comment]
this is still an issue i believe btw :) @jxom

**Comment by jxom** [comment]
Can you open a new issue with a minimal reproduction in https://new.viem.sh? Will make it a lot easier to investigate! Also, I see you're using `getLogs` when it should be `getFilterLogs`?

**Comment by nvnx7** [comment]
Sure. I will, as soon as I get time. As far as remember, I was getting weird result with `getFilterLogs` (it was probably returning empty array). So I did trial & error with all event related apis and `getLogs` was able to return a non-empty array. So I used that.
