### ISSUE TITLE
bug: `getContractEvents` with args can't get events

### ISSUE THREAD

**Issue by zitup** [wevm/viem#2032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.2

### Current Behavior

`getContractEvents` with args can't get events. Unless I remove the args params, did I miss something?

### Expected Behavior

`getContractEvents` with args can get events.

### Steps To Reproduce

You can try and check console output here, https://codesandbox.io/p/sandbox/viem-662pf2

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://codesandbox.io/p/sandbox/viem-662pf2

**Comment by jxom** [comment]
Hmm, indexed `string` arguments expect the non-hashed string, this is because strings are hashed when emitted – do you know what the non-hashed string is?

**Comment by zitup** [comment]
@jxom Non-hashed string works! Thank you jxom. I will close this issue.

**Comment by jxom** [comment]
Sweet
