### ISSUE TITLE
bug: Logs type in transactionReceipt does not have topics type

### ISSUE THREAD

**Issue by Phantola** [wevm/viem#2034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.4

### Current Behavior

I call `getTransactionReceipt` and parsing topics but, `logs` type not have `topics` property

### Expected Behavior

logs type must have topics property

<img width="371" alt="image" src="https://github.com/wevm/viem/assets/75708535/4b8ce357-bdad-4992-9180-2bada6fbe616">

### Steps To Reproduce

Call a getTransacrion and access like above code.

### Anything else?

I'm sorry for my poor english but I want improve your library. 
If I used viem not well, please let me know how can i found about topics in logs type

**Comment by jxom** [comment]
Works for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8AUOOQQqAZ3jJKNOAF4U6LLkIlySmAAoE4uHBhQMcyLABcjZmH0BKcW2dSZ8uOmRpgYeGoYAO4YwAp6AHQA5mgwACrmchjIMMAyAEpoPn4GRiYMGLIMtvwADAAeEq6S3r7+EUQQUbIA2qUAuhEwEGCksuIA9AMmI6NjAHoA-EA

Feel free to break the above snippet and reopen the issue with a minimal reproducible example.
