### ISSUE TITLE
bug: wallet.sendTransaction type failures

### ISSUE THREAD

**Issue by tunnckoCore** [wevm/viem#2059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.6

### Current Behavior

Seems like some regression again.

Before I didn't encounter that, but now typescript yells when i use `type: 'eip4844'`, when comment it out, it is okay.

I know it is a string, but when i try `type: 3`, it says specifically that you can choose from the multiple string variants.

```ts
import { createPublicClient, createWalletClient, http } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { mainnet } from 'viem/chains';

async function unstuck(privateKey) {
  const privKey = ('0x' + privateKey.replace(/^0x/, '')) as `0x${string}`;
  const account = privateKeyToAccount(privKey);

  const wallet = createWalletClient({
    account,
    chain: mainnet,
    transport: http(process.env.RPC_URL),
  });

  const hash = await wallet.sendTransaction({
    to: account.address,
    value: 0n,
    nonce: 2,
    type: 'eip4844',
  });

  console.log(`Unstuck transaction sent: ${hash}`);
}
```

### Steps To Reproduce

Types fail on Stackblitz too

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-zsgygj?file=index.ts

### Anything else?

![image](https://github.com/wevm/viem/assets/5038030/97c933f5-4190-4f89-9091-eaaa0b5f3061)

![image](https://github.com/wevm/viem/assets/5038030/dd2e9b9c-9c2e-4018-ba97-db351216e286)

**Comment by jxom** [comment]
You are missing parameters:

<img width="212" alt="CleanShot 2024-04-03 at 08 22 11@2x" src="https://github.com/wevm/viem/assets/7336481/c09b331d-e91d-47f3-9b7a-3c0a4d753158">

**Comment by tunnckoCore** [comment]
oh yea yea, just noticed, and blobs.. :+1:

**Comment by jxom** [comment]
probably sending tx with same nonce

**Comment by tunnckoCore** [comment]
> probably sending tx with same nonce

Nope.

Doesn't work.

This particular case is crazy: https://etherscan.io/address/0xab280a38ca897c08047875c53363261c59a6b04a

It's a burner wallet. But here's the thing. I received a request to try to unstuck blob transactions. I very well now i need to send transaction with the same nonce and higher gas.

Thing is, etherscan and any other explorer show just 3 out transactions, 1st confirmed, 2nd replaced, 3rd confirmed. Then i jumped on code and got the real account nonce with `getTransactionCount({ blockTag: 'pending' })` which shows 12.

Then i started, okay the first pending is obviously hidden, but it should be 3, so i upped all fees - `maxFeePerGas`, `maxPriorityFeePerGas`, `maxFeePerBlobGas`. From errors i got the sense what were the given fees.

The sent a transaction without setting a nonce, and is still pending for hour - no message like "waiting on transaction with lower nonce".. okay, then sent a transaction with nonce 10 (i was trying to guess which is stuck).. surprisingly it got accepted; then another. To the point that the first accepted transaction is waiting on the later transaction, which seems to not be waiting about anything.

While i'm writing this etherscan hid all these 3 accepted transactions too.
