### ISSUE TITLE
bug: EIP4844 / eth_estimateGas : does not include the blob versioned hashes

### ISSUE THREAD

**Issue by nand2** [wevm/viem#2075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.9

### Current Behavior

I am using the [sending blob transaction guide](https://viem.sh/docs/guides/blob-transactions) and calling a contract with `sendTransaction()`.
Inspecting the eth_estimageGas call, I see it is only including the blobs, but not the blob versioned hashes.

```
{"method":"eth_estimateGas","params":[{"blobs":["0x006865...."],"data":"0x3aa2651c...,"from":"0xAafA7E1FBE681de12D41Ef9a5d5206A96963390e","maxFeePerBlobGas":"0x6fc23ac00","maxFeePerGas":"0x3b9ad63e","maxPriorityFeePerGas":"0x3b9aca00","nonce":"0x2f","to":"0x804C520d3c084C805E37A35E90057Ac32831F96f","value":"0x1"}]}
```

As a consequence, `blobhash()` returns 0 and break the gas estimation. (E.g. with `require(blobhash(0) != 0, "failed to get blob hash");`)

### Expected Behavior

The versioned hashes should be included in the eth_estimageGas call, so that `blobhash()` return the correct value, and the gas estimation goes as expected.

### Steps To Reproduce

Using the [sending blob transaction guide](https://viem.sh/docs/guides/blob-transactions), call on Sepolia : 

```
import { createWalletClient, http } from 'viem'
import { privateKeyToAccount } from 'viem/accounts'
import { sepolia } from 'viem/chains'
import { default as cKzg } from 'c-kzg'
import { mainnetTrustedSetupPath } from 'viem/node'

const account = privateKeyToAccount('0x...')
const client = createWalletClient({
  account,
  chain: sepolia,
  transport: http()
})
const kzg = setupKzg(cKzg, mainnetTrustedSetupPath)

// Prepare data call
const data = encodeFunctionData({
  abi: [{"inputs":[{"internalType":"bytes32[]","name":"keys","type":"bytes32[]"}],"name":"putBlobs","outputs":[],"stateMutability":"payable","type":"function"}],
  functionName: 'putBlobs',
  args: [['0xa5cc3c03994DB5b0d9A5eEdD10CabaB0813678ACACACACACACACACACACACACAC']]
})

// Prepare blob
const blobs = toBlobs({ data: stringToHex('hello world') }) 
// Send transaction
const hash = await client.sendTransaction({
  blobs,
  kzg,
  maxFeePerBlobGas: parseGwei('30'),
  to: "0x804C520d3c084C805E37A35E90057Ac32831F96f",
  data: data,
})
```

The called contract has `require(blobhash(0) != 0, "failed to get blob hash");` and will revert on eth_estimateGas.

Thanks! :)

**Comment by jxom** [comment]
What RPC provider are you using? The node should derive the versioned hashes from the provided blobs.

**Comment by jxom** [comment]
Dang, looks like some nodes don't. I'll take a look into it.

**Comment by nand2** [comment]
Thanks!
The RPC I used is the default one: https://ethereum-sepolia-rpc.publicnode.com/

**Comment by nand2** [comment]
Thanks a lot for the quick resolution !! 
I confirm it now works :-)
