### ISSUE TITLE
bug: just installing viem breaks my build

### ISSUE THREAD

**Issue by hananbeer** [wevm/viem#2083]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package Version

2.9.9

### Current Behavior

I am working on evm.codes, however after merely installing viem the build fails, ie:

```sh
yarn build # works
yarn install viem
yarn build # fails
```

working on latest main branch commit: https://github.com/smlxl/evm.codes/tree/fcfd9befcc44e0290b06456e4686e8ebe798d6bd

this might be some nextjs/react or whatever voodoo, something similar happened with ethereumjs, but maybe anyone encountered this with viem?

the build error seems to be completely unrelated - even though I didn't even import viem the build now fails on unrelated code:
```sh
./components/KBar/Results.tsx:13:14
Type error: Property 'reduce' does not exist on type '{ results: (string | ActionImpl)[]; rootActionId: string | null | undefined; }'.     

  11 |   const flattened = useMemo(
  12 |     () =>
> 13 |       groups.reduce((acc: any, curr: any) => {
     |              ^
  14 |         acc.push(curr.name)
  15 |         acc.push(...curr.actions)
  16 |         return acc
error Command failed with exit code 1.
```

**Comment by hananbeer** [comment]
viem is dependent on typescript >= 5.0.4 but is "optional"? from `package.json`:

```json
  "peerDependencies": {
    "typescript": ">=5.0.4"
  },
  "peerDependenciesMeta": {
    "typescript": {
      "optional": true
    }
  },
```

I'm not sure if this is necessary but because this is marked as "optional" and I had typescript 4.4 already installed it just continued silently.

**Comment by jxom** [comment]
Yes, it is optional because you don't need to use TypeScript with Viem.
