### ISSUE TITLE
bug: createPublicClient not accept zkSync chain

### ISSUE THREAD

**Issue by savasadar** [wevm/viem#2084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.13

### Current Behavior

When I using `createPublicClient` method, can't create an instance with `zkSync` chain. If I downgrade viem version to `"viem": "^1.3.1"` it accept zkSync as a chain.

### Expected Behavior

It should be accept zkSync as a chain.

**Comment by jxom** [comment]
Works for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjgAvANYBlAJ5Vk7Ljz5CRIAPTIGGYFQDOEyZOQRL8ZJRpwAvCnRZchEuWcwACgRJOBRTcwAuRVUNZFoQuBgoDEtZGCimFgCASni2bPEgA
