### ISSUE TITLE
bug: JS Minification breaks getAction()

### ISSUE THREAD

**Issue by acedward** [wevm/viem#2117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.16

### Current Behavior

When transpiling with `esbuild`, the minified version - might - change the names of functions, but does not remove the `function.prototype.name` so getAction checks for an incorrect function. 

In https://github.com/wevm/viem/issues/1502 the the minifier removes function.prototype.name, so the solution works.

The fix in https://github.com/wevm/viem/pull/1504 only works is function.prototype.name is undefined

So https://github.com/wevm/viem/blob/main/src/utils/getAction.ts
getAction should check if each possible function is defined instead of falling back to name: `action.name || name` 

Something as:
```
  return (params: params): returnType =>
        (client as ClientExtended)[action.name]?.params ||
        (client as ClientExtended)[name]?.params ||
        action(client, params);
``` 

Thanks!

viem is great ❤️ 

### Expected Behavior

The minified version should behave same as the non-minified version.

**Comment by AliBARFIi** [comment]
you can fix it
