### ISSUE TITLE
bug: Incorrect serialization of transactions with `serializeTransaction`

### ISSUE THREAD

**Issue by banky** [wevm/viem#2118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.6

### Current Behavior

The `serializeTransaction` function produces an RLP encoded transaction, which when decoded has an incorrect `from` value. Here is my simplified test code 

```js
const client = createPublicClient({
  chain: mainnet,
  transport: http("https://eth.llamarpc.com"),
});
const tx = await client.getTransaction({
  // Chainlink price update at block 19627159
  hash: "0x1b20ac7d2d43d30685235ed6f6a049affe9b381f10ad29b036cf77e93231ed78",
});

// This doesn't change the serialized tx
// Needed because of ViemError: `gasPrice` is not a valid EIP-1559 Transaction attribute.
tx.gasPrice = 0n;
console.log(tx);

const serialized = serializeTransaction(tx);

console.log(serialized);
```

I set the `tx.gasPrice` to 0 to get around this error: `ViemError: `gasPrice` is not a valid EIP-1559 Transaction attribute`

```js
{
  accessList: [],
  blockHash: "0xd649c7d919c4a5e94ed0050c0bb0e785b71cfa6255d0414d579855e19470875c",
  blockNumber: 19627159n,
  chainId: 1,
  from: "0xdbfea8d5822141c13f92caa06eb94d0f3d67c243",
  gas: 740000n,
  gasPrice: 0n,
  hash: "0x1b20ac7d2d43d30685235ed6f6a049affe9b381f10ad29b036cf77e93231ed78",
  input: "0xc9807539000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000"... 2726 more characters,
  maxFeePerGas: 39999170921n,
  maxPriorityFeePerGas: 3000000000n,
  nonce: 131849,
  r: "0xca3e491aa5a607013be6b88d502c49e4fd1a939a12195a201c63c95de32774ec",
  s: "0x38fd35994dcfe2496b188dcb2d7775af98ad59156fd57e35b675108adcfe4202",
  to: "0x373bce97bec13bfa8a5f07cc578ec2d77f80c589",
  transactionIndex: 1,
  type: "eip1559",
  v: 1n,
  value: 0n,
  yParity: 1,
  typeHex: "0x2"
}
```

From this, we see that the `from` is `0xdbfea8d5822141c13f92caa06eb94d0f3d67c243`. The serialized transaction is

```js
0x02f86f018302030984b2d05e0085095022e969830b4aa094373bce97bec13bfa8a5f07cc578ec2d77f80c5898080c001a0ca3e491aa5a607013be6b88d502c49e4fd1a939a12195a201c63c95de32774eca038fd35994dcfe2496b188dcb2d7775af98ad59156fd57e35b675108adcfe4202
```

Running this through the rlp decoder in `cast`, we get:
```sh
cast decode-transaction 0x02f86f018302030984b2d05e0085095022e969830b4aa094373bce97bec13bfa8a5f07cc578ec2d77f80c5898080c001a0ca3e491aa5a607013be6b88d502c49e4fd1a939a12195a201c63c95de32774eca038fd35994dcfe2496b188dcb2d7775af98ad59156fd57e35b675108adcfe4202

{
  "type": "0x02",
  "from": "0x1548302a535090e72bf00f726eb7964a6975deb5",
  "to": "0x373bce97bec13bfa8a5f07cc578ec2d77f80c589",
  "gas": "0xb4aa0",
  "value": "0x0",
  "nonce": "0x20309",
  "accessList": [],
  "maxPriorityFeePerGas": "0xb2d05e00",
  "maxFeePerGas": "0x95022e969",
  "r": "0xca3e491aa5a607013be6b88d502c49e4fd1a939a12195a201c63c95de32774ec",
  "s": "0x38fd35994dcfe2496b188dcb2d7775af98ad59156fd57e35b675108adcfe4202",
  "v": 1
}
```

The `from` address has been messed up by the `serializeTransaction` function. I thought this might be a bug in `cast` so I used this utility (https://rawtxdecode.in/) which produced the same result:

```js
{
  "chainId": "1",
  "type": "EIP-1559",
  "valid": true,
  "hash": "0xfaa6ebbfb15453b7c99361c71f297ae6f3ce32a0434a6622c067e209d5d80f2e",
  "nonce": "131849",
  "gasLimit": "740000",
  "maxFeePerGas": "39999170921",
  "maxPriorityFeePerGas": "3000000000",
  "from": "0x1548302a535090E72BF00F726EB7964A6975deB5",
  "to": "0x373bce97bec13bfa8a5f07cc578ec2d77f80c589",
  "publicKey": "0x04d6430dff743cde9e33195f3d7eacee2e1fea8b61acd9a7e957d3cab9763ad8c8fa20bb2aa5041097126ff71ed4bf5fec21579b786353a0e596353a8bc3bdf2fa",
  "v": "01",
  "r": "ca3e491aa5a607013be6b88d502c49e4fd1a939a12195a201c63c95de32774ec",
  "s": "38fd35994dcfe2496b188dcb2d7775af98ad59156fd57e35b675108adcfe4202",
  "value": "0"
}
```

Note that if using a transaction that does not perform a contract interaction, the `from` field is correct, for example `0x915b393660ead40a5a97b64acaef18e041639c8262eb65b549fe3b7229b42a4f`. This is how I was able to verify that setting `gasPrice` to `0n` has no effect on the `serializeTransaction` function. 

### Expected Behavior

I expect that when encoding a transaction using `serializeTransaction`, decoding the transaction should produce an object with the same `from` field

### Steps To Reproduce

Running my sample code provided should help for reproducing the issue

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-4fbrro?file=index.ts

**Comment by banky** [comment]
Some additional information, I upgraded to viem v2.9.16 and I'm still seeing the same problem however the `gasPrice is not a valid EIP-1559 Transaction attribute` is no longer an issue. I tried to use the built in `recoverAddress` function and that also seems to be having problems:

```js
const client = createPublicClient({
  chain: mainnet,
  transport: http("https://eth.llamarpc.com"),
});
const tx = await client.getTransaction({
  hash: "0x1b20ac7d2d43d30685235ed6f6a049affe9b381f10ad29b036cf77e93231ed78",
});

console.log(tx);

const serialized = serializeTransaction(tx);
console.log(serialized);

const recoveredAddress = await recoverAddress({
  hash: tx.hash,
  signature: signatureToHex({
    r: tx.r,
    s: tx.s,
    v: tx.v,
    yParity: tx.yParity,
  }),
});

console.log(recoveredAddress);
console.log("Correct from address:", tx.from === recoveredAddress); // This is false
```

The `recoveredAddress` here is `0x788EbA0D624b4791BB86C642A2d84F13792452DA` instead of `0xdbfea8d5822141c13f92caa06eb94d0f3d67c243`

**Comment by jxom** [comment]
When serializing transactions (RLP encoding), the `from` address isn't actually included in the encoding. 

Recovering the `from` address involves using both the **unsigned** transaction and the signature of the transaction. You are probably getting an incorrect `from` value from `cast` and other tools as you are providing a **signed** transaction (one which includes `r`, `s`, `v`/`yParity`) instead of an unsigned one. 

You can recover the address by using [Viem's `recoverTransactionAddress`](https://viem.sh/docs/utilities/recoverTransactionAddress#recovertransactionaddress).

**Comment by banky** [comment]
@jxom my issue is that I serialize the transaction and send it to the chain but it reverts, probably because the address is incorrect. how do i get around that?

**Comment by banky** [comment]
For anyone else that comes across this, I resolved the issue by wrapping the ethers serialize function for viem. This returns a transaction that is correctly decoded and thus gets mined without issues

```js
import ethers from "npm:ethers@5.7.2";
import { Transaction, TransactionSerializedLegacy } from "viem";

/**
 * Serializes a viem transaction using ethers utility
 */
export const serializeTransactionWithEthers = (
  tx: Transaction
):
  | `0x02${string}`
  | `0x01${string}`
  | `0x03${string}`
  | TransactionSerializedLegacy => {
  if (tx.type === "eip1559") {
    return ethers.utils.serializeTransaction(
      {
        type: 2,
        chainId: tx.chainId,
        data: tx.input,
        gasLimit: tx.gas,
        nonce: tx.nonce,
        to: tx.to ?? undefined,
        maxFeePerGas: tx.maxFeePerGas,
        maxPriorityFeePerGas: tx.maxPriorityFeePerGas,
        value: tx.value,
      },
      {
        v: Number(tx.v),
        r: tx.r,
        s: tx.s,
      }
    ) as `0x02${string}`;
  } else {
    // Currently, I only care about EIP-1559 transactions
    throw new Error("Only EIP-1559 transactions are supported");
  }
};
```
