### ISSUE TITLE
bug: publicClient multicall doesnt have `account` field as specified in the docs

### ISSUE THREAD

**Issue by rouzwelt** [wevm/viem#2121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.16

### Current Behavior

as described per viem docs here: https://viem.sh/docs/contract/multicall#account-optional
the `multicall()` should be able to receive an `account` field, however is errors on typescript when such field is provided with:
`Object literal may only specify known properties, and 'account' does not exist in type 'MulticallParameters'`

### Expected Behavior

`account` should be aded to the fn signature

**Comment by jxom** [comment]
Thanks for raising! The docs are incorrect here, and multicall doesn't support sending an `account`. This is because `msg.sender` is the address of the multicall contract instead of the EOA, so the `account` property will become worthless.
