### ISSUE TITLE
bug: `readContract` returns `never` type

### ISSUE THREAD

**Issue by holic** [wevm/viem#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

4.9.16

### Current Behavior

Using `readContract` on a contract ABI with the correct `functionName` and `args` returns a `never` type (in viem 2.9.16) where it used to return a properly typed object (in viem 2.7.12).

<img width="673" alt="image" src="https://github.com/wevm/viem/assets/508855/f42802fa-f537-480f-bb55-8a8fbc5b9642">

<img width="522" alt="image" src="https://github.com/wevm/viem/assets/508855/4323171d-dfd7-45ee-b7aa-d4476a8b31e7">
<img width="575" alt="image" src="https://github.com/wevm/viem/assets/508855/5f477e9b-2eb6-44b8-86bf-43c50738ede7">

### Steps To Reproduce

See repro below (although stackblitz shows the return value as `any` rather than `never` and doesn't seem to be resolving types for `readContract` import)

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-sagfg8?file=index.ts,package.json

**Comment by ezynda3** [comment]
I'm also having issues with `readContract` since `v2.9.6`. All calls that used to succeed now simply fail saying they returned no data. For context I'm using `sveltekit` and `bun` so that could be the issue but I can't upgrade past `v2.9.5`

```js
export const load: PageServerLoad = async ({ params, url, locals }) => {
  const { address } = params
  const network = <string>url.searchParams.get('network') ?? 'mainnet'

  const chain: Chain = chainMap[network]

  const publicClient = createPublicClient({
    chain,
    transport: http(),
  })
  const abi = parseAbi(['function facets() view returns ((address,bytes4[])[])'])

  try {
    // Fetch all facet addresses
    const facetData = <FacetData>await readContract(publicClient, {
      address: getAddress(address),
      abi,
      functionName: 'facets',
    })
  } catch(e) {...}
}

**Comment by jxom** [comment]
Seems to work for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjggMwKlTTwO3XgOGiA9MgZKqAZwnTw0eEnQYAJmQg0oGZOq48+QkSF0uYwR1MpSTQAD1l4ZED4DAJgOABeOABtSThENPS4GABPMDQALgFOPCpXAKp+Wkz0qgwQQoFbNCI1NAAlNCioWyqauGUwPBhjItSsrIR+ibqGov4YWNaASV7qiYnc-PmCHOxjAGYAJj6NrOVsKDqiABU8xv5O4wg8KGQ0VdONtnWNqbPavUHgBrNA5G54MCtL5nLYPXb7Y7JAC6MI2FzQVwwt3uOz2aEORxRaPSP36yN+6ReLGGoxSFP6xkW2AAssNYsASLl5lRHGAMDklmgvmT0v8snD5iUyv5HGjZg8AOZqAAiOVmpAAYiIiGt+oNaWNphkAXAFfNFsQPnrTZKBAiCccSecaJjrndtgIni83tbnaK-sbAXMBKDwZDoZSNnb+A7CcSoxMMVicZ7Y-j46jE+xs+Kzuamur6lqdbZllRmqFnekY3gLgAOasDV0pj0POs0RvZgPpBkTalDEZGs55jYF-hNmNxpvJ924+0Z-1RvtZJlYNBsy2c4Dc7QiADuIt+o5j0vKcqj4+VMDVGuQ2patgAMtRFTAGGiDUOUsbRzMgRaQqfNmNbzumiInCBzaXHOabeq87zAcaPaTEGZoAaGYIQlCwpQVOGZIlmaGztibZ4hBCbIbmaHjrYRYgCWj7lpWk5gR2MBdsRLawe2DZLuSUYDoaP4jjRGETnhbEXEcACsABsM7caRUk0LJCndsuUZrqy7JxFyOTzDoh6-AGJ5gWesqVJe4nXrexb3qWADKJDvJ+VCDnS4yBqa46WisNoAvhEGKTBylwQSPqIQFEwoWKYkhvwYbYZGaFBY6RJEaaJGpvCBEZfxok+eJdF3g+urMWErFpuxnFZUpOXzDVBXeQC45rrAVW8ap8khW6YVdTAanNRMf5ZOO1DRdGKmDT1UHZWRAjsUNGkCf0Qnfl5I3xQ8thYBgnXkQSvWtmB04rRMK7pNpG66duu5eGgxmZKZ-SnqU55Wf0V5qGVk1fp5v7bYBVpIbap15cdPHzPBvqg981FFQlSURrhqXgxRmUAvN6PpZRZyxSarXiZwpYVVWknVXxc31Qt-BNedLX5sTpZPgK1IHQuwXU6FDUCL9rM5OzDO9oJwwecOjNjsVe0c+BR3c31vNy6YwtwJdcDXZuHL6YZB5HpkZlphZFTyjZP2lm54siZL-4JX5foU7lXNcTztMw1Fw2oYjIJYSjstxoRkP9Ydmae3F3tSqTFaVY7jVUy7iu0-TVGrf2YvCZtXtEwlu2LP7i4KydaZnSnF1acyN1bjre6Pfr4cSuZ72WabCXXvzbPDJbGeAxHAj23DsI44SQdK+7Dul1k6vrQDhXZw8JOPgLQto8XEOF1DfMsx3MCe+rmu3dXD1PaSx6vY3Mom9Zrfm4vr7vl3G093PwP+fnzt1a7YFjwPWQE6NwY+3DDhN+uNMZnGxqvDGYdCZMwSgvcq0dyYrwGrVLGNNpqoJigjZ+xQt6C07rHTm6UR603bvgneqsp7p0frPWBDxZZLVmgnIuA1loTxFoyCuWs9I7gMjXY+OYDZnyNk3S+X0zYwH5nfD8UZ-oSy2r3BYQFJqbCHk6dewcvQRQQuPfG2C6HzGRsAwhytA4aKVgHfKqt64GNwUxRBDD44f0Thg3eosaQ0JtmNcSjjurqWYRvOm0kmF6NTquLhB9eG61riZU+qiREXwvOI6+MAADSYJHIGFEPtWR7lu60KlnbZRIDh7mLdto2GKjBFlzWtQmeXiAGGIyVkxQJT1EBM0fwTJDBsluM4eubhd0+FHzrjA7I58PotyVGoTo3Q-p5M8QonBSiQZVNApA4hZSv4VI9tYsZttAHJVRmDDZoctmnLMewrOtj+DwOfNvNpkEOlKzIcvUJNS04ePqUsm52lSAqhliYkuziWEh2gf-dCCVqBRGaM+aRKtkEh3aSCwJABRMoEBYUvioG+BgCL3kNMhTtei-zAWIqIfitBn9Tl9ImPvKuUT+GjMNvPURSSDnzGvLM6A8yraZxsYUh4-c1njIuU8lFnTv5VL-kDTCQCUonKdqAkhairFXKoV8+R1zBXzD+cgAFecgUF2ebTYF8Mn43OhZitAcKcXvkpYPMVKq0zophTa7FuKHW-30Tqwsd4DU5PJcrZ1SqvUnzCVdCJDL7pGWZcI1liTPocoENeRyzJGK6gft87VyaVmvyNe-KlLjwrPB0T-cNBTc1GIVYFVVeMi2gopZcglPzfW3KjixExycJVK27eayt3i4F4LebWp15yHivIIeq9xfKLVtseSGpF4r+2T3LgMyJMa9axKEfEhNkyr7TJgAANWxHgNA3Tem5NnQOxpfdikFs2Sa7ZpbKm0qyNPLVArc2CFPeelpgbFVLsXQIC9rTKFrp0tG4Zsbt0CreomqZ8xIBgE1B4OyDEHKPizZ+-Zg6hX3qDZY4Djwdm6JXa2qtvtjGEbyvW8B6CxV0e9XO3NJV7K-TJr4jixG+1YJY3hw6Hr3w3AgDgCAYAuNsJ7UnYJ-iW1qxnRnPeUbtaMv4LydyAohRxt3VKNlSaBMCCGMYBgIn0MZt5fkwlvkCOAabcu+j1KHhSvBbKxKVGa2OtDc2htgTLFMYrdZ4qJLMMIM7UG3j6IGMoNc4o3OGARP4BMyU4jZq+MfPfXUsYyn11QZ5HyLTVodMNwSfu5JDx0CKmAEyTEaboBoAABIQAgMCbD1sKOGbzWRrzQHx3Q1I+W6pQWEoMGa8CAAgrYWw6BjBhpKw8Ow02CRzfSBAh4UQnB+DgMsOr6Amstdi8s6gQpbD7eBMYAAQjuRQEmu1ON850yLgWOGfL5TlyDqn7oaf5IKIrsGxnwbK7myr1XLg3G01eqzHXb1dcG+s7zDmotOf6y+3ZVyv2dbuUvKddnTGI6TNF+Yk6KHo9wzDsMoGAOjoR8Rynh2bk-qIGeunD7SlPrTCz0nELxxhgAHJAhW6Kh4TIoDKEVAFl0yOBAi7FxLmVii7n84aILmMMucUS9W4T6XMBRfq7AcxjLVIsv0gg5XT7wzvuFZrS9XTxR9OIel6qELv02v8rJ0Sl+3WppjvZ85gb0qfWUflcc6nS6NfQWLQjuXgfOtsYwxxhxd3Ow8fu+l4bO0yW47S0jyPYLwO1M1Sb-pH2eFfYK7963cT5t6YQwe3VN9M2Q8WTmzrwqF19a0ajr3z2W-k48yHnr9nw9rbD-rnvGOYd3M40n7jHegnJ72dz6WhqaP7FS8a+TGq3um8GYfS3FeQ82+r3b2v5X6+SItk37NE+Pd3tWe333KPIrd6G9D2-7ng+POH1rvH0f+OT47Rjgi1Txz0bXn1ny5zc3ixSzn2z3H3d3HCxweVZ2RQexeWHRx3IwUwL232LzN1Lwt3Lwh2eir3hxryB062MBmS6B5Vd3-3fzbxQPx0l1z072f0G3l2WWrQH29yjzHxYLAP834M4N+XTX1Uz1DwpXXzX0XzcytSxXhQf2kzAldWtVtU9XpzbTj1JRXyzw3zQNNX0LTxe0y0LxRB3w3UIM0wP2KzIJPwoJhyoJgDTSwAszoJvQYNs0kLx2Ixc1kMUW4K-34M1yl1-2EJjwAPsXC1xyewEMCViJEK0IkMH2DVgKMIN3T0jkXmQNX0fWULTGJzfSNzMPe3wKGXy2sOIMCxZXIObjr2lyhFIDQHM3EN0JdGvUyLv3zVyLZ3yL9y7w4IiPf0CKYO-1CKEM0NY2d0AKQRiJAIJ1CISKGLakWFgAAHUdwGBlAXcZ8AAWAABhTxoAOMmNjxaDaAcFKBJzmOOMOLn3YhOP8OWWgNZ2kPlmnRwKUwsLywEH3yqKGxqPsLqLPwaJcnPTEIDXcM6NhxFTSl6IMOfXYID3oJ537yCLeLOUgMUXamuO8IeMwVAPiIuF2IJPgKXxzmSN4Lz0fykPz1ey+LwN3zUz+L+xIJ3WP1uXt3qP4CZHqyPUxGMDEQJ1wPpObxv3HEEAFKFO8KIzSMLWMOwLpRUwIOiQESPzsM5NP1zVKBBxqygF20azGyhLfxs3vyYN8P91OJh1Gxa0myW1m1lkWxm0FxHwEA2x1y2x2xgHqzOyKLgA-SLyVNy3NwqJ+3+PVKF3mDQElJoAd34AaxaCIAgANONN73f15PQH5KgEFPZRlLXi4krBtSKB1zPTlLyKwPVgwA0xyBABeDpE4GxCoP+0BP4GjOoFxJhwNIAH0VRzjsBuUehUzxTxJGCejUD6NCzbBiyoBSyaSSMBjkSPDUTP9RjgjmxJyigGyiAmy5yJi6SsgqzHAay6zNzGy0Bmz40oyYyOz39uzHJqC5khyECRyvCUjZSCywgizsgZzzy5y-CsSuC0TVzFINyuAzyyzMT5NhyEo9VITXjqZQKtydy+jqSoLnyoUMUFC7U8UlC0FELwK5zVCsKNCnibltDWiqc3z0iCd8LtzfyULaSPiJhDyqBjy8B6yCLqjLyBA2zYzuS7zGj3gWi4L9QFlr90L8MzSxzmDNdQKSz6KESS0kSrThigLpLv9aLkLFK+CVLaJpioigCbiIC6pNKFLHNWDwDSTX80yViMAOo9irLZLPypywK6L7jiSrLEjWM+y0BLi+LgDbiQLnLTy3K5yHi7iALLVML3VFDzSELgrXKtLzKwCiKYrsK5svLY9KTbdUiPzQgvykKzLCTOk4DrLKzqzaz2KQqtKIyYxeKbzxwBKwSXD-AKKnzyTJLui9D5Sos5Kfy59-y0KOqmkVz1K1zlBTKIKfMFToLhdVibycr8Sgr8qXLCr3LjjPLljl9KKqTGKTKEq1rdzqKyqowWK2KOLQquKcrMQeAoA4zUr1D7UuzyxGdgBHqZFRKOiTTxJWhsLJMQltK44-E31aqwIbroA4zicuzUVwBchXcVxQa0xwa7ruSoaXrsQ3qWqdCMAhMPrhSocbLxJYK9pcb-q5NAbFpZNdLxIohwBhgbUsaKLSaZ8pMKbwDWaFSEbSDIyeKoBbrIaMCYAuzGbcaVQIACRecIAL8YByxxs1jaCr8cNhqBAJrDK8Sqb1qZpybOaLzrq+aIbUbBbhaxDcblhjBJaYAAAtTECAdqtzVW2Y9W4GzWjmjIkwxGh4ZGgW7I8hY21w5AU24wa2ngO2xRB2smo4rWkG7muq-WlGkE-gKGkTCAFkKsnIFo36L1ORdrQmhKKgPAEATOiOl2gGmaiS+YRQUIIulm0u4q3tDWpigE7i1suO723UbHIW5O1O1i6uz6gm2ankAu3uoy12hYiyxhbWt23Oh4Su4ep2qOkuyenvLm9kjUr2-i-9Z6qgV6960O5ZX63FYusKhuzfXWjk9ehOynP21qtscbTgS4FotseGs+te1u-isErsgAeWGE-s4AuxeArCzrEqVqgOyo5NKpCIstKsyscPmqPoYvZtrrJLkIrHgbZonujtXp5pbv5v4u9PQC3srG-pgF-v-tKFsCAa+unvmAPvvhrqXriMexPqwIHoEBcHeFmxtWnwCoXuPudsbo9qjLfsvvwbQC3p3rIcAb3tELsoWo5IwcXupowthOmlHsYfrv4dPrZLgzBuEdzW7PRpIFsF+iVwJGZr7rFPLp4vCC6GwBUcpk0fQeYbLuVv4HQHeGAElPsdYSQfUZk0cZ1u0YB10dwZEfq3EYxtsHSRyFMeMHMfxssdcbCHyFcBtTQeSqJICantYbca6DQE8bSfocjrUZQhXp0aRr0c6wMe3sibHifsVpzpyeSdscKZ6Jkoj0EIzGYJgffxm2Urir-MtNIrbT6bLVsDTV10VFljVymbnxmcwfKc9sqc7NEYiaMcckEp4Ozrd1cZxI2PfG2Mvx4ceL4ZgBOaGqgJ8r8rkY1PCsjvOZYasfbVvj+r2IioQbuf3MEd5tCf0dWcMcxohJJukWkbbWadSe8aBt4Y+eceyaefcfya8fSbrv8ehYrJfuwYvr+fCYBdsBPSZz-R6UUBaPifaP7qefBbseRbHrAIUcipGbyYKchcpqyZpcybRcCauvPuWdvP+ZqaMfxeZ3-VJc1yoaaZsYhepb8dUd8Z6fHARaZalcgdpdheXoxdjt+aqb5Z3sFcJeyRFpBYaZ2bkIlapaKcUeGeB0ZaRfNdOZKc0iCZbKxa1fCfBytHGyIBsDolRVCFB0ofJdcdHO6vLIyclSGfpdzWFQmbF2mZ1xjbmbjZxQWeCYqc1ZWddaFAts1AAcs0SbcyDbzJ6rZbDYXKUc6utGjaTZMXmYTcmcweRDgAwGMBQGiGCEkA2yZBQEoBoESBQBsGwHwGIFIAoBEBoAAApxQDAjAihFBlBVA6BMgPSTAIgigmAWAx2ABKaoNgDd4IDt+AYgCAZAYEXnAuggTEXtjAfcJQSIbtmAAAOmvAuyTOPdPZAHPagE3b3eiGyGUV7f4H2KrEbebf3akH3bgG4N7eSAA6rAbabZbZMBgG-cQ7gBmzwCIHgCSCvZvdQ8wHsEcA9NcDHeQDvfoHFCdOW3mEA6+A5F+GNkcFMc5QfIVsyDssVE8mFXoG4IZB3eCGScsDgGaAbPQ-gAAANn2j3gQzQz3MQigAASBAQ919mTqANgUTqQIAA

Can you fork the playground, break it, then open a new issue? Try double check your TSConfig!

**Comment by holic** [comment]
This is weird, I am still seeing `any` as the return type:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAOQA3YGhD8A3AChQkWIjggMwKlTTwO3XgOGiA9MgZKqAZwnTw0eEnQYAJmQg0oGZOq48+QkSF0uYwR1MpSTQAD1l4ZED4DAJgOABeOABtSThENPS4GABPMDQALgFOPCpXAKp+Wkz0qgwQQoFbNCI1NAAlNCioWyqauGUwPBhjItSsrIR+ibqGov4YWNaASV7qiYnc-PmCHOxjAGYAJj6NrOVsKDqiABU8xv5O4wg8KGQ0VdONtnWNqbPavUHgBrNA5G54MCtL5nLYPXb7Y7JAC6MI2FzQVwwt3uOz2aEORxRaPSP36yN+6ReLGGoxSFP6xkW2AAssNYsASLl5lRHGAMDklmgvmT0v8snD5iUyv5HGjZg8AOZqAAiOVmpAAYiIiGt+oNaWNphkAXAFfNFsQPnrTZKBAiCccSecaJjrndtgIni83tbnaK-sbAXMBKDwZDoZSNnb+A7CcSoxMMVicZ7Y-j46jE+xs+Kzuamur6lqdbZllRmqFnekY3gLgAOasDV0pj0POs0RvZgPpBkTalDEZGs55jYF-hNmNxpvJ924+0Z-1RvtZJlYNBsy2c4Dc7QiADuIt+o5j0vKcqj4+VMDVGuQ2patgAMtRFTAGGiDUOUsbRzMgRaQqfNmNbzumiInCBzaXHOabeq87zAcaPaTEGZoAaGYIQlCwpQVOGZIlmaGztibZ4hBCbIbmaHjrYRYgCWj7lpWk5gR2MBdsRLawe2DZLuSUYDoaP4jjRGETnhbEXEcACsABsM7caRUk0LJCndsuUZrqy7JxFyOTzDoh6-AGJ5gWesqVJe4nXrexb3qWADKJDvJ+VCDnS4yBqa46WisNoAvhEGKTBylwQSPqIQFEwoWKYkhvwYbYZGaFBY6RJEaaJGpvCBEZfxok+eJdF3g+urMWErFpuxnFZUpOXzDVBXeQC45rrAVW8ap8khW6YVdTAanNRMf5ZOO1DRdGKmDT1UHZWRAjsUNGkCf0Qnfl5I3xQ8thYBgnXkQSvWtmB04rRMK7pNpG66duu5eGgxmZKZ-SnqU55Wf0V5qGVk1fp5v7bYBVpIbap15cdPHzPBvqg981FFQlSURrhqXgxRmUAvN6PpZRZyxSarXiZwpYVVWknVXxc31Qt-BNedLX5sTpZPgK1IHQuwXU6FDUCL9rM5OzDO9oJwwecOjNjsVe0c+BR3c31vNy6YwtwJdcDXZuHL6YZB5HpkZlphZFTyjZP2lm54siZL-4JX5foU7lXNcTztMw1Fw2oYjIJYSjstxoRkP9Ydmae3F3tSqTFaVY7jVUy7iu0-TVGrf2YvCZtXtEwlu2LP7i4KydaZnSnF1acyN1bjre6Pfr4cSuZ72WabCXXvzbPDJbGeAxHAj23DsI44SQdK+7Dul1k6vrQDhXZw8JOPgLQto8XEOF1DfMsx3MCe+rmu3dXD1PaSx6vY3Mom9Zrfm4vr7vl3G093PwP+fnzt1a7YFjwPWQE6NwY+3DDhN+uNMZnGxqvDGYdCZMwSgvcq0dyYrwGrVLGNNpqoJigjZ+xQt6C07rHTm6UR603bvgneqsp7p0frPWBDxZZLVmgnIuA1loTxFoyCuWs9I7gMjXY+OYDZnyNk3S+X0zYwH5nfD8UZ-oSy2r3BYQFJqbCHk6dewcvQRQQuPfG2C6HzGRsAwhytA4aKVgHfKqt64GNwUxRBDD44f0Thg3eosaQ0JtmNcSjjurqWYRvOm0kmF6NTquLhB9eG61riZU+qiREXwvOI6+MAADSYJHIGFEPtWR7lu60KlnbZRIDh7mLdto2GKjBFlzWtQmeXiAGGIyVkxQJT1EBM0fwTJDBsluM4eubhd0+FHzrjA7I58PotyVGoTo3Q-p5M8QonBSiQZVNApA4hZSv4VI9tYsZttAHJVRmDDZoctmnLMewrOtj+DwOfNvNpkEOlKzIcvUJNS04ePqUsm52lSAqhliYkuziWEh2gf-dCCVqBRGaM+aRKtkEh3aSCwJABRMoEBYUvioG+BgCL3kNMhTtei-zAWIqIfitBn9Tl9ImPvKuUT+GjMNvPURSSDnzGvLM6A8yraZxsYUh4-c1njIuU8lFnTv5VL-kDTCQCUonKdqAkhairFXKoV8+R1zBXzD+cgAFecgUF2ebTYF8Mn43OhZitAcKcXvkpYPMVKq0zophTa7FuKHW-30Tqwsd4DU5PJcrZ1SqvUnzCVdCJDL7pGWZcI1liTPocoENeRyzJGK6gft87VyaVmvyNe-KlLjwrPB0T-cNBTc1GIVYFVVeMi2gopZcglPzfW3KjixExycJVK27eayt3i4F4LebWp15yHivIIeq9xfKLVtseSGpF4r+2T3LgMyJMa9axKEfEhNkyr7TJgAANWxHgNA3Tem5NnQOxpfdikFs2Sa7ZpbKm0qyNPLVArc2CFPeelpgbFVLsXQIC9rTKFrp0tG4Zsbt0CreomqZ8xIBgE1B4OyDEHKPizZ+-Zg6hX3qDZY4Djwdm6JXa2qtvtjGEbyvW8B6CxV0e9XO3NJV7K-TJr4jixG+1YJY3hw6Hr3w3AgDgCAYAuNsJ7UnYJ-iW1qxnRnPeUbtaMv4LydyAohRxt3VKNlSaBMCCGMYBgIn0MZt5fkwlvkCOAabcu+j1KHhSvBbKxKVGa2OtDc2htgTLFMYrdZ4qJLMMIM7UG3j6IGMoNc4o3OGARP4BMyU4jZq+MfPfXUsYyn11QZ5HyLTVodMNwSfu5JDx0CKmAEyTEaboBoAABIQAgMCbD1sKOGbzWRrzQHx3Q1I+W6pQWEoMGa8CAAgrYWw6BjBhpKw8Ow02CRzfSBAh4UQnB+DgMsOr6Amstdi8s6gQpbD7eBMYAAQjuRQEmu1ON850yLgWOGfL5TlyDqn7oaf5IKIrsGxnwbK7myr1XLg3G01eqzHXb1dcG+s7zDmotOf6y+3ZVyv2dbuUvKddnTGI6TNF+Yk6KHo9wzDsMoGAOjoR8Rynh2bk-qIGeunD7SlPrTCz0nELxxhgAHJAhW6Kh4TIoDKEVAFl0yOBAi7FxLmVii7n84aILmMMucUS9W4T6XMBRfq7AcxjLVIsv0gg5XT7wzvuFZrS9XTxR9OIel6qELv02v8rJ0Sl+3WppjvZ85gb0qfWUflcc6nS6NfQWLQjuXgfOtsYwxxhxd3Ow8fu+l4bO0yW47S0jyPYLwO1M1Sb-pH2eFfYK7963cT5t6YQwe3VN9M2Q8WTmzrwqF19a0ajr3z2W-k48yHnr9nw9rbD-rnvGOYd3M40n7jHegnJ72dz6WhqaP7FS8a+TGq3um8GYfS3FeQ82+r3b2v5X6+SItk37NE+Pd3tWe333KPIrd6G9D2-7ng+POH1rvH0f+OT47Rjgi1Txz0bXn1ny5zc3ixSzn2z3H3d3HCxweVZ2RQexeWHRx3IwUwL232LzN1Lwt3Lwh2eir3hxryB062MBmS6B5Vd3-3fzbxQPx0l1z072f0G3l2WWrQH29yjzHxYLAP834M4N+XTX1Uz1DwpXXzX0XzcytSxXhQf2kzAldWtVtU9XpzbTj1JRXyzw3zQNNX0LTxe0y0LxRB3w3UIM0wP2KzIJPwoJhyoJgDTSwAszoJvQYNs0kLx2Ixc1kMUW4K-34M1yl1-2EJjwAPsXC1xyewEMCViJEK0IkMH2DVgKMIN3T0jkXmQNX0fWULTGJzfSNzMPe3wKGXy2sOIMCxZXIObjr2lyhFIDQHM3EN0JdGvUyLv3zVyLZ3yL9y7w4IiPf0CKYO-1CKEM0NY2d0AKQRiJAIJ1CISKGLakWFgAAHUdwGBlAXcZ8AAWAABhTxoAOMmNjxaDaAcFKBJzmOOMOLn3YhOP8OWWgNZ2kPlmnRwKUwsLywEH3yqKGxqPsLqLPwaJcnPTEIDXcM6NhxFTSl6IMOfXYID3oJ537yCLeLOUgMUXamuO8IeMwVAPiIuF2IJPgKXxzmSN4Lz0fykPz1ey+LwN3zUz+L+xIJ3WP1uXt3qP4CZHqyPUxGMDEQJ1wPpObxv3HEEAFKFO8KIzSMLWMOwLpRUwIOiQESPzsM5NP1zVKBBxqygF20azGyhLfxs3vyYN8P91OJh1Gxa0myW1m1lkWxm0FxHwEA2x1y2x2xgHqzOyKLgA-SLyVNy3NwqJ+3+PVKF3mDQElJoAd34AaxaCIAgANONN73f15PQH5KgEFPZRlLXi4krBtSKB1zPTlLyKwPVgwA0xyBABeDpE4GxCoP+0BP4GjOoFxJhwNIAH0VRzjsBuUehUzxTxJGCejUD6NCzbBiyoBSyaSSMBjkSPDUTP9RjgjmxJyigGyiAmy5yJi6SsgqzHAay6zNzGy0Bmz40oyYyOz39uzHJqC5khyECRyvCUjZSCywgizsgZzzy5y-CsSuC0TVzFINyuAzyyzMT5NhyEo9VITXjqZQKtydy+jqSoLnyoUMUFC7U8UlC0FELwK5zVCsKNCnibltDWiqc3z0iCd8LtzfyULaSPiJhDyqBjy8B6yCLqjLyBA2zYzuS7zGj3gWi4L9QFlr90L8MzSxzmDNdQKSz6KESS0kSrThigLpLv9aLkLFK+CVLaJpioigCbiIC6pNKFLHNWDwDSTX80yViMAOo9irLZLPypywK6L7jiSrLEjWM+y0BLi+LgDbiQLnLTy3K5yHi7iALLVML3VFDzSELgrXKtLzKwCiKYrsK5svLY9KTbdUiPzQgvykKzLCTOk4DrLKzqzaz2KQqtKIyYxeKbzxwBKwSXD-AKKnzyTJLui9D5Sos5Kfy59-y0KOqmkVz1K1zlBTKIKfMFToLhdVibycr8Sgr8qXLCr3LjjPLljl9KKqTGKTKEq1rdzqKyqowWK2KOLQquKcrMQeAoA4zUr1D7UuzyxGdgBHqZFRKOiTTxJWhsLJMQltK44-E31aqwIbroA4zicuzUVwBchXcVxQa0xwa7ruSoaXrsQ3qWqdCMAhMPrhSocbLxJYK9pcb-q5NAbFpZNdLxIohwBhgbUsaKLSaZ8pMKbwDWaFSEbSDIyeKoBbrIaMCYAuzGbcaVQIACRecIAL8YByxxs1jaCr8cNhqBAJrDK8Sqb1qZpybOaLzrq+aIbUbBbhaxDcblhjBJaYAAAtTECAdqtzVW2Y9W4GzWjmjIkwxGh4ZGgW7I8hY21w5AU24wa2ngO2xRB2smo4rWkG7muq-WlGkE-gKGkTCAFkKsnIFo36L1ORdrQmhKKgPAEATOiOl2gGmaiS+YRQUIIulm0u4q3tDWpigE7i1suO723UbHIW5O1O1i6uz6gm2ankAu3uoy12hYiyxhbWt23Oh4Su4ep2qOkuyenvLm9kjUr2-i-9Z6qgV6960O5ZX63FYusKhuzfXWjk9ehOynP21qtscbTgS4FotseGs+te1u-isErsgAeWGE-s4AuxeArCzrEqVqgOyo5NKpCIstKsyscPmqPoYvZtrrJLkIrHgbZonujtXp5pbv5v4u9PQC3srG-pgF-v-tKFsCAa+unvmAPvvhrqXriMexPqwIHoEBcHeFmxtWnwCoXuPudsbo9qjLfsvvwbQC3p3rIcAb3tELsoWo5IwcXupowthOmlHsYfrv4dPrZLgzBuEdzW7PRpIFsF+iVwJGZr7rFPLp4vCC6GwBUcpk0fQeYbLuVv4HQHeGAElPsdYSQfUZk0cZ1u0YB10dwZEfq3EYxtsHSRyFMeMHMfxssdcbCHyFcBtTQeSqJICantYbca6DQE8bSfocjrUZQhXp0aRr0c6wMe3sibHifsVpzpyeSdscKZ6Jkoj0EIzGYJgffxm2Urir-MtNIrbT6bLVsDTV10VFljVymbnxmcwfKc9sqc7NEYiaMcckEp4Ozrd1cZxI2PfG2Mvx4ceL4ZgBOaGqgJ8r8rkY1PCsjvOZYasfbVvj+r2IioQbuf3MEd5tCf0dWcMcxohJJukWkbbWadSe8aBt4Y+eceyaefcfya8fSbrv8ehYrJfuwYvr+fCYBdsBPSZz-R6UUBaPifaP7qefBbseRbHrAIUcipGbyYKchcpqyZpcybRcCauvPuWdvP+ZqaMfxeZ3-VJc1yoaaZsYhepb8dUd8Z6fHARaZalcgdpdheXoxdjt+aqb5Z3sFcJeyRFpBYaZ2bkIlapaKcUeGeB0ZaRfNdOZKc0iCZbKxa1fCfBytHGyIBsDolRVCFB0ofJdcdHO6vLIyclSGfpdzWFQmbF2mZ1xjbmbjZxQWeCYqc1ZWddaFAts1AAcs0SbcyDbzJ6rZbDYXKUc6utGjaTZMXmYTcmcweRDgAwGMBQGiGCEkA2yZBQEoBoESBQBsGwHwGIFIAoBEBoAAApxQDAjAihFBlBVA6BMgPSTAIgigmAWAx2ABKaoNgDd4IDt+AYgCAZAYEXnAuggTEXtjAfcJQSIbtmAAAOmvAuyTOPdPZAHPagE3b3eiGyGUV7f4H2KrEbebf3akH3bgG4N7eSAA6rAbabZbZMBgG-cQ7gBmzwCIHgCSCvZvdQ8wHsEcA9NcDHeQDvfoHFCdOW3mEA6+A5F+GNkcFMc5QfIVsyDssVE8mFXoG4IZB3eCDQ4w6kF0F0DgAAD0AB+SQEIcISwOAZoBs9D+AAAA2faPeBDNDPcxCKAABIEBD3X2NOoA2BFOpAgA

**Comment by tmm** [comment]
[ABIType returns the correct result.](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgQQEbAAoEMpZAUxnygGcAVCDKUYGYAN3zIE8x8SAaOAUQA8ZcAYxhpgAMQCuAO2HAIUuAF84AMygQQcAORZ0MVvi0AoI4Pkl4u4HAC8cANpG4iJ87j62ALm0rps+Vocrs5SePjeWgDmhABK+GZQACaBwXDAUmASMCTejm5uSKEEETC6ADb4AJLJXB7h2qjMRCQAzABMWkpB+c6FYREA1vjMZBJgFYHuBhGNze32ALqdit1uC6vOEFmZ2bmpvXBF9VoWWHSCACJnWJN1M03syxsFh-3a+DIQifiJADIfkRgAAsSLdpg0Hq0Ol19ohXsVtIlmEVgJdrmCvBDmk9UutUqciABZLJWMq0ZgRejAfAAdxSzhWrgQqTuPj8dACzyOEWiMDiCRqqXSOxyDlhfQRWlKqAq1Qxx1m7HaOJ6cO52iGIzGE1q4K0iqhixVPQlxxU1LKfywzC2MHl9zm0MZ+Tx+VtIr2qtNEQJqKupXtWMeMK98OOHzM3z+AOBoN1mP1kOVIZNYYiSJRaID8YVkONzldbgJ+GJ0uAZP0lOpdNWjIWcCwJDgZikFhMdTgcRIEjK8DsomwuAIRFIFCoNDojBYbBIAB4+AIsMJRJIZBypLO6hAVA30FwAES8-nQRL7gB89n3wqyJH3CzPRgA9I+3AA9AD8QA)
