### ISSUE TITLE
viem through proxy

### ISSUE THREAD

**Issue by aarifkhamdi** [wevm/viem#2126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

According to the types of `"@types/node": "~20.12.7"`, you can pass https://github.com/aarifkhamdi/viem/blob/74dbb2e7276af349bc03988eca5ec99b83292e61/src/utils/rpc/http.ts#L18 in https://github.com/aarifkhamdi/viem/blob/74dbb2e7276af349bc03988eca5ec99b83292e61/src/clients/transports/http.ts#L38. In particular, you can pass a dispatcher that will allow you to use a proxy (https://undici.nodejs.org/#/docs/api/ProxyAgent ). But here https://github.com/aarifkhamdi/viem/blob/74dbb2e7276af349bc03988eca5ec99b83292e61/src/utils/rpc/http.ts#L103 dispatcher is not passed as the second argument. That's how it would work `const response = await fetch(request, {dispatcher: options.fetchOptions.dispatcher});`

Also I tried to discuss it here https://github.com/wevm/viem/discussions/1521#discussioncomment-8776162

Actually any solution for using proxies will be great

### Expected Behavior

passing `dispatcher` in fetchOptions works as expected based on types

### Steps To Reproduce

use my repo. Provide RPC and Proxy or just mock it since you just need to check if proxy (or agent) is used

https://github.com/aarifkhamdi/viem_proxy_repro/blob/363dea9a18e7b8fea451b8847182e47580854ec7/src/main.ts#L4

unexpected behavior start here https://github.com/aarifkhamdi/viem/blob/74dbb2e7276af349bc03988eca5ec99b83292e61/src/utils/rpc/http.ts#L103

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/aarifkhamdi/viem_proxy_repro/blob/363dea9a18e7b8fea451b8847182e47580854ec7/src/main.ts#L4

### Anything else?

<img width="1178" alt="image" src="https://github.com/wevm/viem/assets/25562783/6476e40b-a85a-4c39-b827-3c1d20db7f12">

**Comment by jxom** [comment]
Hmm interesting. Maybe `dispatcher` isn't well supported on a `Request` instance. Can take a look.
