### ISSUE TITLE
why is base and baseSepolia not compatible with  Type "Chain" 

### ISSUE THREAD

**Issue by IbrahimIjai** [wevm/viem#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.5

### Current Behavior

I noticed a slight change in baseSepolia which made it in compatible with type of "Chain" in version 2.8.5, but it is perfect in  2.5.0

### Expected Behavior

I expect baseSepolia to be compatible with type "Chain"

I am making an array of Chains 

export const publicChains = [  baseSepolia,
  polygonMumbai,
] as const satisfies Readonly<Chain[]>;

But I get ts error on with baseSepolia. it is not compatible with Chain.

I would love to use 2.8.5

**Comment by jxom** [comment]
Works fine for me: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnAwgCwIbAB2cAvnAGZQQhwDkAbsOiLQFCiSyJwBGeAzugDK6SABtgeUhSo0GTEAHoAxviL82rZREL94qgrrgBeOAG0+gkeMkBdOALjbd8fnhjB+5JvzhR0eAAmOmIo2GqEZrasrEA

Can you please fork that playground and break it? Try double check your tsconfig too.

**Comment by IbrahimIjai** [comment]
Thank you very much, I fixed it. I just updated my ts version from 4.7.5 to latest.

**Comment by jxom** [comment]
Cool!

**Comment by gigamesh** [comment]
I'm getting this too, despite being on the latest version of typescript. 

The crazy thing is I have viem & typescript installed in sibling workspaces of a monorepo, with viem and typescript both on their latest versions, and the type error is only happening in one workspace.
