### ISSUE TITLE
bug: Viem getContract doesn't work with WalletClient that implements custom writeContract function.

### ISSUE THREAD

**Issue by blakecduncan** [wevm/viem#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.16

### Current Behavior

I'm using the ZeroDev SDK and permissionless.js to interact with smart contract wallets. I am encountering an issue in production where the `writeContract` function name is mangled by the bundler, leading to incorrect behavior.

Here’s the code snippet where I configure the `getContract` function:

```
const contract = getContract({
  address: '...',
  abi: testABI,
  client: {
    public: publicClient,
    wallet: kernelClient
  }
})

const hash = await contract.write.mint([kernelClient.account.address])
```

Both ZeroDev and permissionless.js implement the WalletClient interface and include their custom `writeContract` function. In development, everything works as expected because the function names remain unchanged. However, in production, the bundler renames `writeContract` to `writeContract$1`, which causes `getContract` to default to using the base version of `writeContract` rather than the custom implementation provided by ZeroDev/permissionless.

Attached is a screenshot showing that in production, `getContract` attempts to use `writeContract$1` instead of the existing `writeContract` on the client object:

<img width="738" alt="Screenshot 2024-04-12 at 11 35 27" src="https://github.com/wevm/viem/assets/30248643/d61cb71a-3958-410b-985a-697553cebb5b">

Relevant code [here](https://github.com/wevm/viem/blob/74dbb2e7276af349bc03988eca5ec99b83292e61/src/actions/getContract.ts#L729).  The function it relies on is imported in this file, which doesn’t recognize the custom writeContract on the wallet client.

### Expected Behavior

The getContract function doesn't rely on `function.prototype.name` of the imported `writeContract` function.  That way if a wallet client has a custom function it will still use that.

### Steps To Reproduce

1. clone this repo
https://github.com/blakecduncan/bug-repro/blob/main/src/App.tsx

2. update the values in `createAccountNoPreset.ts`

3. `yarn build && yarn preview`
4. Or if you want to see it work, run `yarn dev`

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/blakecduncan/bug-repro

**Comment by jxom** [comment]
I have a feeling that https://github.com/wevm/viem/pull/2132 fixes this. Can you check? I'll reopen if not.

**Comment by blakecduncan** [comment]
> I have a feeling that #2132 fixes this. Can you check? I'll reopen if not.

Thanks, it did fix it! @jxom 

Also, thanks @acedward for the fix!

**Comment by jxom** [comment]
What a legend
