### ISSUE TITLE
bug: `writeContract` does not perform serialization and signing for transactions with local accounts

### ISSUE THREAD

**Issue by insulineru** [wevm/viem#2146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.8

### Current Behavior

When attempting to use the `walletClient.writeContract` function, the HTTP request fails with a status 400. The error message states that the `eth_sendTransaction` method is not found. Below are the details of the request and the error:

```
HTTP request failed. Status: 400
URL: https://base-mainnet.blastapi.io/84650d6f-c7a3-42f6-b093-73c7c47dd28c
Request body: {"method":"eth_sendTransaction","params":[{"data":"0x9dca362f","from":"0x20Ca10A6a0c561953F636e93389324a7cC17d08E","gas":"0x48cd5","to":"0x0A2AF931eFFd34b81ebcc57E3d3c9B1E1dE1C9Ce"}]}
Request Arguments: from: 0x20Ca10A6a0c561953F636e93389324a7cC17d08E to: 0x0A2AF931eFFd34b81ebcc57E3d3c9B1E1dE1C9Ce data: 0x9dca362f gas: 298197
Details: {"code":-32601,"message":"Method not found","data":{"method":"'eth_sendTransaction' does not exist/is not available"}}
```

The account used is of type `local` as verified by logging `walletClient.account.type` before execution.

### Expected Behavior

The expected behavior is that the `walletClient.writeContract` would successfully initiate a transaction without errors. `sendTransaction` perform serialization and signing for transactions with local accounts

### Steps To Reproduce

1. Initialize `walletClient.account` using the Coinbase Waas SDK package. (`@coinbase/waas-sdk-viem`). The source code for the function `toViem` on [NPM](https://www.npmjs.com/package/@coinbase/waas-sdk-viem?activeTab=code)
2. Confirm the account type is `local`.
3. Call `walletClient.writeContract` with the necessary transaction parameters.
4. The error stating that the `eth_sendTransaction` method is not found is received.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

Not applicable. A minimal reproducible example would require a Coinbase API key which is not shareable due to security concerns

### Anything else?

<img width="630" alt="image" src="https://github.com/wevm/viem/assets/20267733/7164e537-b91d-468b-81da-87dbb1360cb3">
<img width="406" alt="image" src="https://github.com/wevm/viem/assets/20267733/5d3e196d-cc0c-4a13-9dfe-539bef9ae40f">

**Comment by jxom** [comment]
I am unable to reproduce this. Our test suite also has several tests for [sending transactions with local accounts](https://github.com/wevm/viem/blob/main/src/actions/wallet/sendTransaction.test.ts#L592). A minimal reproduction will be needed to further debug.
