### ISSUE TITLE
bug: documentation for multicall on http transport is out of date?

### ISSUE THREAD

**Issue by 0x33dm** [wevm/viem#2151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.21

### Current Behavior

After reading the documentation for the [http transport](https://viem.sh/docs/clients/transports/http#batch-json-rpc) I went ahead and got the `batch: true` property on my client.

````ts 
const fantomClient = createPublicClient({
  chain: fantom,
  transport: http(),
  batch: true
})
````

This yields an error:
> Type 'true' has no properties in common with type '{ multicall?: boolean | { batchSize?: number | undefined; wait?: number | undefined; } | undefined; }

In order to satisfy the type error I ended up with a code like this:

````ts
const fantomClient = createPublicClient({
  chain: fantom,
  transport: http(),
  batch: {
    multicall: true
  }
})
````

Which I'm not sure if it's a JSON RPC multicall or a multicall3 contract call as described on the [multicall doc page](https://viem.sh/docs/contract/multicall.html)

### Expected Behavior

Documentation example to be updated and clarify if the multicall will be a JSON RPC MULTICALL or multicall3 contract call.

### Steps To Reproduce

add `{ batch: true }` on VSCODE as per documentation.

**Comment by jxom** [comment]
Here you go: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAEQA3YGhD8A3AChQkWIi4Yavdlx58hIkAHpkDDMCoBnCZMnIIR+J0UxeFETTgBeFOiy5CJcpRoAKBJJwKHoGAFwKSiC0gXAwUIqGsjDhTCy+1pEAdFBgyACqUESGmQAmaNZ4RDCZqWAA2gAMALr0SARYuuFxeGjsAJTRbH1SQA

**Comment by 0x33dm** [comment]
> Here you go: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxhwC+cAZlBCHAEQA3YGhD8A3AChQkWIi4Yavdlx58hIkAHpkDDMCoBnCZMnIIR+J0UxeFETTgBeFOiy5CJcpRoAKBJJwKHoGAFwKSiC0gXAwUIqGsjDhTCy+1pEAdFBgyACqUESGmQAmaNZ4RDCZqWAA2gAMALr0SARYuuFxeGjsAJTRbH1SQA

Thank you

---

My fault, I missed the curly braces likely because of highlighted/faded code on the docs UI and my dark screen.

![image](https://github.com/wevm/viem/assets/166445471/1f029e93-8b90-4753-974d-f3040e1dff7d)
