### ISSUE TITLE
bug: issue with `getContract` `client` typing

### ISSUE THREAD

**Issue by jbrower95** [wevm/viem#2163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.23

### Current Behavior

This very simple code gives a weird error:

```
import abi from './Counter.abi';
import {createPublicClient, getContract, http} from 'viem';
import {mainnet} from 'viem/chains';

const publicClient = createPublicClient({
    chain: mainnet,
    transport: http()
})

const contract = getContract({
    address: '0x00',
    abi,
    client: publicClient
})
```

On the `client: publicClient` assignment, the following type error occurs:

```
Type '{ account: { address: undefined; type: "json-rpc"; }; batch?: { multicall?: boolean | { batchSize?: number; wait?: number; }; }; cacheTime: number; ccipRead?: false | { request?: (parameters: CcipRequestParameters) => Promise<...>; }; ... 55 more ...; extend: <const client extends { ...; } & ExactPartial<...>>(fn: (...' is not assignable to type '{ public?: never; wallet: never; } | { public: never; wallet?: never; }'.ts(2322)
getContract.d.ts(44, 5): The expected type comes from property 'client' which is declared here on type 'GetContractParameters<Transport, Chain, Account, readonly [{ readonly type: "function"; readonly name: "increment"; readonly inputs: readonly []; readonly outputs: readonly []; readonly stateMutability: "nonpayable"; }, { ...; }, { ...; }], { ...; } | { ...; }, "0x00">'
```

Furthermore, changing the publicClient from `mainnet` to `base` gives an _additional_ typing error (on the `chain: mainnet` -> `chain: base` line): 

```
Type '{ blockExplorers: { readonly default: { readonly name: "Basescan"; readonly url: "https://basescan.org"; readonly apiUrl: "https://api.basescan.org/api"; }; }; contracts: { readonly l2OutputOracle: { ...; }; ... 8 more ...; readonly l2ToL1MessagePasser: { ...; }; }; ... 9 more ...; fees?: ChainFees<...>; }' is not assignable to type 'Chain'.
  The types returned by 'serializers.transaction(...)' are incompatible between these types.
    Type '`0x02${string}` | `0x01${string}` | `0x03${string}` | TransactionSerializedLegacy | `0x7e${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.
      Type '`0x02${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.ts(2322)
createClient.d.ts(38, 5): The expected type comes from property 'chain' which is declared here on type '{ batch?: { multicall?: boolean | { batchSize?: number; wait?: number; }; }; cacheTime?: number; ccipRead?: false | { request?: (parameters: CcipRequestParameters) => Promise<`0x${string}`>; }; ... 5 more ...; transport: HttpTransport; }'
```

### Expected Behavior

There should be no type error.

### Steps To Reproduce

Snippet provided reproduces.

(tsconfig.json)
```
{
    "compilerOptions": {
      "module": "NodeNext",
      "moduleResolution": "NodeNext",
      "noImplicitAny": false,
      "removeComments": true,
      "preserveConstEnums": true,
      "sourceMap": true,
      "esModuleInterop": true,
      "allowJs": true,
      "outDir": "dist"
      
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules/**/*"],
}
```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/jbrower95/solabi-loader/tree/main/example-app

### Anything else?

- The mainnet vs. base issue is weird
- I've tried tinkering with my module settings / tsconfig for the `getContract()` call with no success.

**Comment by jxom** [comment]
I have no type issues here: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoAoFcBGANsEgMLGoB2MANHAOaoykTVTpK1wAWMMYAXzgAzKBBBwA5ADdgqEJIDcAKFCRYiEOmCVKTIaPFTZ8gPRJu2ygGcly5UlbX4YAsTIVqcALxwUGLDwiEnI5agAKBGU4P0sdAC44LR09Wmi4GHYbdRhE3n5wgEplAWKHJ3hHNg54X0ZmVkyayPT0ABM2tGtrRMkABgAPPr7JGlb8YESAbQBdMZikT1y4V2CPMJgSwqA

My guess is you need to set `strict: true` in your TSConfig. Otherwise, might be worth comparing the TSConfig in the TypeScript Playground with yours. The TypeScript Playground generally has the best defaults for TSConfig.

**Comment by LI-YONG-QI** [comment]
@jxom I added `"strictNullChecks": true` in `tsconfig.ts` to solved this problem, did viem recommend `tsconfig.ts` practice?
I noticed that the bug is annoying and difficult to solve for user

> I have no type issues here: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbwMZQKYEMaoAoFcBGANsEgMLGoB2MANHAOaoykTVTpK1wAWMMYAXzgAzKBBBwA5ADdgqEJIDcAKFCRYiEOmCVKTIaPFTZ8gPRJu2ygGcly5UlbX4YAsTIVqcALxwUGLDwiEnI5agAKBGU4P0sdAC44LR09Wmi4GHYbdRhE3n5wgEplAWKHJ3hHNg54X0ZmVkyayPT0ABM2tGtrRMkABgAPPr7JGlb8YESAbQBdMZikT1y4V2CPMJgSwqA
> 
> My guess is you need to set `strict: true` in your TSConfig. Otherwise, might be worth comparing the TSConfig in the TypeScript Playground with yours. The TypeScript Playground generally has the best defaults for TSConfig.

**Comment by jbrower95** [comment]
+1, that resolved it for me too.
