### ISSUE TITLE
bug: raw bundle size increased by 0.25MB after update to 2.9.27 in Angular app

### ISSUE THREAD

**Issue by imaksp** [wevm/viem#2188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.27

### Current Behavior

Size before update (using v2.9.26):
<img width="801" alt="before-update" src="https://github.com/wevm/viem/assets/2557058/8a57a6a5-bdca-470b-a8b2-1f5833f56250">

Size after update (v2.9.27):
<img width="805" alt="after-update" src="https://github.com/wevm/viem/assets/2557058/fedd69f7-67f6-4837-b088-8f1ca747edfd">

### Expected Behavior

Bundle size should not increase without any code changes.  & Angular's bundler supports tree shaking.

### Steps To Reproduce

Create an Angular app with with latest wagmi & viem 2.9.26 & 2.9.27, & see the difference in bundle size by changing viem version.

### Anything else?

we are importing only getAddress , isAddress, isAddressEqual, parseUnits, formatUnits , getContract, createClient, fallback, http & some chains from viem, & @wagmi/core might be importing some more.

I will work on reproduction later.

**Comment by jxom** [comment]
Hi. I ran your imports on both `2.9.26` and `2.9.27` with `bun run size` and I get identical outputs.

<img width="266" alt="CleanShot 2024-04-26 at 20 18 42@2x" src="https://github.com/wevm/viem/assets/7336481/a4ad7d7f-7074-48e5-8939-6f217ee95a37">
<img width="261" alt="CleanShot 2024-04-26 at 20 16 46@2x" src="https://github.com/wevm/viem/assets/7336481/36cb2f56-10ac-4e79-a942-b5645bb94dff">

Not sure if this is an issue in Viem. Please provide a minimal reproducible example.

**Comment by imaksp** [comment]
Hi, with new version 2.9.28, difference is now reduced to ~9Kb , so I can ignore it. also that weird minification issue with text like: `�Ethereum Sign` & new lines is fixed. Thanks.
