### ISSUE TITLE
bug: eth_chainId fails on signTransaction

### ISSUE THREAD

**Issue by Ptroger** [wevm/viem#2200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### EDIT
Fixed: issue was with my node version. I was using a deprecated version that didn't had fetch.

### Package Version

2.9.29 or any

### Current Behavior

When trying to sign a transaction with a viem wallet client, it fails. It happens when using the default http transport

### Expected Behavior

signTransaction should not be making an HTTP request to know what chainId is the transaction on (eth_chainId), or it should succeed. It looks like the standard ethereum json-rpc at the url does not have an eth_chainId method.

### Steps To Reproduce

```
import { createWalletClient, hexToBigInt, http } from 'viem';
import { mainnet } from 'viem/chains';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts'

const main = async () => {
  console.log('Hello World');
  
  const privateKey = generatePrivateKey()
  const acc = privateKeyToAccount(privateKey);
  console.log('Private Key:', privateKey);
  console.log('Account:', acc);
  
  const walletClient = createWalletClient({
    chain: mainnet,
    transport: http()
  })
  

  try {
    const tx = await walletClient.signTransaction({
      chain: mainnet,
      account: acc,
      to: '0x70997970c51812dc3a010c7d01b50e0d17dc79c8',
      maxFeePerBlobGas: hexToBigInt('0x0121421'),
      blobs: [],
      value: hexToBigInt('0x01'),
    })
    console.log('tx:', tx);
  } catch (e) {
    console.error('Error:', e);
  }

}

main();
```

➜  viemTest npm run dev

> viemtest@1.0.0 dev
> ts-node src/index.ts

Hello World
Private Key: 0x060d666e4a6dd2e2afa2b6124374fc3dc37b3fc8379c1f5491651fe5d9c4d52d
Account: {
  address: '0x36cc3F2703a1c2434ec85da02f9B0Dc2E2b28688',
  experimental_signAuthMessage: [AsyncFunction: experimental_signAuthMessage],
  signMessage: [AsyncFunction: signMessage],
  signTransaction: [AsyncFunction: signTransaction],
  signTypedData: [AsyncFunction: signTypedData],
  source: 'privateKey',
  type: 'local',
  publicKey: '0x0448fb8fc76d82f6aaba2e9b0a6e7811d538b883785d7362682362d2a711bbc680a98e2b0fc2073a19be06f880b36bbff4aaa5118ecbff94de77dd2e738d61cda2'
}
Error: HttpRequestError: HTTP request failed.

URL: https://cloudflare-eth.com
Request body: {"method":"eth_chainId"}

Details: Request is not defined
Version: viem@2.9.29
    at Object.request (/Users/ptroger/narval/viemTest/node_modules/viem/utils/rpc/http.ts:141:15)
    at async fn (/Users/ptroger/narval/viemTest/node_modules/viem/clients/transports/http.ts:124:19)
    at async request (/Users/ptroger/narval/viemTest/node_modules/viem/clients/transports/http.ts:129:39)
    at async delay.count.count (/Users/ptroger/narval/viemTest/node_modules/viem/utils/buildRequest.ts:104:18)
    at async attemptRetry (/Users/ptroger/narval/viemTest/node_modules/viem/utils/promise/withRetry.ts:44:22) {
  details: 'Request is not defined',
  docsPath: undefined,
  metaMessages: [
    'URL: https://cloudflare-eth.com',
    'Request body: {"method":"eth_chainId"}'
  ],
  shortMessage: 'HTTP request failed.',
  version: 'viem@2.9.29',
  body: { method: 'eth_chainId', params: undefined },
  headers: undefined,
  status: undefined,
  url: 'https://cloudflare-eth.com'
}

It also fails with zerodev first step tutorial, and most of the things that underlyingly use viem.

**Comment by jxom** [comment]
The `eth_chainId` is expected for safety reasons. It seems that you're issue is solved though via the edit?

Closing for now!
