### ISSUE TITLE
bug: typescript complains about optimism chain

### ISSUE THREAD

**Issue by madroneropaulo** [wevm/viem#2201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.29

### Current Behavior

```
import {optimism} from "viem/chains";
import {createWalletClient} from "viem";
...
  const account = mnemonicToAccount("some mnemonic");

  const walletClient = createWalletClient({
    account,
    chain: optimism, //typescript complains here 
    transport: http(OP_PROVIDER_URL),
  })
  
```
 // Typescript won't allow this to compile. It works fine if I just add //@ts-ignore before chain
This is the error
`Type '{ blockExplorers: { readonly default: { readonly name: "Optimism Explorer"; readonly url: "https://optimistic.etherscan.io"; readonly apiUrl: "https://api-optimistic.etherscan.io/api"; }; }; ... 10 more ...; fees?: ChainFees<...>; }' is not assignable to type 'Chain'.`

### Expected Behavior

Typescript should compile. I'm using 5.4.2 same as viem.
mainnet works, only other chains have the issue.

**Comment by tmm** [comment]
Works fine in this [TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQdQwG3zRgGF9g0A7GAGjgAsYYw4BfOAMyghDgHIAbhRB8AUKEixEcEJTQgIlYMgAqEAILJkEAK7U2nbr0HCA9Bi27qAZzETo8JBDAxQwa73Zce-IfNPI9BjAlLaiotqh8BbaevAAvDJyCkqqGpZxABR81jxoSfKKynwAlOGR1vAA7gREpORUCSjoWLi1xGQU1JkIonBwMVa0fShBIQBccM6uIO4gNCMwUBihkjCTjMyZJQusZUA). Please add a minimal reproduction and I can take a look.
