### ISSUE TITLE
docs: No migration guide for hexToSignature

### ISSUE THREAD

**Issue by BerkliumBirb** [wevm/viem#2202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.28

### Current Behavior

`hexToSignature` returns Signature type with `v` being optional `number`

### Expected Behavior

There should be some migration guide how to change `yParity` to `v` because in previous version v was always present.

**Comment by jxom** [comment]
I am not sure a migration guide is needed as `v` should be returned with all legacy signatures. 

If it doesn't then it was probably a bug (you can't convert a `yParity` value to `v` value).

**Comment by BerkliumBirb** [comment]
But the problem is that previously `v` was always present and during migration it became optional and from the just SemVer POV it's a breaking change that should be mentioned in some way.

**Comment by jxom** [comment]
We can add something to the docs.
