### ISSUE TITLE
bug: getLogs log.address not checksummed

### ISSUE THREAD

**Issue by sakulstra** [wevm/viem#2207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.31

### Current Behavior

For some reason log.address is not checksummed when using viem getLogs

### Expected Behavior

it should be i guess?

### Steps To Reproduce

use getLogs with whatever params

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-8rdqgp?file=index.ts

**Comment by jxom** [comment]
What issue is this causing? It doesn't _need_ to be, does it?

**Comment by sakulstra** [comment]
It's just inconsistent as adresses in log.args etc are check-summed, why isn't log.address?

**Comment by jxom** [comment]
No reason really. This will be a breaking change however. Added a note to make this change in next major release: https://github.com/wevm/viem/commit/34a4f06898075a64afc5987df382a01c723ed2f1
