### ISSUE TITLE
bug: Error triggered when using "gasPrice" in writeContract

### ISSUE THREAD

**Issue by cristianopolicarpo** [wevm/viem#2217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.3

### Current Behavior

When attempting to execute a deposit transaction using `writeContract` with a specified "gasPrice" value, an error occurs if the transaction amount exceeds the available balance in the account, even though the balance appears to be sufficient.

### Expected Behavior

The transaction should succeed without error if the account balance is equal to or greater than the transaction amount plus the gas fee.

### Steps To Reproduce

1. Use an account that has a balance less than 0.5 eth, using Sepolia to my Minimal Reproducible Example on StackBlitz.
2. Access: the stackblitz project that I shared and try to execute the deposit function with an amount of any value less than the account balance.
3. This must fail.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/vitejs-vite-am8eg4?file=src%2Fcomponents%2FWriteContract.tsx

### Anything else?

In accounts with much larger amounts this does not happen, as it seems that only the error check the gas incorrectly. So when the account balance is much higher this error does not happen unless the deposit amount is almost the total account balance, then the error will be triggered again.

Comment out line 23 of WriteContract.tsx "gasPrice: estimateFeesPerGas.gasPrice" and this should work normally.

**Comment by jxom** [comment]
`gasPrice` is a property used for legacy transactions. Please use `maxFeePerGas` & `maxPriorityFeePerGas` instead, or even better, don’t pass it at all and let the wallet derive it.

**Comment by cristianopolicarpo** [comment]
> `gasPrice` is a property used for legacy transactions. Please use `maxFeePerGas` & `maxPriorityFeePerGas` instead, or even better, don’t pass it at all and let the wallet derive it.

Hi @jxom,

Thank you for your input. The solution I'm working on aims to support legacy transactions for networks that don't support/enabled EIP-1559. By defining a legacy gasPrice, we can avoid potential issues with wallets that don't handle legacy transactions properly on this networks.

How did you manage to understand why Viem in legacy transactions are demanding a balance beyond what is necessary?

**Comment by jxom** [comment]
I see. Viem doesn't really do any special orchestration here – this error is coming from the RPC when we perform an `eth_call` with the same parameters that we pass to `eth_sendTransaction` (to simulate the call for potential errors). It might be worth trying a different RPC endpoint to see if this error is specific to the RPC. You can also bypass these simulation checks in Wagmi by passing `__mode: 'prepared'` to `writeContract`.

**Comment by cristianopolicarpo** [comment]
I noticed this error in a project on a custom evm network using wagmi core in Vue 3, and I created this Stackblitz Test in Sepolia using wagmi react and the behavior was the same. So I decided to open this issue.


Initially I imagined that the gasPrice might be being multiplied by an incorrect unit, generating a higher balance requirement than necessary, see the log below:

Raw Call Arguments:
  from:      0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319
  to:        0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  value:     0.4 ETH
  data:      0xd0e30db0
  gasPrice:  2.303394322 gwei
 
Contract Call:
  address:   0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  function:  deposit()
  sender:    0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319

Docs: https://viem.sh/docs/contract/simulateContract
Details: err: insufficient funds for gas * price + value: address 0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319 have 479177383256779903 want 515169716100000000 (supplied gas 50000000)
Version: viem@2.9.3
    at getContractError (chunk-J2TTURLG.js?v=ef3951c6:249:10)
    at simulateContract (chunk-J2TTURLG.js?v=ef3951c6:1002:11)
    at async simulateContract2 (chunk-MMBZFRD6.js?v=ef3951c6:2564:31)
    at async writeContract2 (chunk-MMBZFRD6.js?v=ef3951c6:2803:42)

**Comment by jxom** [comment]
What wallet are you using? Seems like it is providing an absurd gas value of `50000000`. You may need to manually pass in a gas limit yourself to the contract write too.

See here: https://stackblitz.com/edit/vitejs-vite-1gjwjb?file=src%2Fcomponents%2FWriteContract.tsx%3AL168

**Comment by cristianopolicarpo** [comment]
In the test above, I used Metamask Browser Extension v11.14.5 on the StackBlitz project that I shared when I created the Issue.

Are you getting different results using the StackBlitz repo I shared? To reproduce the error you need to deposit an amount almost equal to the total balance of your wallet.

Example:
If your Sepolia balance is 4 ETH try setting the amount to 3.9 ETH. So this will add 3.9ETH to the absurd gas and will fail due to insufficient funds.

Here is a log from now, requiring 2.94 ETH:

Raw Call Arguments:
  from:      0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319
  to:        0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  value:     0.3 ETH
  data:      0xd0e30db0
  gasPrice:  46.414248396 gwei
 
Contract Call:
  address:   0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  function:  deposit()
  sender:    0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319

Docs: https://viem.sh/docs/contract/simulateContract
Details: err: insufficient funds for gas * price + value: address 0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319 have 377964554051814903 want 2620712419800000000 (supplied gas 50000000)

**Comment by cristianopolicarpo** [comment]
> What wallet are you using? Seems like it is providing an absurd gas value of `50000000`. You may need to manually pass in a gas limit yourself to the contract write as well.
> 
> See here: https://stackblitz.com/edit/vitejs-vite-1gjwjb?file=src%2Fcomponents%2FWriteContract.tsx%3AL168

I tried passing gas manually as suggested and this returned the error: Out of gas

URL: https://rpc.sepolia.org
Request body: {"method":"eth_call","params":[{"from":"0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319","data":"0xd0e30db0","gas":"0x6dfc","gasPrice":"0xa9da5ab26","to":"0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9","value":"0x429d069189e0000"},"latest"]}
 
Raw Call Arguments:
  from:      0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319
  to:        0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  value:     0.3 ETH
  data:      0xd0e30db0
  gas:       28156
  gasPrice:  45.594553126 gwei
 
Contract Call:
  address:   0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
  function:  deposit()
  sender:    0xD245d9cC1a206b7908e4d82BF93E8f34Ca0Ad319

Docs: https://viem.sh/docs/contract/simulateContract
Details: out of gas
Version: viem@2.9.3
    at getContractError (chunk-C6FZ2PDM.js?v=598225f0:249:10)
    at simulateContract (chunk-C6FZ2PDM.js?v=598225f0:1002:11)
    at async simulateContract2 (chunk-RKK52DQG.js?v=598225f0:2564:31)
    at async writeContract2 (chunk-RKK52DQG.js?v=598225f0:2803:42)
