### ISSUE TITLE
bug: State code overrides do not work with address 1-9

### ISSUE THREAD

**Issue by leovigna** [wevm/viem#2218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.8.6

### Current Behavior

State bytecode overrides do not work with addresses 1-9 (eg. `0x0000000000000000000000000000000000000001`)
I don't think this is an issue with viem but rather there is some implementation that enforces this on common node implementations, especially for testing (ganache, anvil). It can be pretty common to use address 1-9 when writing a simple unit test (eg. some token burn), and it's not documented anywhere that bytecode overrides do not work on these addresses.

### Expected Behavior

These addresses should behave like any other and support state overrides but do not.

### Steps To Reproduce

Write a simple script that makes a contract call with state override using address 1 => fails
Same but with address 10 => succeeds
Wasn't able to create a quick example right now because stackblitz doesn't seem to work with ganache.

### Anything else?

Suggested solution is to simply add a note in the docs page for `readContract` and `simulateContract` under the section detailing that the stateOverrides parameter will not work for overriding address(1) code.

**Comment by leovigna** [comment]
Testing out with other public endpoints address 10 also fails. Not sure what the specific reason is. For now I will use large addresses when writing these unit tests but it's confusing that certain implementations don't let you override these specific addresses.

**Comment by banteg** [comment]
these addresses are not normal addresses, they are [precompiles](https://www.evm.codes/precompiled) and are the only addresses that have native code instead of evm bytecode associated with them. it makes total sense you cannot overwrite their code, because this would break all sorts of things.
