### ISSUE TITLE
bug: getWithdrawalStatus use obsoleted portal Abi (current v3.8.0)

### ISSUE THREAD

**Issue by oleggrib** [wevm/viem#2226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

getWithdrawalStatus(client, parameters)
Thows error: "ContractFunctionExecutionError: Execution reverted for an unknown reason."
when trying to detect status of L2->L1 withdrawal

### Expected Behavior

Must not trow error and return status

### Steps To Reproduce

1. Try to withdraw something from L2 (OptimismSepolia) to L1 (Sepolia)
2. run publicClientL1.getWithdrawalStatus({
      receipt,
      targetChain: chain,
    }

### Anything else?

Issue in this line - https://github.com/wevm/viem/blob/main/src/op-stack/actions/getWithdrawalStatus.ts#L154

getWithdrawalStatus sends 1 parameter, but current portal version require 2 parameters as input

```function checkWithdrawal(bytes32 _withdrawalHash, address _proofSubmitter) public view```

contract code - https://sepolia.etherscan.io/address/0x62749b56f045d30e1971ffa9880d496c701eb386#code

**Comment by tmm** [comment]
Feel free to PR an update!

**Comment by tmm** [comment]
(Could be useful if we grab these artifacts with the [Wagmi CLI](https://wagmi.sh/cli/getting-started) instead of manually updating.)
