### ISSUE TITLE
bug: fallback transport does not fallback when having webSocket transport on the first priority

### ISSUE THREAD

**Issue by kim-hera** [wevm/viem#2233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.9.31

### Current Behavior

The fallback transport does not fallback properly when having webSocket transport on the first priority.
My setup is
- wss rpc
- https rpc
- https rpc

When wss rpc hit rate limit, server down, etc., there is no request to the https rpcs.

### Expected Behavior

It should fallback properly.

### Steps To Reproduce

1. Setup a fallback provider.
2. Config wss transport at the first priority.
3. Config https transport at the second priority and so on.

```
createConfig({
  ...
  transports: {
    [arbitrumChain.id]: fallback([
      webSocket('wss://...'),
      http('https://...'),
      http('https://...'),
    ]),
  },
  ...
});
```

### Anything else?

I'll come back with minimal example and screenshots when I have time.

**Comment by jxom** [comment]
I cannot reproduce this. Can you make this test fail? 

https://github.com/wevm/viem/compare/2233?expand=1#diff-7a5e8fe3b3b331efea724a23f082d4abf649f3164fdaf206049c7f0f2f3822e1R834-R860
