### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'http')

### ISSUE THREAD

**Issue by TechnoGeek01** [wevm/viem#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.10.2

### Current Behavior

Uncaught TypeError: Cannot read properties of undefined (reading 'http') --> Happens when using VITE to build react application with Wagmi version ^1.4.5.
It breaks the application.

### Expected Behavior

Shouldn't break application.

### Steps To Reproduce

1) git clone https://github.com/TechnoGeek01/vite-viem-issue .
2) yarn
3) npm run dev

Check the application. It doesn't work. It breaks.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/TechnoGeek01/vite-viem-issue

**Comment by jxom** [comment]
Wagmi 1.x does not support Viem 2.x. You will need to upgrade Wagmi to 2.x.

**Comment by TechnoGeek01** [comment]
But it worked with my Next Js application. It just doesn't work with VITE react app.
