### ISSUE TITLE
bug: Metamask transaction fails when multiple extensions are detected.

### ISSUE THREAD

**Issue by brijeshagal** [wevm/viem#2266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.10.9

### Current Behavior

When multiple wallet extensions are active like Rainbowkit and Metamask, the transaction reverts with the following error:
```
{
    "e": {
        "metaMessages": [
            "Current Chain ID:  1",
            "Expected Chain ID: 42161 – Arbitrum One",
            " ",
            "Request Arguments:",
            "  from:  0x62414d44AaE1aA532630eDa14Df7F449C475759C\n  to:    0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9\n  data:  0xa9059cbb000000000000000000000000a22042a57270f95169a230b7e766265a67759ebf0000000000000000000000000000000000000000000000000000000000000064"
        ],
        "shortMessage": "The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 42161 – Arbitrum One).",
        "name": "TransactionExecutionError",
        "version": "viem@2.10.9",
        "message": "The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 42161 – Arbitrum One).\n\nCurrent Chain ID:  1\nExpected Chain ID: 42161 – Arbitrum One\n \nRequest Arguments:\n  from:  0x62414d44AaE1aA532630eDa14Df7F449C475759C\n  to:    0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9\n  data:  0xa9059cbb000000000000000000000000a22042a57270f95169a230b7e766265a67759ebf0000000000000000000000000000000000000000000000000000000000000064\n\nVersion: viem@2.10.9",
        "cause": {
            "metaMessages": [
                "Current Chain ID:  1",
                "Expected Chain ID: 42161 – Arbitrum One"
            ],
            "shortMessage": "The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 42161 – Arbitrum One).",
            "name": "ChainMismatchError",
            "version": "viem@2.10.9",
            "message": "The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 42161 – Arbitrum One).\n\nCurrent Chain ID:  1\nExpected Chain ID: 42161 – Arbitrum One\n\nVersion: viem@2.10.9"
        }
    }
}
```

This error occurs when the connected wallet is Metamask goes away when all other wallet extensions are disabled. Also, it doesn't appear when any other wallet is connected. Sometimes, when disconnecting and switching wallets, it again tries to sign using the previously connected wallet.
Checked browsers: Brave, Chrome

### Expected Behavior

Other wallets or presence of other wallets should not hinder the transaction process.

### Steps To Reproduce

A minimalist tutorial site to showcase the bug: https://viem-wallet-error-tutorial.vercel.app/

Steps: 
- Install multiple extension wallets like Rainbow along with Metamask
- Make sure all are active but not connected to the site.
- After connecting with Metamask, click on Submit Txn and you shall get an error in the console as shown in the screenshot below, with Arbitrum as the connected chain.
<img width="1800" alt="image" src="https://github.com/wevm/viem/assets/87767138/4573397a-fcda-4bde-bebe-2e4c744e7d67">
- Now, doing the same with some other walle or metamask connected but all other wallet extensions disabled, works perfectly fine. Hence, metamask seems to be conflicting with other wallets.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://viem-wallet-error-tutorial.vercel.app/

### Anything else?

I'm not sure if it's an issue with rainbowkit. 
Installed Versions:
```
    @rainbow-me/rainbowkit: 2.0.7,
    @tanstack/react-query: 5.32.1,
    viem: 2.10.9,
    wagmi: 2.9.1
```

**Comment by jxom** [comment]
Unsure what's going on as there is no minimal reproducible example (via code), but I suspect that error message is expected if there is a mismatch between your configured chain (ie.  Arbitrum One) and the wallet chain (ie. Mainnet).

**Comment by brijeshagal** [comment]
Please find the codebase here: https://github.com/brijeshagal/error-reproduction-code
