### ISSUE TITLE
bug: Cannot convert undefined to a BigInt in encodeFunctionData when passing tuple

### ISSUE THREAD

**Issue by just2102** [wevm/viem#2268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.10.5

### Current Behavior

```javascript
import { abi as SWAP_ROUTER_ABI } from "@uniswap/v3-periphery/artifacts/contracts/SwapRouter.sol/SwapRouter.json";
```

```javascript
    const tuple = {
      tokenIn: fromToken.address,
      tokenOut: toToken.address,
      fee: poolFee,
      recipient: address,
      amountIn: fromReadableAmount(amountIn, fromToken.decimals),
      amountOutMinimum: 0,
      sqrtPriceLimitX96: 0,
    };
```

```javascript
    const customCalldata = encodeFunctionData({
      abi: SWAP_ROUTER_ABI,
      functionName: "exactInputSingle",
      args: [tuple],
    });
```

![image](https://github.com/wevm/viem/assets/88230737/8261eed7-c0fd-4664-af87-15c8fdb41521)

### Expected Behavior

It should encode function data properly.

### Steps To Reproduce

```javascript
export function fromReadableAmount(amount: number | string, decimals: number) {
  if (typeof amount === "string") {
    return parseUnits(amount, decimals);
  }

  return parseUnits(amount.toString(), decimals);
}
```

amountIn = 0.1
decimals = 18

```javascript
  const tuple = {
      tokenIn: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      tokenOut: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      fee: 3000,
      recipient: address,
      amountIn: fromReadableAmount(amountIn, fromToken.decimals),
      amountOutMinimum: 0,
      sqrtPriceLimitX96: 0,
    };
```

call the encodeFunctionData function:
```javascript
    const customCalldata = encodeFunctionData({
      abi: SWAP_ROUTER_ABI,
      functionName: "exactInputSingle",
      args: [tuple],
    });
```

don't forget to import SWAP_ROUTER_ABI:
```
import { abi as SWAP_ROUTER_ABI } from "@uniswap/v3-periphery/artifacts/contracts/SwapRouter.sol/SwapRouter.json";
```

for that you'd have to install UniswapSDK 
@uniswap/v3-sdk
@uniswap/sdk-core

### Anything else?

Swap Router ABI if you don't want to install uniswap sdk:
[SwapRouter.json](https://github.com/wevm/viem/files/15345172/SwapRouter.json)

Swap Router contract for reference:
https://etherscan.io/address/0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45#writeContract

**Comment by jxom** [comment]
I can't reproduce. Please make sure you supply the correctly typed arguments to the function call. From first glance, I can see you are supplying `number` types instead of `bigint`: 

```diff
const tuple = {
      tokenIn: fromToken.address,
      tokenOut: toToken.address,
      fee: poolFee,
      recipient: address,
      amountIn: fromReadableAmount(amountIn, fromToken.decimals),
-     amountOutMinimum: 0,
+     amountOutMinimum: 0n,
-     sqrtPriceLimitX96: 0,
+     sqrtPriceLimitX96: 0n
  };
```

From the error message, it also seems like it is being supplied an `undefined` value. Perhaps one of your variables are undefined?

**Comment by just2102** [comment]
> I can't reproduce. Please make sure you supply the correctly typed arguments to the function call. From first glance, I can see you are supplying `number` types instead of `bigint`:
> 
> ```diff
> const tuple = {
>       tokenIn: fromToken.address,
>       tokenOut: toToken.address,
>       fee: poolFee,
>       recipient: address,
>       amountIn: fromReadableAmount(amountIn, fromToken.decimals),
> -     amountOutMinimum: 0,
> +     amountOutMinimum: 0n,
> -     sqrtPriceLimitX96: 0,
> +     sqrtPriceLimitX96: 0n
>   };
> ```
> 
> From the error message, it also seems like it is being supplied an `undefined` value. Perhaps one of your variables are undefined?
> 
> I would suggest to use TypeScript as it would catch errors like these in your editor! :)

I've tried supplying bigint, doesn't work.
None of my variables are undefined
![image](https://github.com/wevm/viem/assets/88230737/4c3c9b1e-490b-4160-8d1e-7eed99dd6669)

**Comment by jxom** [comment]
You’re missing `deadline` in your tuple.
