### ISSUE TITLE
bug: isAddress returns wrong value with invalid checksummed addresses if switching between strict: false and strict: true

### ISSUE THREAD

**Issue by johnpm-12** [wevm/viem#2294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.12.0

### Current Behavior

Cache gets messed up.
`const addressWithInvalidChecksum = '0xa5cc3c03994db5b0d9a5eEdD10Cabab0813678Ac';
console.log(viem.isAddress(addressWithInvalidChecksum, { strict: false }));
console.log(viem.isAddress(addressWithInvalidChecksum)); // strict is true by default`
The above code logs true, true.
The first isAddress adds the address to cache with a response of true.
So the second isAddress returns true without validating checksum.

### Expected Behavior

It should log true, false.
isAddress with strict true (the default) and an invalid checksummed address (not lowercase) should always return false.

### Steps To Reproduce

See code above.
You can also see it here: https://stackblitz.com/edit/stackblitz-starters-dvanid?file=index.js
Run `node index.js` then `node index2.js`.
In index.js, cache for that address is set true with the strict: false check, so future strict: true checks incorrectly return the same value.
In index2.js, the same address returns false, as it should, because there is no strict: false check first.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/stackblitz-starters-dvanid?file=index.js

### Anything else?

The same cache bug can occur if you do isAddress with strict true first, and then strict false afterwards, passing in the same invalid checksummed address both times.

Possible solutions include having 2 caches, one for strict false, and one for strict true.
Or make the cache aware of the strict value (key could be `${strict}${address}` for example).
Or just use a cache for strict true, since that's probably the most used (although I do see strict false a lot in internal viem code).

I was gonna skip making an issue and just put a PR, but wasn't sure how ya'll wanted the cache handled. Its a quick fix.

**Comment by tmm** [comment]
Single cache that is aware of whether strict is on works. Feel free to create a PR (so you get credit) and we can tweak if necessary!

**Comment by tmm** [comment]
Single cache that is aware of whether strict is enabled works. Feel free to create a PR (so you get credit) and we can tweak if necessary!
