### ISSUE TITLE
bug: `parseSiweMessage` fails to parse correctly when domain contains port

### ISSUE THREAD

**Issue by hbriese** [wevm/viem#2302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.12.1

### Current Behavior

`parseSiweMessage` fails to parse any prefix fields when the port is included with the domain e.g. `https://example.com:8080`

### Expected Behavior

EIP-4361 (SIWE) states that "domain REQUIRED. The domain that is requesting the signing. Its value MUST be an RFC 3986 authority. The authority includes an OPTIONAL port. If the port is not specified, the default port for the provided scheme is assumed (e.g., 443 for HTTPS)."

### Steps To Reproduce

```ts
import { parseSiweMessage, createSiweMessage } from 'viem/siwe';

const message = createSiweMessage({
  address: '0xA0Cf798816D4b9b9866b5330EEa46a18382f251e',
  chainId: 1,
  domain: 'example.com:8081',
  nonce: 'foobarbaz',
  uri: 'https://example.com/path',
  version: '1',
});

// All message prefix fields fail to parse due to the domain :port
export default JSON.stringify(parseSiweMessage(message)); 
// {"uri":"https://example.com/path","version":"1","nonce":"foobarbaz","chainId":1,"issuedAt":"2024-05-24T04:57:26.865Z"}

```

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-omrjff?file=index.ts

**Comment by cryptofelon** [comment]
I think this should be reopened. See https://github.com/wevm/viem/pull/2303#issuecomment-2134281871
