### ISSUE TITLE
createPublicClient leaves open handles

### ISSUE THREAD

**Issue by cstoneham** [wevm/viem#2320]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

^2.7.22

### Current Behavior

It seems that the RPC connection created by the public client isn't disconnecting properly (or there's no clear way to close the connection). When I run even a simple jest test (see below) I get the error:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TLSWRAP

      17 |     });
      18 |
    > 19 |     const block = await client.getBlock({ blockTag: "latest" });
         |                                ^
      20 |
      21 |     expect(block).toBeDefined();
      22 |   });
```

Leading me to believe that there's some open connection not getting cleaned up.

### Expected Behavior

Tests should exit without this error.

### Steps To Reproduce

1. add jest packages `"jest": "^29.6.2",` and `"ts-jest": "^29.1.1",`
2. Write this simple test:
```
it("simple", async () => {
    const client = createPublicClient({
      chain: mainnet,
      transport: http(
        "<RPC>",
      ),
    });

    const block = await client.getBlock({ blockTag: "latest" });

    expect(block).toBeDefined();
  });
  ```
3. Even through the test passes, see this issue in the console: `Jest has detected the following 1 open handle potentially keeping Jest from exiting:`

**Comment by jxom** [comment]
Works fine for me here: https://stackblitz.com/edit/viem-getting-started?file=package.json,index.test.js. Please break this or provide a minimal reproducible example, and I will reopen this issue.
