### ISSUE TITLE
client extend slow type inference

### ISSUE THREAD

**Issue by devlzcode** [wevm/viem#2322]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.12.5

### Current Behavior

Slow type inference when trying to access properties on the client or in function arguments, most noticeably when using `createTestClient(...).extend(publicActions).extend(walletActions)`. A little slow as well when using the wallet client itself but not as bad. For context, on my M2 Ultra Max it takes 2s or more for code completion to complete, 10s or mor on stackblitz, and often 5s or more on the typescript playground.

### Expected Behavior

Blazing fast type inference.

### Steps To Reproduce

```ts
import { createTestClient, http, publicActions, walletActions } from "viem";
import { foundry } from "viem/chains";

const client = createTestClient({
  chain: foundry,
  mode: "anvil",
  transport: http(),
})
.extend(publicActions)
.extend(walletActions)

// Start using code completion with `client`.
```

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQFTQZxgGEAbYNAOxgBo4ALGGMWsAVwCMzkBBZGYCBXy0A7hhIk0MXv0H44AXzgAzKBBBwA5ADdyITQG4AUKEixEKiKwoATKAE9FKtRp16A9MjoZgQw0aNkOXhkMkp4AF4UdCxcAmIwqgAKBCM4FG9fAC5Lazt7ajS4EAgbNBzNDApdEk1C9JgoKvwzGByGJiSASkKFLqKAOjQAD2xbJLZOYB4+ASF+9KHRyhsksQkpGTn8LuMjd3c4AGUYDHMYezBfAHM4AANQ8ioBu7gB97gqmzhGx1Z8G6fCiOZTWWaCOAiYAwOifKDXfADIxAA

**Comment by tmm** [comment]
What is the exact version you are using (without the caret)?

**Comment by devlzcode** [comment]
> What is the exact version you are using (without the caret)?

2.12.5

If you want a stackblitz repro, here: https://stackblitz.com/edit/viem-getting-started-vuwwkq?file=index.js

**Comment by tmm** [comment]
Need to look into this more, but looks like versions after `2.9.8` are slower than `2.9.7`

- [TS Playground viem@2.9.7](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQFTQZxgGEAbYNAOxgBo4ALGGMWsAVwCMzkBBZGYCBXy0A7hhIk0MXv0H44AXzgAzKBBBwA5ADdyITXAD0huDACeYAgC44AJgB0ATnsB2AFBvkc+MjKV4ALwo6Fi4BMR+VAAUCG5wcCAQACZoNpoYFLokmtRxplAZ+JCwNgxMUQCUuQoVefZoAB7YFElRbJzAPHwCQrXx9U2UrWISUjI9+LWekTBuQA)
- [TS Playground viem@2.9.8](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQFTQZxgGEAbYNAOxgBo4ALGGMWsAVwCMzkBBZGYCBXy0A7hhIk0MXv0H44AXzgAzKBBBwA5ADdyITXAD0huDACeYAgC44AJgB0ATnsAOAFBvkc+MjKV4ALwo6Fi4BMR+VAAUCG5wcCAQACZoNpoYFLokmtRxplAZ+JCwNgxMUQCUuQoVefZoAB7YFElRbJzAPHwCQrXx9U2UrWISUjI9+LWekTBuQA)

**Comment by tmm** [comment]
Seems like the `.extend` API is the slow piece, especially when using `publicActions` (still need to profile).

[TS Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQYQDbBoB2MANCulmgAoCuARgcvoSeQBYwxjlgNMBBZDGAQiAZzgBfOADMoEEHADkAN0IhlcAPTa4MAJ5g04gFxwATADoAnFYAcAKEfIx4+MgLF4AXgqZsFm8ACgRHOH0oDAlIWHNObmCASlJHKSSrNAAPbCIAE2C+RmBkIRE3JJcvEmdXCXgipiCSOD9UAJp+EuaYUPDI6PFYmHiuMGTU9MdG7uqYRyA)

```ts
import { createClient, createPublicClient, http, publicActions } from 'viem' // types: 2.9.8

const client = createClient({
  transport: http(),
}).extend(publicActions)
client // much slower using extends

const publicClient = createPublicClient({
  transport: http(),
})
publicClient // instant autocomplete
```

**Comment by tmm** [comment]
[This line](https://github.com/wevm/viem/blob/main/src/types/contract.ts#L214) looks like the culprit.

**Comment by devlzcode** [comment]
I appreciate the work!
