### ISSUE TITLE
watchBlocks always can only watch latest block but not the pending block even if blockTag is set to be pending

### ISSUE THREAD

**Issue by maxtokka** [wevm/viem#2333]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.1

### Current Behavior

when watchBlocks, no matter if I specify the `blockTag` as `pending` or not, the block watched is always the "latest" current block. 
```
viemClient.watchBlocks({
        blockTag: 'pending',
        onBlock: async (block) => {
            concole.log(block);
        }
    });
```

### Expected Behavior

when specify the `blockTag` as pending, the block should be the pending block

### Steps To Reproduce

```
import { publicClient } from './client'
 
const unwatch = publicClient.watchBlocks( 
  { onBlock: block => console.log(block) }
)
```

**Comment by jxom** [comment]
Works for me.

https://stackblitz.com/edit/viem-getting-started-afbsnx?file=index.ts

**Comment by maxtokka** [comment]
> Works for me.
> 
> https://stackblitz.com/edit/viem-getting-started-afbsnx?file=index.ts

when I test locally, it works indeed for `mainnet` & `http` transport. But when I change to `mainnet` & `webSocket`, it doesn't work any more. I tried on others chains as well, seem issue seems to exist, only `http` transport works but `webSocket` doesn't work
