### ISSUE TITLE
Experimental writeContracts does not use client#sendCalls

### ISSUE THREAD

**Issue by BerkliumBirb** [wevm/viem#2340]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.10.11

### Current Behavior

sendCalls is [used directly](https://github.com/wevm/viem/blob/007405e54e6a1b81e6045ccfbac3622efbc8aa61/src/experimental/eip5792/actions/writeContracts.ts#L121) without checking if client actually implements it.

### Expected Behavior

It's expected to use `getAction(client, sendCalls, 'sendCalls')` instead to enable consumers implement their custom sendCalls.

**Comment by jxom** [comment]
Good idea!
