### ISSUE TITLE
`optimism` does not follow `Chain` type

### ISSUE THREAD

**Issue by 0xc00c** [wevm/viem#2355]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.2

### Current Behavior

Typescript compiler rejects assigning the export `optimism` to a variable of type `Chain` while this works for other exports like `bsc`, `fantom` or `arbitrum`.

### Expected Behavior

The following code should compile without error
```javascript
import { Chain } from 'viem';
import { bsc, optimism } from 'viem/chains';

    const OP: Chain = optimism; // <--- Does not compile
    console.log('Using', OP.name);
    const BSC: Chain = bsc; // <--- Does compile
    console.log('Using', BSC.name);
```

### Steps To Reproduce

Try to assign a chain export to a variable of Chain type. It will work for most/all except for optimism that will trigger the following complier error:
`Type '{ blockExplorers: { readonly default: { readonly name: "Optimism Explorer"; readonly url: "https://optimistic.etherscan.io"; readonly apiUrl: "https://api-optimistic.etherscan.io/api"; }; }; ... 10 more ...; fees?: ChainFees<...>; }' is not assignable to type 'Chain'.
  The types returned by 'serializers.transaction(...)' are incompatible between these types.
    Type '`0x02${string}` | `0x01${string}` | `0x03${string}` | TransactionSerializedLegacy | `0x7e${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.
      Type '`0x02${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.`

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play/?target=99&moduleResolution=99&module=199&jsx=0#code/JYWwDg9gTgLgBAbzgYQBYENgDs4F84BmUEIcA5AG7ACmIZA3AFCiSyJwBGAzgMYA0cCGBihgXUviIlyVWgHoeGbFwaNGPCFi7wA8gAUAXCiU4AvIOGjxTDVogAbagDp7EAOYAKMgFUu2N2QC+k5Y6CDUAJQ2mtpwAEIAyshGaJhmnLzRdo4u7l6+-oHxSSFhkfRAA

**Comment by jxom** [comment]
The playground you linked doesn't emit any errors, and I am also unable to reproduce this issue in my [minimal compilation example here](https://stackblitz.com/edit/viem-getting-started-cd4yuh?file=index.ts,package.json,tsconfig.json). Can you please re-open this PR with a minimal reproducible example which emits an error?

**Comment by 0xc00c** [comment]
The error appears with the following `tsconfig.json`
```
{
  "compilerOptions": {
    "outDir": "./built",
    "allowJs": true,
    "target": "es2020",
    "skipLibCheck": true,
    "module": "NodeNext",
    "moduleResolution": "nodenext",
  },
  "include": ["./src/**/*"]
}
```
I thought Playground would share the config as I set it up, sorry about that.
From the default settings, just change Module to NodeNext as in the screenshot.

![image](https://github.com/wevm/viem/assets/97407868/17658f12-82ba-4b58-b384-b25901208ce1)
