### ISSUE TITLE
`optimism` does not follow `Chain` type

### ISSUE THREAD

**Issue by 0xc00c** [wevm/viem#2358]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.2

### Current Behavior

Typescript compiler rejects assigning the export `optimism` to a variable of type `Chain` while this works for other exports like `bsc`, `fantom` or `arbitrum`.

### Expected Behavior

The following code should compile without error
```javascript
import { Chain } from 'viem';
import { bsc, optimism } from 'viem/chains';

    const OP: Chain = optimism; // <--- Does not compile
    console.log('Using', OP.name);
    const BSC: Chain = bsc; // <--- Does compile
    console.log('Using', BSC.name);
```

### Steps To Reproduce

Set `tsconfig.json` as:
```
{
  "compilerOptions": {
    "outDir": "./built",
    "allowJs": true,
    "target": "es2020",
    "skipLibCheck": true,
    "module": "NodeNext",
    "moduleResolution": "nodenext",
  },
  "include": ["./src/**/*"]
}
```
In Playgroung, just change Module to NodeNext.
![image](https://github.com/wevm/viem/assets/97407868/17658f12-82ba-4b58-b384-b25901208ce1)

Try to assign a chain export to a variable of Chain type. It will work for most/all except for optimism that will trigger the following complier error:
```
Type '{ blockExplorers: { readonly default: { readonly name: "Optimism Explorer"; readonly url: "https://optimistic.etherscan.io"; readonly apiUrl: "https://api-optimistic.etherscan.io/api"; }; }; ... 10 more ...; fees?: ChainFees<...>; }' is not assignable to type 'Chain'.
  The types returned by 'serializers.transaction(...)' are incompatible between these types.
    Type '`0x02${string}` | `0x01${string}` | `0x03${string}` | TransactionSerializedLegacy | `0x7e${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.
      Type '`0x02${string}`' is not assignable to type 'TransactionSerialized<_transactionType, (_transactionType extends "eip1559" ? `0x02${string}` : never) | (_transactionType extends "eip2930" ? `0x01${string}` : never) | (_transactionType extends "eip4844" ? `0x03${string}` : never) | (_transactionType extends "legacy" ? TransactionSerializedLegacy : never)>'.
```

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play/?target=99&moduleResolution=99&module=199&jsx=0#code/JYWwDg9gTgLgBAbzgYQBYENgDs4F84BmUEIcA5AG7ACmIZA3AFCiSyJwBGAzgMYA0cCGBihgXUviIlyVWgHoeGbFwaNGPCFi7wA8gAUAXCiU4AvIOGjxTDVogAbagDp7EAOYAKMgFUu2N2QC+k5Y6CDUAJQ2mtpwAEIAyshGaJhmnLzRdo4u7l6+-oHxSSFhkfRAA

### Anything else?

Original issue: https://github.com/wevm/viem/issues/2355

In the original issue I did not specify the `tsconfig.json` content.
With the default settings, it compiles, as you said, but then the JS code fails. That is why I use Module NodeNext.
```
[ERR]: "Executed JavaScript Failed:" 
[ERR]: Check dependency list! Synchronous require cannot resolve module 'viem/chains'. This is the first mention of this module!
```

**Comment by jxom** [comment]
Do you still get the error when `strict` mode is enabled (ie. `compilerOptions.strict`)?

**Comment by 0xc00c** [comment]
> Do you still get the error when `strict` mode is enabled (ie. `compilerOptions.strict`)?

It works on VS Code (thanks for the tip!) but not in Playground (it is enabled by default on Playground).

**Comment by jxom** [comment]
Hmm yeah. I can’t seem to replicate the TSConfig from the playground in my local environment. Will keep digging.

**Comment by jxom** [comment]
Closing for now as I can’t reproduce in non-playground environment. Feel free to reopen with a repro in a repository or alike!
