### ISSUE TITLE
`estimateGas` fails when it contains `stateOverride`

### ISSUE THREAD

**Issue by shirotech** [wevm/viem#2363]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.3

### Current Behavior

It throws error:

```
Docs: https://viem.sh/docs/contract/estimateContractGas
Details: trailing characters at line 1 column 1132
Version: viem@2.13.3
    at getContractError (/Users/<redacted>/Projects/<redacted>/node_modules/viem/utils/errors/getContractError.ts:72:10)
    at estimateContractGas (/Users/<redacted>/Projects/<redacted>/node_modules/viem/actions/public/estimateContractGas.ts:125:27)
    at async main (/Users/<redacted>/Projects/<redacted>/scripts/utils.ts:36:15) {
  details: 'trailing characters at line 1 column 1132',
  docsPath: '/docs/contract/estimateContractGas',
```

### Expected Behavior

expected to work, `simulate` is okay, but `estimateGas` throws error.

### Steps To Reproduce

https://stackblitz.com/edit/viem-getting-started-1h6i9t?file=index.ts

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-1h6i9t?file=index.ts

### Anything else?

Related: #2275
On a sidenote, why can't simulate also return the gas used?

**Comment by jxom** [comment]
I was able to successfully run this using a different RPC provider other than the default public one (QuickNode to be specific), so perhaps RPC provider you are using doesn't fully support state overrides in `eth_estimateGas`.

> why can't simulate also return the gas used?
Viem's Actions are designed to be atomic/pure/1-1 with JSON-RPC methods.
