### ISSUE TITLE
Add ZetaChain to wagmi/chains

### ISSUE THREAD

**Issue by Kali-Decoder** [wevm/viem#2364]
### What is the issue?

Adding Zetachain to wagmi with some updation attributes .

### Where did you find it?

Issue raised on zeta chain repo to list zetachain on wagmi/chains .
https://github.com/zeta-chain/toolkit/issues/92

**Comment by tmm** [comment]
The chains in the Wagmi docs don't always reflect the latest Viem version. I added a note for folks https://wagmi.sh/react/api/chains#available-chains
