### ISSUE TITLE
The provided tip (maxPriorityFeePerGas = 1.5gwei) cannot be higher than the fee cap (maxFeePerGas = 13.31 gwei)

### ISSUE THREAD

**Issue by 0xlynett** [wevm/viem#2377]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

(well, #2087, but it's closed)

### Viem Version

2.13.7 (through wagmi)

### Current Behavior

(`maxPriorityFeePerGas` = 0.1 gwei, `maxFeePerGas` = 15.15 gwei).

The provided tip is higher than the fee cap, but this error appears when I try to do `sendTransaction`.
```
TransactionExecutionError: The provided tip (`maxPriorityFeePerGas` = 0.0x5f5e1 gwei) cannot be higher than the fee cap (`maxFeePerGas` = 0x.38719f23a gwei).

Request Arguments:
  chain:                 undefined (id: 0x1)
  from:                  0xC2f3F2c8084d6bc40887B0B867353d280e3D742D
  to:                    0xc2f3f2c8084d6bc40887b0b867353d280e3d742d
  maxFeePerGas:          0x.38719f23a gwei
  maxPriorityFeePerGas:  0.0x5f5e1 gwei
  nonce:                 0x9
```

### Expected Behavior

The error does not appear and the transaction sign menu shows up on my wallet.

### Steps To Reproduce

My transaction object:
```
{"from":"0xc2f3f2c8084d6bc40887b0b867353d280e3d742d","to":"0xc2f3f2c8084d6bc40887b0b867353d280e3d742d","maxFeePerGas":"0x51efa5fba","maxPriorityFeePerGas":"0x5f5e100","gas":"0x5208","input":"0x","nonce":"0x9","chainId":"0x1","type":"0x2"}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-aw8oue

### Anything else?

Using `wagmi` hooks in React. The transaction data comes directly from an `eth_sendTransaction` RPC call from Foundry's `cask`. It happens on many networks.

**Comment by jxom** [comment]
`maxFeePerGas` and `maxPriorityFeePerGas` need to be of type `bigint`.
