### ISSUE TITLE
minor: wrong behavior comment in parseUnits

### ISSUE THREAD

**Issue by janndriessen** [wevm/viem#2378]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The comment at line https://github.com/wevm/viem/blob/main/src/utils/unit/parseUnits.ts#L22 says: `// trim leading zeros.`

but it should actually be `// trim trailing zeros.`

### Where did you find it?

https://github.com/wevm/viem/blob/main/src/utils/unit/parseUnits.ts#L22

**Comment by jxom** [comment]
ty
