### ISSUE TITLE
Viem serializes transaction wrong with zeroes

### ISSUE THREAD

**Issue by KillariDev** [wevm/viem#2394]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.8

### Current Behavior

```js
const viem = require("viem")
console.log(viem.serializeTransaction(
	{
		chainId: 17000,
		gas: BigInt("0x52080"),
		maxFeePerGas: BigInt("0x0"),
		maxPriorityFeePerGas: BigInt("0x0"),
		nonce: 0,
		to: "0xc000000000000000000000000000000000000000",
		value: BigInt("0x0"),
	},
	{
		r: "0x0",
		s: "0x0",
		yParity: 0,
	},
))
```
this prints out: `0x02e58242688080808305208094c0000000000000000000000000000000000000008080c080**0000**`
which is wrong. It should be `0x02e58242688080808305208094c0000000000000000000000000000000000000008080c080**8080**`
 (notice the last 4 characters)
 
The signature parameters (v,r,s) are all zeroes. Zeroes is a special case and should be serialized as 0x80 (https://ethereum.stackexchange.com/questions/7411/rlp-encoding-of-0)
 

### Expected Behavior

the script should print: `0x02e58242688080808305208094c0000000000000000000000000000000000000008080c0808080`

### Steps To Reproduce

```js
const viem = require("viem")
console.log(viem.serializeTransaction(
	{
		chainId: 17000,
		gas: BigInt("0x52080"),
		maxFeePerGas: BigInt("0x0"),
		maxPriorityFeePerGas: BigInt("0x0"),
		nonce: 0,
		to: "0xc000000000000000000000000000000000000000",
		value: BigInt("0x0"),
	},
	{
		r: "0x0",
		s: "0x0",
		yParity: 0,
	},
))
```

**Comment by jxom** [comment]
Good spot. Will fix tomorrow.
