### ISSUE TITLE
`watchContractEvent` doing requests with invalid block range

### ISSUE THREAD

**Issue by Lopol2010** [wevm/viem#2470]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.16.1

### Current Behavior

When listening events via `watchContractEvent`, console is filled with error: 
RPC Request failed:  
code: -32000, message: invalid block range params 

`Request body: "method":"eth_getLogs" ..."fromBlock":"0x2649c99" ... "toBlock":"0x2649c97"`  

As you can see `fromBlock` is greater than `toBlock`.
I assume bug appears in these lines: https://github.com/wevm/viem/blob/f7afaa2e0c687e45fe85c8de51cbd8a12f2318a4/src/actions/public/watchContractEvent.ts#L242-L243

### Expected Behavior

The case with invalid block range should be handled by `watchContractEvent` function, so that it won't make request with invalid block range.

### Steps To Reproduce

Listen for BSC mainnet contract events via RPC node `https://rpc.ankr.com/bsc`
And these arguments:
```
    let unwatch = client.watchContractEvent({
        abi: ...,
        address: ...,
        pollingInterval: 4000,
        eventName: ...,
        onError: err => { console.log("[Listener] error:", err); },
        onLogs: logs => {
        }
    })
  ```

**Comment by jxom** [comment]
Hmm, must be some load balancing issue on the RPC Provider side. Will add a guard to fix.
