### ISSUE TITLE
dist bundle size

### ISSUE THREAD

**Issue by pkieltyka** [wevm/viem#2483]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

docs state viem is ~31kb minified + gzipped

<img width="650" alt="image" src="https://github.com/wevm/viem/assets/18831/d25b4017-c77a-4a50-999d-e7e1960e7d11">

bundlephobia says its ~74kb minified + gzipped

https://bundlephobia.com/package/viem@2.17.2

<img width="1466" alt="image" src="https://github.com/wevm/viem/assets/18831/cfe93745-ff77-401d-aeec-051d8bb5981c">

### Where did you find it?

* https://viem.sh/docs/introduction
* https://bundlephobia.com/package/viem@2.17.2

**Comment by jxom** [comment]
Docs are correct. The comparison here is the size to import `createPublicClient` and `http` from Viem. 

Bundlephobia is not a great source of truth for bundle size of ESM packages as it doesn't account for [tree-shaking](https://developer.mozilla.org/en-US/docs/Glossary/Tree_shaking), and shows the bundle size to import every single module from Viem into your application.

**Comment by jxom** [comment]
Can configure the `size-limit` imports [here](https://github.com/wevm/viem/blob/main/package.json#L123)then run `pnpm size`.
