### ISSUE TITLE
Public action `verifyHash` does not work with zksync public client

### ISSUE THREAD

**Issue by tahos81** [wevm/viem#2484]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.16.5

### Current Behavior

When doing anything that uses `verifyHash` internally (like `verifySiweMessage`) if the public client in context is a zksync client verification fails. Reason for that is `verifyHash` uses erc-6492 for signature verification and has a constant called `universalSignatureValidatorByteCode` but regular bytecodes does not work on zksync so verification fails even when the signature is valid. This is not a problem for eoa's (you can just verify with an arbitrary public client) but it is breaking for smart contract accounts

### Expected Behavior

Either a different constant bytecode should be used when the chain in context is zksync or 6492 flow should not be used and verification flow should revert to old flow (1271 + ecrecover).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-shqa8r?file=index.ts

**Comment by jxom** [comment]
Unfortunately, zkSync handles contract deployments a bit differently to Ethereum. :\ 

Can see what I can do.

**Comment by jxom** [comment]
Added a fallback for this scenario here: https://github.com/wevm/viem/commit/ec3b0e08f0a379249224e65092277191f1a8502b.
