### ISSUE TITLE
Issue with passing wallet client to reservoir sdk

### ISSUE THREAD

**Issue by ali9821** [wevm/viem#2494]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.12.1

### Current Behavior

Hey team
I'm using reservoir kit sdk for my nft marketplace
I'm creating a wallet client by createWalletClient and passing it to reservoir for sending my transactions to the wallet provider
I get httpRequestError and RpcError all the time

### Expected Behavior

Expected my transactions get sent to the wallet and sign them in the wallet app

### Steps To Reproduce

These are some snippets that I've implemented in the project:
import { ListModal } from '@reservoir0x/reservoir-kit-ui'
import { useAddress } from '@thirdweb-dev/react'
import { useHistory } from 'react-router-dom'
import { createWalletClient, http } from 'viem'
import { polygon } from 'viem/chains'

export default function ListItem({
  tokenId,
  mutate,
  width,
  text,
}: {
  text?: string
  width?: string | number
  tokenId: string
  mutate?: () => void
}) {
  const history = useHistory()
  const address = useAddress()

  const client = createWalletClient({
    account: address as 0x${string},
    chain : polygon,
    transport: http(),
  })

  return (
    <ListModal
      normalizeRoyalties
      trigger={
        <button
          style={{
            width: width || '',
            color: 'white',
            fontSize: 19,
            fontWeight: 500,
            padding: '10px 20px 10px 20px',
            borderBottom: '4px solid #0D842E',
            borderRadius: 10,
            background: 'linear-gradient(90deg, #1E9F5F 0%, #0ED070 78.35%)',
          }}
        >
          {text || 'Sell'}
        </button>
      }
      walletClient={client}
      collectionId="0x9c09596d3d3691ea971f0b40b8cad44186868267"
      tokenId={tokenId}
      chainId={137}
      orderKind="seaport"
      oracleEnabled={true}
      currencies={[
        {
          contract: '0x4455eF8B4B4A007a93DaA12DE63a47EEAC700D9D',
          symbol: 'KNIGHT',
        },
      ]}
      onGoToToken={() => {
        history.push(/explore?id=${tokenId})
      }}
      onListingComplete={(data) => {
        console.log('Listing Complete', data)
        if (mutate) mutate()
      }}
      onListingError={(error, data) => {
        console.error('Transaction Error', error, data)
      }}
    />
  )
}

And the errors I experience by testing alchemy and infura rpc urls and the publicClient :

Transaction Error HttpRequestError
    at Object.request ( )
    at async fn (t)
    at async request (h)
    at async delay.count.count (e)
    at async attemptRetry (s)
  {tokenId: '25529', collectionId: '0x9c09596d3d3691ea971f0b40b8cad44186868267', listings: Array(1)}
 collectionId
 : "0x9c09596d3d3691ea971f0b40b8cad44186868267"
 listings: [{…}]
 tokenId:"25529"

Transaction Error MethodNotFoundRpcError
    at delay.count.count (buildRequest.js:35:1)
    at async attemptRetry (withRetry.js:24:1)Caused by: RpcRequestError
    at request (http.js:70:1)
    at async delay.count.count (buildRequest.js:23:1)
    at async attemptRetry (withRetry.js:24:1) {tokenId: '25529', collecti

### Link to Minimal Reproducible Example

marketplace-v2-umber.vercel.app/profile-v2

### Anything else?

I need to add this here that I'm using thirdweb as our main wallet connection sdk
And in the case of using reservoir I have to create a viem wallet client and pass it to reservoir component to accomplish my transaction

**Comment by tmm** [comment]
Better to raise this with Reservoir.
