### ISSUE TITLE
Incorrect inferred type on `decodeLogEvent`

### ISSUE THREAD

**Issue by jagnani73** [wevm/viem#2501]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

^2.17.4

### Current Behavior

When calling the function `decodeEventLog`
```ts
const decoded = decodeEventLog({
    abi: ABI,
    topics: raw_log_topics as [],
    data: raw_log_data as `0x${string}`,
    eventName: "ApprovalForAll",
});
```

the return as typecasted as
```ts
const decoded: {
    eventName: "ApprovalForAll";
    args: readonly unknown[] | undefined;
}
```

But the return (`decoded`) when logged gives
```ts
{
    eventName: 'ApprovalForAll',
    args: {
    owner: '0xfC43f5F9dd45258b3AFf31Bdbe6561D97e8B71de',
    operator: '0x1E0049783F008A0085193E00003D00cd54003c71',
    approved: true
    }
}
```

There is a mismatch between the types of `decoded.args` - the function shows a return on an array while the actual return is an object

### Expected Behavior

The return should be typed as
```ts
{
    eventName: string,
    args: {
    owner: string
    operator: string,
    approved: boolean,
    }
}
```

### Steps To Reproduce

```ts
const ABI = [
    {
        "anonymous": false,
        "inputs": [
            {
                "indexed": true,
                "internalType": "address",
                "name": "owner",
                "type": "address"
            },
            {
                "indexed": true,
                "internalType": "address",
                "name": "operator",
                "type": "address"
            },
            {
                "indexed": false,
                "internalType": "bool",
                "name": "approved",
                "type": "bool"
            }
        ],
        "name": "ApprovalForAll",
        "type": "event"
    }
]

const raw_log_data = "0x0000000000000000000000000000000000000000000000000000000000000001'

const raw_log_topics = [
  '0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
  '0x000000000000000000000000fc43f5f9dd45258b3aff31bdbe6561d97e8b71de',
  '0x0000000000000000000000001e0049783f008a0085193e00003d00cd54003c71'
]

const decoded = decodeEventLog({
    abi: ABI,
    topics: raw_log_topics as [],
    data: raw_log_data as `0x${string}`,
    eventName: "ApprovalForAll",
});

console.log(decoded);
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-4zufc6?file=index.ts

### Anything else?

![image](https://github.com/user-attachments/assets/9942efb1-353a-4db2-85b6-07a765cf379a)

**Comment by jxom** [comment]
You need to add `as const` to the `ABI` declaration.

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgEwKYGMJoKIDdUB2MAMhAOZwC+cAZlBCHAOS7CohMBQnmBAzvACCAIQCScALxwA2pzjzEchcoBEAQwIQCATxAQArnxUAuWmoA2fVABoly+SuAEw+mEdOz7Xxd99xHBGgAHqjIJnAwUPo2dn6qTjCoUAQWACraYKjh6sjIUKh8RrZxXiopIFmmKhAA7gRJKsUlqjAZlf5qufmFKrG+lE1xCH0lAcGh4ZHRg83+CUkp5umZ2Z15BUUjcWVqFdkQmVBqMNCNW34qrStVa91G58oDDwrDswpjqCFhpjQWVjPNAKJZJpNrZABGEAg5jObwc5Xa6jAYHo+DCANGV0RkOhvWalHOAF0MfDdojBMjURYAGLQQTmGEk-xY7KofBEPEKAmEuBqPhwXgCbiC+BHGoAfXM5HFyGOakk-gADEFFaq1eqNZqtdqdbrtQBGLg8LQCOBiyXSk5gYDoflSTzMZX6gDsAGZFc7UGpwa6AJzegBs+o9qAAHKHfb7QwAWACsnVdyFjvvByF9AdjrpoACZVTnc77c9GI+g1NnwcnXc6A+n0K7DU0mMq9S3FTR0NGs7GaL7cnHs7HQz61DQaPXU+DUBmg2nPUPnfq0ExG83W7r9ahVdHfc7Q1nVaG1AfY-rfa7N2rE6r0Eno6rXegF1xCcKTfA0Jg0MgFR+sKg8IQJDkAAFK8CjesApgiKIMxWjafCmOaUpkOKcG2ry-LSMSsSyjAaiIWoErITKcoYXAAAGyoACQIAIUBOGQlDkTMbKAQAcmSVQUiiEC4DSdIMmclAAJQANyvvw0KoAAdMhwG-l+YlAA
