### ISSUE TITLE
IntegerOutOfRangeError when encoding transaction data with large token approval amounts

### ISSUE THREAD

**Issue by ArielGueta** [wevm/viem#2524]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

^2.13.2

### Current Behavior

When interacting with dApps such as Uniswap, large token approval amounts are often used. For example, the approval amount might be:

> 115792089237316195423570985008687907853269984665640564039457584007913129.639936

Using the `parseUnits(amount, decimals)` function converts this to:

> 115792089237316195423570985008687907853269984665640564039457584007913129639936n

However, when trying to encode this amount for a transaction, the following code snippet:

```ts
const calldata = encodeTxData(tokenApprovalSig, [
  spender,
  parseUnits(amount, decimals)
]);
```

results in an `IntegerOutOfRangeError`.

### Expected Behavior

The encodeTxData function should handle large integers without throwing an IntegerOutOfRangeError.

### Steps To Reproduce

Use the parseUnits function with a large token approval amount:

```ts
const amount = "115792089237316195423570985008687907853269984665640564039457584007913129.639936";
const decimals = 6;
const parsedAmount = parseUnits(amount, decimals);
```

Attempt to encode the transaction data with the parsed amount:

```ts
const calldata = encodeTxData('function approve(address spender, uint256 amount)', [
  spender,
  parsedAmount
]);
```

**Comment by jxom** [comment]
`parseUnits('115792089237316195423570985008687907853269984665640564039457584007913129.639936', 6)` is greater than the maximum `uint256` value (2 ** 256 - 1) so this is expected.

**Comment by ArielGueta** [comment]
How it works for uniswap? any suggestion, please?

**Comment by jxom** [comment]
What do you need a suggestion for? Just don’t exceed the max uint256 range I guess.

**Comment by ArielGueta** [comment]
@jxom The value 115792089237316195423570985008687907853269984665640564039457584007913129639935 is exactly the maximum value for a uint256. So why the code throws?

**Comment by ArielGueta** [comment]
Ok, I see that there is some rounding.

115792089237316195423570985008687907853269984665640564039457584007913129639935 becomes 115792089237316195423570985008687907853269984665640564039457584007913129639936n

**Comment by ArielGueta** [comment]
Ok, the issue solved, thanks
