### ISSUE TITLE
Calling `net_listening` on RPCs yields 400's and other http errors on Network tab

### ISSUE THREAD

**Issue by 0x33dm** [wevm/viem#2540]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.16.1

### Current Behavior

I have been using the fallback transport, and I noticed it does [calls the ](https://github.com/wevm/viem/blob/main/src/clients/transports/fallback.ts#L233) `net_listening` function on RPCs.

What I have been observing is that some public RPCs don't implement, most of the time still they reply with 200 OK but sometimes they also respond with a weird 400.

I wonder if instead of net_listening we should change the method to be `eth_blockNumber` as it's unlikely an RPC won't implement that function and the response time from my location seems to be exactly the same, for instance for flashbots it's around 200ms.

### Steps To Reproduce

Turn `rank` on the fallback transport

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started?file=index.ts

### Anything else?

for instance:

![image](https://github.com/user-attachments/assets/767e0b5f-bf2c-4378-aa81-5f4eb2096902)

**Comment by jxom** [comment]
I wonder if `net_version` more supported than `net_listening`. We can’t really use `eth_blockNumber` as it would cost consumers Compute Units per call.

**Comment by 0x33dm** [comment]
> I wonder if `net_version` is more supported than `net_listening`. We can’t really use `eth_blockNumber` as it would cost consumers Compute Units per call.

Good thinking.

The funny thing I found is that `net_listening` sometimes isn't implemented, yet they return 200 OK, which is a super good trick to use for monitoring.

Perhaps we could add the name of the function to be called as a parameter on the fallback transport, eth_blockNumber probably doesn't cost much computing tough and it's probably cached on the RPCs

**Comment by 0x33dm** [comment]
Another weird behaviour I see, for instance, with "nodies" public RPC

 - it can be 200 OK for sometime
 - it can be 503 ( service unavailable )
 - CORS errors
 
From my understanding it basically means sometimes they're fine with taking requests from public ( it's a public node, so that should  be the case ), but sometimes they seem to be overloaded ( 503 ) and sometimes they probably just open for their own domain.

Because 503 (I guess any 5xx ) errors generate a lot of "error activity" on the "Console" from browsers, I believe we could consider giving a "cool down" period and exclude the RPC from the ranking algorithm to avoid flooding the console and burying some actual application errors.

![image](https://github.com/user-attachments/assets/bf7afe12-9f38-495d-a07d-1ff46300aad0)


![image](https://github.com/user-attachments/assets/2c573daa-aebd-4735-b0ea-b4cbfbef413a)

![image](https://github.com/user-attachments/assets/b9a771e4-bb18-4b0a-86f3-e5ff2895b12d)

**Comment by 0x33dm** [comment]
> I wonder if `net_version` is more supported than `net_listening`. We can’t really use `eth_blockNumber` as it would cost consumers Compute Units per call.

To start with, could we make the function used to `ping` a transport parameter wdyt?

For instance, in my case, I don't mind using `eth_blockNumber`, so it would be a great start for me to stop getting all these error messages on my website/sentry reports.

**Comment by 0x33dm** [comment]
> I wonder if `net_version` is more supported than `net_listening`. We can’t really use `eth_blockNumber` as it would cost consumers Compute Units per call.

I created a PR with rankMethod as a parameter. Would really appreciate if you could give me a help with the tests / getting the PR approved.

I understand ideally, we would want a better default, but in the meanwhile, it would be great to add this option.

https://github.com/wevm/viem/pull/2642

**Comment by 0x33dm** [comment]
@jxom any thoughts on this? would really appreciate some help with the PR.

Thank You
