### ISSUE TITLE
getChainId produces malformatted rpc requests

### ISSUE THREAD

**Issue by tadad** [wevm/viem#2542]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.18.2

### Current Behavior

when you call `getChainId` it formats the rpc request as 
```
    {
      method: 'eth_chainId',
    },
```
which is incorrect and causes issues with most rpc providers I'm aware of

### Expected Behavior

should succeed by adding `jsonrpc: '2.0'` to the request

### Steps To Reproduce

I'm running this against `alchemyplatform/rundler` and it's failing

**Comment by jxom** [comment]
We already do this https://github.com/wevm/viem/blob/main/src/utils/rpc/http.ts#L92.

Please provide a minimal reproducible example of the issue you are facing and I will reopen the issue.
