### ISSUE TITLE
`CustomSource.signMessage` has incorrect output type

### ISSUE THREAD

**Issue by matthiasgeihs** [wevm/viem#2562]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.18.5

### Current Behavior

Output type of `CustomSource.signMessage` is `Hash`. This is most likely incorrect because this outputs a signature which is not a hash.

https://github.com/wevm/viem/blob/410ff2b1b0a63553c3cf5e1e65816bf719cee80e/src/accounts/types.ts#L30

### Expected Behavior

Output type of `CustomSource.signMessage` should probably be `Hex`, as defined in `actions/wallet/signMessage.ts`.

https://github.com/wevm/viem/blob/410ff2b1b0a63553c3cf5e1e65816bf719cee80e/src/actions/wallet/signMessage.ts#L27

### Anything else?

This is just a minor nitpick, but was confusing me for a bit, so I think fixing would be nice.

**Comment by jxom** [comment]
Fixed.
