### ISSUE TITLE
`simulateContract` reverts when using a different ABI, even if the resulting calldata didn't change

### ISSUE THREAD

**Issue by 0xabdou** [wevm/viem#2566]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.18.5

### Current Behavior

I'm trying to simulate an erc20 `approve` transaction using `simulateContract`, the erc20 happens to be mainnet USDT.
If I use `viem`'s `erc20Abi`, I get the following error : `The contract function "approve" returned no data ("0x")`
If I use USDT's abi, the simulation succeeds.

### Expected Behavior

The simulation should not revert when using `viem`'s `erc20Abi`, since the generated calldata is the same for both abis (tested using `encodeFunctionData`)

### Steps To Reproduce

in the stackblitz project I linked, run `npx ts-node main.ts` in the terminal, you should see this result:
```
approving 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 succeeded
approving 0xdac17f958d2ee523a2206206994597c13d831ec7 succeeded
```
now change `USDT_ABI` to `viem's` `erc20Abi` on line 29 and re-run the cmd:
```
approving 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 succeeded
approving 0xdac17f958d2ee523a2206206994597c13d831ec7 failed: The contract function "approve" returned no data ("0x").
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-ec5bvb?file=main.ts

### Anything else?

We appreciate the mighty team behind viem and wagmi for improving web3 DX 🙏

**Comment by jxom** [comment]
USDT ABI does not conform to ERC20 spec unfortunately. It uses a modified version.

**Comment by 0xabdou** [comment]
it seemed weird that simulating an approval of WETH using USDT abi succeeds, but not the other way around
