### ISSUE TITLE
`createSiweMessage` domain check should support chrome extension id ?

### ISSUE THREAD

**Issue by zouhangwithsweet** [wevm/viem#2574]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

lastest

### Current Behavior

chrome extension host:
![image](https://github.com/user-attachments/assets/718cd0e6-96aa-42c4-be28-902819accdbd)

code: https://github.com/wevm/viem/blob/main/src/utils/siwe/createSiweMessage.ts#L66

### Link to Minimal Reproducible Example

https://github.com/fisand/wagmi-wxt-starter

**Comment by tmm** [comment]
Chrome extension IDs aren't valid [RFC 3986 authorities](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier), which is required for [ERC-4361](https://eips.ethereum.org/EIPS/eip-4361).
