### ISSUE TITLE
An Unexpected Error occurred

### ISSUE THREAD

**Issue by melzsanbox** [wevm/viem#2584]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.18.8

### Current Behavior

When I run:

```
npx hardhat deploy:custom --contract Token --params '["Wrapped Bitcoin", "WBTC"]' --network bnb_testnet
```

There is an error like in the picture, I don't know what happened.

I have also made some modifications in my codes such as:

- Changing the RPC Endpoint
- Changing the Timeout
- Changing the network gas

but the error is still not solved.

![IMG_2297](https://github.com/user-attachments/assets/e29b234b-cfde-42da-9e4e-bd126a3be506)

### Expected Behavior

I’m using Replit mobile and package version:

```
• viem: @2.18.8
• hardhat: @2.22.7
• nomicfoundation/hardhat-toolbox-viem: @3.0.0
• npm: @10.5.0
• node: @20.12.2
```

### Steps To Reproduce

My hardhat.config.ts file:

```
import "@nomicfoundation/hardhat-toolbox-viem";
import "dotenv/config";
import { HardhatUserConfig } from "hardhat/config";
import "./scripts/deploy";
import "./scripts/generate";
import "./scripts/push";
import "./scripts/peers";
import "hardhat-contract-sizer";

const accounts = process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [];

const config: HardhatUserConfig = {
  solidity: {
    compilers: [{ version: "0.8.24" }],
    settings: {
      optimizer: {
        enabled: true,
        runs: 10000,
      },
    },
  },
  contractSizer: {
    alphaSort: true,
    disambiguatePaths: false,
    runOnCompile: true,
    strict: true,
  },
  defaultNetwork: "localhost",
  networks: {
    localhost: {
      url: "http://localhost:8545",
    },
/*  bnb_mainnet: {
      url: "https://bsc-dataseed.binance.org",
      accounts,
    }, */
    sepolia: {
      url:
        process.env.SEPOLIA_RPC_URL ||
        "https://rpc.ankr.com/eth_sepolia/xxx",
      accounts,
    },
    bnb_testnet: {
      url: process.env.BNB_TESTNET_RPC_URL || "https://bsc-testnet.infura.io/v3/xxx",
      accounts,
    },
    opbnb_testnet: {
      url: process.env.OPBNB_TESTNET_RPC_URL || "https://opbnb-testnet.nodereal.io/v1/xxx",
      accounts,
    },
  },
  etherscan: {
    apiKey: "APICODE123",
  },
  gasReporter: {
    enabled: true,
    currency: "USD",
  },
  mocha: {
    timeout: 999999,
  },
  sourcify: {
    enabled: true,
  },
};

export default config;
```

### Anything else?

* This has happened before on the **Sepolia** network, but when I changed the **Sepolia** RPC it worked fine and was resolved on the **Sepolia** network.

However, it is different on the **BSC Testnet** network, I have changed RPC several times such as using RPC Public or using well-known RPC provider platforms such as _Quicknode, Infura, Moralis_ and so on. This is still not resolved

**FYI
> I used three different EVM networks namely Sepolia, opBNB, and BNB Smart Chain. And this happens only when I run the deploy command on the BNB Smart Chain network.

My contact
Telegram: @oomelz

**Comment by jxom** [comment]
Public RPCs have unreliable load balancing & caching mechanisms. I would suggest either:
- using a non-public RPC endpoint for BSC Testnet,
- [increasing `retryCount`](https://viem.sh/docs/actions/public/waitForTransactionReceipt#retrycount-optional) on `waitForTransactionReceipt` to >7.
