### ISSUE TITLE
Ethers V5 -> Viem migration is giving falsified information on estimating gas

### ISSUE THREAD

**Issue by hskang9** [wevm/viem#2600]
### What is the type of issue?

Documentation is missing, Documentation is incorrect, Documentation is confusing, Example code is not working

### What is the issue?

In migration from Ethers V5 to Viem [here](https://viem.sh/docs/ethers-migration#viem-18), current Viem client does not include the function `estimateContractGas`.

### Where did you find it?

https://viem.sh/docs/ethers-migration#viem-18

**Comment by jxom** [comment]
The Public Client does indeed include `estimateContractGas`.

https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBAbzgYygUwIYzQBQK4BGANsMgMIloB2MANHABYwxj1pTIBMADAIIHA4AXzgAzKBBBwA5ADdgaENIBQoSLERwQGYFSpp4I8ZJnzFAemQMdVAM4q4y5BDvxklGnAC8KdFlyEJOQeMAAUCMpwKNa6AFxaNvp0kXAwUBh26jDxTCyhAJTKQoVOIQB0aLYwoP5kLmkYyDAA4hi2yubmUd0AegD8kU4uVXAA5m3ecBgA7jpu5ZXV2th1NOlNrbbhjlEYACZ76La28dLcAB7StCkYAvHsXHwC9DtieFRNwC4AchggaKcMGAwBJZGgrjcoKMTnAANpnc7cJHIlGotHojEoq5wbhUAC6RXyjhSYzaHS6-SAA
