### ISSUE TITLE
KakarotSepolia with chain id `107107114116` is deprecated. 

### ISSUE THREAD

**Issue by shrirajpawar4** [wevm/viem#2610]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

Kakarot Sepolia with chain id "107107114116" is deprecated. 

New chain id for Kakarot Sepolia Testnest is "1802203764"

### Where did you find it?

in chains section in Wagmi docs. 
![image](https://github.com/user-attachments/assets/e4d2624a-38b1-466d-a6e3-f5ce1cca0e01)

a PR is already there with correction but reflection in docs is missing I guess
(https://github.com/wevm/viem/pull/2388)

**Comment by tmm** [comment]
> Chain definitions as of `viem@2.17.0`. For `viem@latest`, visit the [Viem repo](https://github.com/wevm/viem/blob/main/src/chains/index.ts).
