### ISSUE TITLE
onFetchRequest does not pass request into fetch

### ISSUE THREAD

**Issue by coffeexcoin** [wevm/viem#2630]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.19.7

### Current Behavior

when trying to use `onFetchRequest` to add a request header on http transport, the header is not passed up as part of the request when `fetch` is called

### Expected Behavior

Any modifications to the request in `onFetchRequest` are passed to the server as part of the http request

### Steps To Reproduce

```
  const wallet = privateKeyToAccount(generatePrivateKey());
  http("http://relay.flashbots.net", {
    onFetchRequest: async (request) => {
      const bodyText = await request.body?.getReader()?.read();
      if (bodyText?.value) {
        const signed =
          await wallet.signMessage({
            message: {
              raw: keccak256(bodyText.value)
            }
          });

        request.headers.set("X-Flashbots-Signature", `${wallet.address}:${signed}`);
      }
    }
  });
  ```

### Link to Minimal Reproducible Example

https://www.typescriptlang.org/play/?target=9#code/JYWwDg9gTgLgBAbwFBzgQQMYYgVwHYwA0K6AJqVAKYDO1xqAwgBYCGwe9cDANsJQZx58CDCHgBmwAOacMVFjEpD+REnMoLKABRwAjXhmUC18xQHUW3bpRhHVqABItqTTg8oAPTkxgwwnAGtKLBYAgCYAVgA2Ti0WKGpKTGx8ezgweMSAURgmSihODITKAHEAd0pgWKpfYHEAT04AJTAMAGUMPJAWThgIdy8SABUoFjxqSFhiAF84cSgIEDgAIgA3PhBlgG4kUEn4BDgpfnzNLShgVc0AaUpG9IurxVv6oYhk3AI4WfnFlfXKCAAPQsLCfGDUba7cDQA5wbrsPA2b5zBZLNYbIGdNjjKFITz7OAwepgShwABi3GcTF0EAhLXanUBLDgAF44ABtEhAgBUPJIcB5cAAAqQaHJgGAYMAxHA2qAcFTFHAWbp8KRrCqpDjqPAWRNgnVgBg4PoIBgAnA8DgQLp8oQ4OwMNwcKR2FI4NQFUr3SrTerNQoiXkiRAwHAIOJg2SkR54GaLQA6AVC4W8PCWnx+agALiBQNI5uoifEVJctIhiaRMCBpepFeoAFoWDgMNKxCDSFc8BhKKQgVBWo3+KRIOwYABiGxMAD6GEs3DVeA1lBTIs8LHA1jXYAW6zFUETVAAjjgaDAABSHEDTiCkHNwADk07nC4AQgHKI+HUVN7nOUSHj-hyj4AAweImkHfk+4GQYmj4ALoOgmAQAHI2naUAPmBEFQQ6uqaG+3DmmhGH5NhsFQXACHfAAlGu+ZsgAfIg-rLtYJTOOcxqUBRuHwchn5OC4fFwdB2DsLoziUAAInU4iiXhcDTm0KhvKIknSYpAlHM45KUDQ2nQVQ1CKhCD4cqxEl4FJiRyeICkwfx0EqWpEAaTZWlOWJDratQ+mGd5Sl+QAqok95BTpfRoOQJn-jhPmAcJTBGQ6VwurxkWPiiSGejAhHERa6G2uRWUOn0+XcJx1BhX2RnfCmQIkMgqCoAAsreEXLC+85WB+7GUFCrVwHEow3ooCQAPwWQw76fk0lCnueo1-ghOzDQtMA4FAeBDCSmWzX1800JA4yUHtpLrd8xBrUg+IeISxKkhSZY0nS1CYO24wADwkDAozjISniKMu1BwCMYwTLCbLgwDUNTGorDsMpcYjmDzA4nAAA+cDqpQkhIqQMMY8jON4wTfacKCKRfMDaPoGCqQwx8qTECx7ItXAvL8q1QryiAiqaH6S4rlqOp6p6pIYEaJooVaZEFI6PYum6eAel6As+mrwufiq8C5GSfThpG0ZWsDpqFQEya82ujZwDJRYPlmYC5vmAIgImLgFkWIJtjK4y1q9DZYguttwAAUm0ADyqGNk0WgMHAHW5HewEAAY9XNA1pwhF7O673sYMWdblu9VY2IH9bvc2rZfZ23a9v2g4YMOy5jgQU65K+Vgi9Y9E27zIq-ks8RSGDdsIGm7CWod3D9SuC1LbqK0gNQ0xrsKNTbeM4MhhrguKETvXcHAJlmcWiBTxmXBZwvJ1iIkF2UOvA+oKmG5bqug97NDhzqJolIq4QjsA6Z2KJfhLEfO7R8a4f6wFYgiPA1ZwFoifO7LESNxgwNfoKOA2BxjwGdMIeA7J-6KEAaXYBvAVBXjXKgbE7AHyIOrJwXBqB-qQ32E7XwYALy0VYUKaY-c354IfvAUgCgWTshYGUNghDqEEETMfee1haGD3YUBVKdCLYkWKphLR6i8oFV0QrIya4hGNTULfaw004AXgFCqKAY8HyzxUZQReZ5l7xD-CQWizERpomAIkb6rjjpQzOk-JiOxpg7CQE9MkFC3pUOIb9dhcMgao1BrDTh0N2QQ0BrCWQmCUYg1IOjYpZNlz43YH2YmFTcZVIpqQKmjNaaZLKQzGmJDOngk4M3DoXQWR0yyQyAZzJsYNLFE0mG5ManNKQOzAJNhpQNFSVwBRMA1lpJyQjYaDCOAOOpr0hx-SmTdBKfTUZZyWAOMmpyOCiSGxXMGQ6OCpzBkIQcQ+R571nnMlYS9IBH0-YP2+hwgpUw8GYKYiQGFUS7oEmhvEwFlDqB2FEBIaQazwXw3gMMjp+TcUw0JfsIpmN8XlMxpUqZcy6lUsmdUwmLSukXKySzL47J2VpHeeMilcA-nnOpYy2p7JZlMoWTDc4yy6j1BCRsjFkgpBgvSYUqFOIHRHNZqfVoYzuhMXhfdQk4h8AgrwHg0wlAfnJJUNilV8C+UksKYjcl7TKWkwZdM0VjS5nMvBKyjpXLmatO5Tq65-qwYCpZEKz1HqfULPsagYeNh8j-itWi+VYhFXKp2UQNV7ANXBodDyvVSBaLfKDu9Ow2aIW5v2Q6UaiQuXfU1QQJiRbQ2DJYpzfBupWJBHqDDZYJckmQgdHgTcZJ2TLDTes4hywUTsiTRNagV0e3yOITDMhSgNlqNanBJdKaAX9oBeOm8AL4kPiHRW61BBlicCEbE1AW8dp4I2YmfFF5h0Nk+v7agfjnAopHVWhxOLSUOLrQ4htSRg3NuDW2k5HbmSwuiXdZFoSBoeOWt41eMNOYwE0egKAoxZUDHhagFCejSq6GkOOK6BFFBERMSVLCpoaNfBxssJU54hpElAOeTcYBbHWmY9E2JaHrHuPvhE-auGSC91KFxC4vYHzUakLRuTQlqQPgGKuiAmk7LyRU2xmAV1XIEHUnpzyiQjNqYIFdPyAV-yqfU0+mg58HxoCIywWVnN6GWdsrJQzrHbMmYcWZmAFn9OZWc3ZhxDmDJOeM1dVAoVwo2Zc61aKsUaD-hihQHLyWkpabgMlQr6Uzzpdi6gaYZGjEMctpRljwnMJXQqpYaqtUIrNfyKJhFD1obGp7F9OY17gVfWoLanN4bsk1uJXatI+zpskzNdG2l7JlsTLFZTEgLa8Wup6UzTlhb41EJUOWoFdgy2Ae-aasGnNn1mt83giTD4Lyjz-f45Rn4LynYEI4se-CSAxKQOvQ10NnD1B7HME1w2vsDTWYtvlG3VvitQLt6bXK2YJtfcQ87qKq2OshXWlUcGqZOP-Ohu+S8YAr2oKWh85xFhBMoCEiTC1wmP32l2tQYjT5ScSDDGRciccqCPItTxl4nvjSYHeS9mcjoDTvQ44ewF3tISB7RR9fOtovpMqdRIKGkBrvhJjaR1BIcmj4f47tvPfvdK3TofQxo7C7u2TW7hfgLzLGdnmIEABGAAnGERMfuogAA5EwAGYo85jDxEAALBEZYgO9mYKYTiFhGu7p+YISNoFgbF2PBuHcN4XKLzHCRKMRQ3EniUBeHwzX2fRG56-e9TdFq00u6e6B2EHveHe54QXKgVJ6gllG+XGAd7EAONQGIfSMBOiYd1A+CHUOLwngl341k3Php7N57SUgrxzbSNkcAeAG-zyJgP-USaiZjgwAWiwA8fDb-yFIHwwrw06h2Ov0MYGt-ytKA-Entd9m9e0vQpBCZBdT94BW8IQuVPZpA8AOpaAWBjhXdQDWobxUDjgHwQDMCn0ZEHwggQhwhogLxf9gZExADhECDqsZ9d8H0GDhoL9dREw8gn8U1PYbAvcAANRsNNRseUSAhQbaQaB0NOAAEgQDgOBS6UTCf3y1oGmBzGkIgMJmmDTkbwIJfkYIBSEQBV2wfFkMx3AzTxN0RBsA1y12N1kSsGRFIQtQsHsNsB3W73mz7y9x93zED2D1Dwj2j0j1jwTyTxT1an2XT0sLSDR2DQfF3EuGL1eHeGDXLxOCr20CL2eDuAbyzx51zzlhP2FztzvxsEYyKgVg-yb2N1GDKCGA8GgOFzsOsBgEQMgMJVBC+gwMALiMyEoByDyCgC91AkTFAmT3PQgAfCaJsAUODQUOy1oHPX2jl0lD9wiAiADyV2Gm6A8ACi0HyGqh6OKHKEqC9z91AlGLCNQG2O4mgDP3qF2P2OcEOMSGOOAFOLGOsKqNtwXAaLPzz1RSUQk1vwwPw2AhqLqPV2Ggo1MR0QtABXo0oDKNImY0vS411GWFyJz2oAgGsETGIikB+wXEb1B2-3X3F2ACoETEQTZFZHZBADvEVCAOnyuJxD4UBIXyYB+wfhxMoHfSI2gGJKQCAA

### Anything else?

It appears this was broken with https://github.com/wevm/viem/commit/581dc93fb5216ee910ac741af617f0c45edf582b as the `Request` object passed to `onRequest` is not actually passed to fetch anymore, but instead `url` and `init` are passed.

**Comment by 841660202** [comment]
When will the fix be released?

**Comment by 841660202** [comment]
@jxom When will the fix be released?

**Comment by coffeexcoin** [comment]
Curious if you have any thoughts on how this might be able to be resolved without breaking the dispatcher functionality referenced in #2126 

It looks like `dispatcher` is not a valid property on `RequestInit` as part of the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit) but instead something exclusive to node provided by undici.

My thinking is perhaps that we add an `onRequestInit` that allows modifying the RequestInit object once the body is included - something along these lines:

```ts
const requestInitHandler = onRequestInit ?? (url, init) => init;
const init: RequestInit = requestInitHandler(url, {
    ...fetchOptions,
    body: Array.isArray(body)
      ? stringify(
          body.map((body) => ({
            jsonrpc: '2.0',
            id: body.id ?? idCache.take(),
            ...body,
          })),
        )
      : stringify({
          jsonrpc: '2.0',
          id: body.id ?? idCache.take(),
          ...body,
        }),
    headers: {
      'Content-Type': 'application/json',
      ...headers,
    },
    method: method || 'POST',
    signal: signal_ || (timeout > 0 ? signal : null),
  }
});
