### ISSUE TITLE
Update  (spicy network) Block Explorer URLs from HTTP to HTTPS

### ISSUE THREAD

**Issue by abdul-kabugu** [wevm/viem#2649]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

^2.10.1

### Current Behavior

whenever  i try to  interecat with smart contract on chiliz testnet (spicy network)  i  get this  error   **inpage.js:1 MetaMask - RPC Error: Expected null or array with at least one valid string HTTPS URL 'blockExplorerUrl'. Received: http://spicy-explorer.chiliz.com**
![errorsrr](https://github.com/user-attachments/assets/ed91314e-c6dc-49c5-8564-9b2ccb2776e1)

### Expected Behavior

i expected  whenever  I  call smart contract function  metamask will pop up and  sin tx

### Steps To Reproduce

interact with  any smart contract function deployed on spicy net

**Comment by tmm** [comment]
Feel free to create a PR!
