### ISSUE TITLE
`waitForTransactionReceipt` timeout exception after confirmed

### ISSUE THREAD

**Issue by vimtor** [wevm/viem#2650]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.13.1

### Current Behavior

Sometimes, when calling `waitForTransactionReceipt` with a timeout, the call times out, but when you check the transaction hash on an explorer, you can see that the transaction was confirmed within the timeout period.

We are experiecing this on Taiko's chain. Here are our server logs:

![CleanShot 2024-08-23 at 14 25 58@2x](https://github.com/user-attachments/assets/5a540c06-39b0-4c42-ae37-13ce52350abd)

And here is the transaction on the explorer:

![CleanShot 2024-08-23 at 14 26 51@2x](https://github.com/user-attachments/assets/c8440c14-dbb9-4318-8708-efb6ff84daa5)

As you can see, the transaction was confirmed in a minute, but the client wasn't able to find it after 5 minutes.

### Expected Behavior

`waitForTransactionReceipt` should only throw if the transaction is not confirmed within the timeout period.

### Steps To Reproduce

I can't provide an exact reproduction since I don't know the origin of the issue.

**Comment by tmm** [comment]
Are you using a public RPC URL or a paid service? Public RPCs tend to not be as high-availability/responsive.

**Comment by jxom** [comment]
> As you can see, the transaction was confirmed in a minute, but the client wasn't able to find it after 5 minutes.

Viem’s Client is only as smart as the RPC Provider that you pass to it (via `http` Transport). Viem periodically calls the RPC Provider to try and retrieve the receipt. If no receipt is resolved from the RPC Provider from these calls, then Viem throws the error that you see here.

Have you tried using an alternate RPC Provider?
