### ISSUE TITLE
readContract fails with error: `Uncaught (in promise) ContractFunctionExecutionError: HTTP request failed...` on local anvil rpc node

### ISSUE THREAD

**Issue by MurdeRM3L0DY** [wevm/viem#2668]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.20.1

### Current Behavior

reading from a contract on a local anvil rpc node fails from the solid js frontend

### Expected Behavior

reading from a contract on a local anvil rpc node shouldn't fail from the solid js frontend

### Steps To Reproduce

1) Clone the provided repro
2) Install dependencies via `pnpm i`
2) Open 2 terminal emulators
3) run ```anvil --no-cors --state state.json``` on one 
4) run ```pnpm dev``` on the other
5) Open your web browser to `localhost:3000`, also open the console
6) Click on the `TriggerIssue` button in the webpage and observe the errors in the console

I've also provided a script at `script/readContract.s.ts` to show that reading from contract only fails on the browser webpage.
You can run this script via: ```pnpm tsx script/readContract.s.ts```; 

### Link to Minimal Reproducible Example

https://github.com/MurdeRM3L0DY/viem-issue-repro

### Anything else?

I've had to provide a github repro as it must be run against a local anvil rpc node. I've made such to keep it as minimal as possible by including the `state.json` file which contains the state of blockchain with the already deployed contract + the autogenerated abi.ts file only contains the basic `counterAbi`. 

Here's a screenshot of the error from the console:
![viem-issue-error](https://github.com/user-attachments/assets/42333080-433c-423a-b3e9-03be32ce26f4)

**Comment by jxom** [comment]
Works for me if I remove `--no-cors` from `anvil`, and `no-cors` from the HTTP request headers.

I wouldn't recommend using `no-cors`. Instead, might be worth looking into laxing the CORS policy.
