### ISSUE TITLE
hashBytecode errors with     const hex = hex_.replace('0x', ''); TypeError: hex_.replace is not a function

### ISSUE THREAD

**Issue by jarrodwatts** [wevm/viem#2695]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.2

### Current Behavior

I have a big `ACCOUNT_BYTECODE` variable (too big to fit in the issue)

- Call `hashBytecode(ACCOUNT_BYTECODE)`
- Errors with the error below.

```
const hex = hex_.replace('0x', '');
                     ^
TypeError: hex_.replace is not a function
    at padHex
    at encodeBytes
```

**Comment by jxom** [comment]
Minimal reproduction?

**Comment by jxom** [comment]
Your stacktrace has usage from `encodeAbiParameters` (`encodeBytes`). However, `hashBytecode` has no codepaths to `encodeAbiParameters`. Are you sure your stacktrace is coming from `hashBytecode`?

**Comment by jarrodwatts** [comment]
Hey @jxom - apologies was AFK for a few days.

You're right the hashBytecode works as expected. I was trying to provide the bytecode hash as an argument to my factory contract when calling `deployContract`. To fix the issue I was having, I just needed to wrap the hash inside `toHex` for it to work.

Not sure if any action is required here but just letting you know.

**Comment by jarrodwatts** [comment]
Here's my code - https://github.com/Abstract-Foundation/examples/blob/main/contract-deployment/clients/src/viem.ts
