### ISSUE TITLE
Contract Function Execution Error Due To Different Contract Function Param Name

### ISSUE THREAD

**Issue by Metaxona** [wevm/viem#2703]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.19.7

### Current Behavior

i am having a problem using erc20Abi specifically approve since in the erc20Abi the approve uses 

```solidity
approve(address spender, uint256 amount) 
```

while the contract i am trying it on uses 

```solidity
approve(address _spender, uint256 _amount)
```

which made it impossible for me to call the function and will likely happen on every erc20 tokens that uses a different param name

and throws an error like this

![image](https://github.com/user-attachments/assets/0efa66df-3e3a-4cde-9ed2-0cd415b598bd)

### Expected Behavior

the call should use the signature without the param name like this

```solidity
approve(address,uint256)
```

which from what I know, what evm uses when calculating function signatures instead of including the param names (correct me if i am wrong on this one)

by ignoring the param names, it won't affect the contract interactions due to having a conflict in param names from the standard abi and the one being implemented on the contract

---

there's also the issue about that from both the eip site and the one openzeppelin use being different

[EIP-20](https://eips.ethereum.org/EIPS/eip-20#implementation)

![image](https://github.com/user-attachments/assets/01aa2bd5-8d6b-45e3-a229-9a73a48d4063)

[Openzeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.1/contracts/token/ERC20/IERC20.sol)

![image](https://github.com/user-attachments/assets/292ba486-001b-4ccc-8a6b-27cbce35ce17)

here you will see that the EIP-20 one uses the version with _ while the Openzeppelin one does not 

### Steps To Reproduce

1. deploy 2 basic erc20 token that has different param names 

one with

```solidity
approve(address spender, uint256 amount) 
```

another with

```solidity
approve(address _spender, uint256 _amount)
```

2. setup interaction client (@wagmi/core | viem)
3. use `erc20Abi` from viem
4. interact with it using either @wagmi/core or viem's `writeContract`

**Comment by jxom** [comment]
I can't reproduce this. Can you provide a minimal reproduction, or try [break mine](https://github.com/wevm/viem/commit/aa9ecb9b402ee94a272e4f21ce764b94f533355a)?

**Comment by Metaxona** [comment]
> I can't reproduce this. Can you provide a minimal reproduction, or try [break mine](https://github.com/wevm/viem/commit/aa9ecb9b402ee94a272e4f21ce764b94f533355a)?

Here's a reproduction repo without the private ley so you have to provide yours

https://github.com/Metaxona/viem-issue-2703

this one also has the address of the contract being used which is causing an error. 

the contract is verified on [sepolia etherscan](https://sepolia.etherscan.io/address/0x5acf514746f8A725A5D688359dFF1F5db289D7d0#code)

**Comment by jxom** [comment]
The `approve` method on that contract doesn’t return a `boolean` value. The ERC20 spec specifies that `approve` must return a `boolean`.

To get this to work, you will need to make `outputs` an empty array on the `approve` function of the ABI.

**Comment by jxom** [comment]
The `approve` method on that contract doesn’t return a `boolean` value. The ERC20 spec specifies that `approve` must return a `boolean`.

To get this to work, you will need to make `outputs` an empty array on the `approve` function of the ABI.

**Comment by Metaxona** [comment]
> The `approve` method on that contract doesn’t return a `boolean` value. The ERC20 spec specifies that `approve` must return a `boolean`.
> 
> To get this to work, you will need to make `outputs` an empty array on the `approve` function of the ABI.

hmmm, i did not notice that. so i got this code from usdt deployed on ethereum mainnet which is weird too since they are linking the implementations on the code to the eip 20 docs

and another weird thing is using `cast sig` from foundry-rs returns the same thing with or without the return

``cast 0.2.0 (6de15b0 2024-07-15T00:21:23.265849459Z)``

```bash
viem-issue-2703 git:(main) cast sig "function approve(address _spender, uint256 _value) returns (boolean success)"

0x095ea7b3

viem-issue-2703 git:(main) cast sig "function approve(address _spender, uint256 _value)"                          

0x095ea7b3

viem-issue-2703 git:(main) cast sig "function approve(address spender, uint256 value)"  

0x095ea7b3

viem-issue-2703 git:(main) cast sig "function approve(address spender, uint256 value) returns (boolean success)" 

0x095ea7b3

viem-issue-2703 git:(main) cast sig "function approve(address spender, uint256 value) returns (boolean _success)"

0x095ea7b3
```

so with this, that call should work since they all generate the same function signature with or without the return output

**Comment by jxom** [comment]
That is correct. Selectors are computed from the keccak256 hash of a contract signature, and a signature only contains the parameters.

The call is not working because Viem is expecting a return value (`boolean`), however, the contract method is returning nullish data (`0x`).

**Comment by Metaxona** [comment]
> That is correct. Selectors are computed from the keccak256 hash of a contract signature, and a signature only contains the method name + parameters.
> 
> The call is not working because Viem is expecting a return value (`boolean`), however, the contract method is returning nullish data (`0x`).

hmmm that checks out, cause if viem is not expecting anything to return it would still work

though there's a problem with this making the built-in erc20Abi from viem unable to be used on all erc20 tokens that follows the standard or atleast most of it like in the case of USDT on ethereum mainnet

so i guess to solve this problem without relying on viem to fix it on the source side of the code would be to set the exact abi used by the contract for this kind of situations then and just put it in an object like `{ [chainId]: { [tokenAddress] : tokenAbi } }` and populate it with the custom abi while using the standard ones if they don't exist

also yeah the error also says that it returned not data `0x`
