### ISSUE TITLE
Problem with zero in unit256 indexed event

### ISSUE THREAD

**Issue by sstepanchuk** [wevm/viem#2728]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.7

### Current Behavior

Event filter ignore prop, if prop = 0, so filter not work properly

### Expected Behavior

Event filter should filter events by this prop if prop = 0, filter should return events with prop = 0

### Steps To Reproduce

emit any event with indexed unit256 property with 0 value. 
emit any event with indexed unit256 property with value diffrent from 0.

try to get event log that have value 0, you will recive all logs, not only this log 

### Anything else?

My event

`
struct Pixel {
        address owner;
        uint24 color;
    }
event PixelChanged(
        uint256 indexed Y,
        uint256 indexed X,
        address indexed changer,
        Pixel old,
        Pixel current
    );`
    
part of my TS code

`(BigInt.prototype as any).toJSON = function () {
  return this.toString();
};

async function deployBoardFixture() {
    const [owner, otherAccount] = await hre.viem.getWalletClients();

    const board = await hre.viem.deployContract("Board");

    const publicClient = await hre.viem.getPublicClient();

    await board.write.setPixels([
      pixels
    ]);

    return {
      board,
      owner,
      otherAccount,
      publicClient,
    };
  }

const { board, owner } = await loadFixture(deployBoardFixture);

const changes = await board.getEvents.PixelChanged({
          Y: 0,
          X: 0,
          changer: owner.account.address
        }, {
          strict: true
        });
console.log(JSON.stringify(changes, null, '   '));

`
 
 JSON that return console log: 
 
 `[
   {
      "eventName": "PixelChanged",
      "args": {
         "Y": "0",
         "X": "0",
         "changer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
         "old": {
            "owner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
            "color": 1
         },
         "current": {
            "owner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
            "color": 1
         }
      },
      "address": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "blockHash": "0x11f6502c9d8dcef7ecddfc259ccef94de8893883399834b49c772836abfdf6ce",
      "blockNumber": "2",
      "data": "0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000001",
      "logIndex": 0,
      "removed": false,
      "topics": [
         "0x84b3faa68b847ee5bd2633b3149d770ed66d387f87b8bfcf7fe5bffc28a59ddf",
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"
      ],
      "transactionHash": "0xde8652351b4eb0f3a0bbb99ec5bb0c605de7cfc9f2ca9e99cb278ca0916fe4e3",
      "transactionIndex": 0
   },
   {
      "eventName": "PixelChanged",
      "args": {
         "Y": "0",
         "X": "1",
         "changer": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
         "old": {
            "owner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
            "color": 2
         },
         "current": {
            "owner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
            "color": 2
         }
      },
      "address": "0x5fbdb2315678afecb367f032d93f642f64180aa3",
      "blockHash": "0x11f6502c9d8dcef7ecddfc259ccef94de8893883399834b49c772836abfdf6ce",
      "blockNumber": "2",
      "data": "0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000002000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000002",
      "logIndex": 1,
      "removed": false,
      "topics": [
         "0x84b3faa68b847ee5bd2633b3149d770ed66d387f87b8bfcf7fe5bffc28a59ddf",
         "0x0000000000000000000000000000000000000000000000000000000000000000",
         "0x0000000000000000000000000000000000000000000000000000000000000001",
         "0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266"
      ],
      "transactionHash": "0xde8652351b4eb0f3a0bbb99ec5bb0c605de7cfc9f2ca9e99cb278ca0916fe4e3",
      "transactionIndex": 0
   }
]`

**Comment by sstepanchuk** [comment]
https://stackblitz.com/edit/stackblitz-starters-hsq1lz?file=test%2FTest.ts

**Comment by sstepanchuk** [comment]
@jxom

**Comment by jxom** [comment]
Thanks. Fixing now.

**Comment by sstepanchuk** [comment]
nice, thank you!

@jxom also. can you pls open this issue?

**Comment by jxom** [comment]
should be fixed in latest version

**Comment by sstepanchuk** [comment]
okay
