### ISSUE TITLE
Problem with Address ToString function

### ISSUE THREAD

**Issue by sstepanchuk** [wevm/viem#2745]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.10

### Current Behavior

I got diffrent addresses in account Object and in Event log that i recive from request

### Expected Behavior

I expect same addresses in account Object and in Event log that i recive

### Steps To Reproduce

https://stackblitz.com/edit/stackblitz-starters-hsq1lz?file=test%2FTest.ts

it's second test

![image](https://github.com/user-attachments/assets/14f6ea62-c687-4c15-9db5-57c10ea243ef)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-hsq1lz?file=test%2FTest.ts

**Comment by sstepanchuk** [comment]
![image](https://github.com/user-attachments/assets/32bc10af-ff71-4e47-9c63-39c041825c4c)

**Comment by sstepanchuk** [comment]
address to string function not work same, take a look to 'f' and 'F'

or to 'b' and 'B'

**Comment by jxom** [comment]
The addresses are the same. One is checksummed, and the other is not.

**Comment by sstepanchuk** [comment]
@jxom 

why Address in account is checksummed and address that i recive is not checksummed?

how i can checksum this address in viem?

**Comment by sstepanchuk** [comment]
in two cases we have the same type of object (address) and it is logical that the information in them should be the same

the question is, why are they different?

**Comment by sstepanchuk** [comment]
@jxom

**Comment by jxom** [comment]
The Account address is often used for display purposes, so it’s default to the checksummed version for safety.

**Comment by sstepanchuk** [comment]
got it, thank you for the answer
