### ISSUE TITLE
Problem with event logs filter

### ISSUE THREAD

**Issue by sstepanchuk** [wevm/viem#2746]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.10

### Current Behavior

Should be two event logs, but i got diffrent count

### Expected Behavior

Need recive two event logs

### Steps To Reproduce

https://stackblitz.com/edit/stackblitz-starters-hsq1lz?file=test%2FTest.ts

It's first test

![image](https://github.com/user-attachments/assets/265a6635-440d-479a-8d7b-e7be0b551ebd)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/stackblitz-starters-hsq1lz?file=test%2FTest.ts

**Comment by jxom** [comment]
The version of Viem being used here is `2.7.6` (see package-lock.json). You will need to upgrade to the latest version as [mentioned here](https://github.com/wevm/viem/issues/2728#issuecomment-2354751933).

**Comment by sstepanchuk** [comment]
![image](https://github.com/user-attachments/assets/a981e268-4248-4ee4-9ece-5026f7a3bfc1)

**Comment by sstepanchuk** [comment]
it's from local package lock

**Comment by sstepanchuk** [comment]
@jxom

**Comment by sstepanchuk** [comment]
@jxom

**Comment by jxom** [comment]
Please avoid directly tagging me, and please provide a minimal repo with only the `viem` dependency (no hardhat)

**Comment by sstepanchuk** [comment]
got it, thank you for the answer
