### ISSUE TITLE
`createPublicClient` with chain `optimism` doesn't satisfy `PublicClient` type

### ISSUE THREAD

**Issue by dalechyn** [wevm/viem#2763]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.12

### Current Behavior

Doesn't satisfy type `PublicClient`.

### Expected Behavior

Should satisfy it.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-mnbjxw?file=index.ts

**Comment by jxom** [comment]
TypeScript needs the generic as OP Stack chains contain different interfaces for Transaction + Receipt schemas (ie. deposit transactions, L1 gas/fee properties on receipt, etc):

https://stackblitz.com/edit/viem-getting-started-8av1yq?file=index.ts

**Comment by dalechyn** [comment]
thanks!
