### ISSUE TITLE
createTestClient type is too heavy 

### ISSUE THREAD

**Issue by pociej** [wevm/viem#2778]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.10

### Current Behavior

```
export function client(chainId: number) {
  return createTestClient({
    chain: foundry,
    mode: "anvil",
    transport : http(),
  })
  .extend(publicActions)
  .extend(walletActions)
}

```

gives ts error The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed. 

### Expected Behavior

There is no need to provide separated explicit annotation

**Comment by jxom** [comment]
Fine on my end: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgYygUwIYzQFTQZxgGEAbYNAOxgBo4wBXAIzOQEFkZgIL9aB3DCRJoY7Tt15wAFjBhg4AXzgAzKBBBwARADdyITQG4AUKEixEKiPQoATKAE9FKtRp16A9MikZgPQ0aNkCXhkMkp4AF4UdCxcAmIwqgAKBCM4FG9fAC5Lazt7ajS4EAgbNBzNDApdEk1C9JgoKvwzGByZOSSASkKFLqKAOjQAD2xbJIZmYDYOLh5+9KHRyhskgSERMTn8LuMgA
