### ISSUE TITLE
Multicall with undefined account fails in some rpc providers (gnosis)

### ISSUE THREAD

**Issue by agualis** [wevm/viem#2792]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.15

### Current Behavior

Running a multicall with viem's public client in gnosis chain like this: 

```ts
 const client = createPublicClient({
      transport: http(rpcUrl),
      chain: gnosis,
 })

client.call({
      to: gnosisRelayerAddress,
      data: encodedMulticall,
    })
```

fails in some rpc urls (i.e. alchemy) because `from` is `undefined` when doing the `eth_call` request. Rpc error: 

```
{jsonrpc: "2.0", id: 6,…}
error
: 
{code: -32015, message: "vm execution error.", data: "Reverted Incorrect sender"}
id
: 
6
jsonrpc
: 
"2.0"
```

### Expected Behavior

The rpc provider should understand that `undefined` `from` (AKA `account`) means `zero_address` and not fail.

Note that if we explicitly provide the zero address in account field like this: 

```ts
client.call({
      account: '0x0000000000000000000000000000000000000000' //ZERO_ADDRESS
      to: gnosisRelayerAddress,
      data: encodedMulticall,
    })
```
If [this viem code](https://github.com/wevm/viem/blob/320e2dc468248168691e6d3f3e2705d33e52c423/src/actions/public/call.ts#L177) was updated to use ZERO_ADDRESS instead of undefined by default, the issue would be fixed but I'm not sure if the problem is in the providers implementing the rpc `eth_call` contract or in viem's side TBH

### Steps To Reproduce

1. Open [stackblitz reproduction link](https://stackblitz.com/edit/github-3de52b?file=src%2FExamples.tsx%3AL22)
2. Update `ALCHEMY_API_KEY` with your key 
3. Click `run private multicall` button and see how the multicall sucessfully returns
4. Click `run private multicall` button and see the error both in the UI and in devtools network tab. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3de52b?file=README.md

### Anything else?

Using `https://rpc.gnosischain.com` and other public RPC urls often work as expected (not like alchemy) but randomly fail with the same error (difficult to consistently reproduce)

**Comment by jxom** [comment]
Likely an RPC issue. It seems that Alchemy may require a `from` address for nonpayable/payable functions. I am not sure statically setting an address of `0x0000000000000000000000000000000000000000` on our side is particularly safe as that would mess with account-dependent contract calls.

Might be best to get in touch with Alchemy!

**Comment by agualis** [comment]
Thanks @jxom, agree that it's not a good idea to set the Zero_Address by default on our side.
Alchemy is already working in a fix but just note that we found this issue also with other providers (although it happens randomly for some of them).

**Comment by agualis** [comment]
More context in case someones hits this issue: 

Currently, these calls without a sender (from) are failing on `Nethermind` and `Geth` nodes, but they work on the `Erigon` client.

Tests performed by the alchemy team. with the following providers and only the `Erigon` based clients don't require the "from:" arg. for this call:

Erigon
https://rpc.gnosischain.com
https://gnosis.blockpi.network/v1/rpc/public
https://gno-mainnet.gateway.tatum.io

Nethermind / Geth
https://rpc.gnosis.gateway.fm
https://gnosis-mainnet.public.blastapi.io
https://rpc.ap-southeast-1.gateway.fm/v4/gnosis/non-archival/mainnet
https://gnosis.drpc.org
https://gnosis-rpc.publicnode.com
https://1rpc.io/gnosis

**Comment by jxom** [comment]
Can you also test this on a Reth node (e.g. `eth.merkle.io`)?

**Comment by agualis** [comment]
> Can you also test this on a Reth node (e.g. `eth.merkle.io`)?

AFAIK it does not support `gnosis` (where my multicall fails). I don't have equivalent multicalls in supported chains but I will test it when I eventually have them.
