### ISSUE TITLE
prepareUserOperation fails when Chain is not passed as an arguement

### ISSUE THREAD

**Issue by AyushBherwani1998** [wevm/viem#2796]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.15

### Current Behavior

When creating `createSmartAccountClient` from permissionless-js, the `chain` is an optional parameter.
```
const smartAccountClient = createSmartAccountClient({
      account: smartAccount,
      bundlerTransport: http(BUNDLER_URL),
      paymaster: bundlerClient,
      // chain: arbitrumSepolia,
      userOperation: {
        estimateFeesPerGas: async () => (await bundlerClient.getUserOperationGasPrice()).fast,
      }
    });
```

If we try to sign the user operation when paymaster is also present, it throws an error that chain id is not present, and the logs are from prepareUserOperation. Checking from the code, chain is a nullable parameter, but we are not doing null checks, and force casting to non nullable. 

### Expected Behavior

Ideally we should check if the chain is nullable, and accordingly get the chain id. Currently chain is nullable, but it won't work if we don't pass the chain. 

### Steps To Reproduce

You can try to create a SmartAccountClient with paymaster, and no chain, it'll throw an error while signing the transaction.

**Comment by jxom** [comment]
Fixed via https://github.com/wevm/viem/commit/705eb21b18f9993abbfd666c48de8c588ab86822. Added you as a co-author!
