### ISSUE TITLE
Recent `parseEventLog` breaking change

### ISSUE THREAD

**Issue by Ncookiez** [wevm/viem#2810]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.16

### Current Behavior

The recent change to `parseEventLogs` (2fa3d004467945efc548ac23a659c32a1e206cc4) made in version `2.21.8` has a (maybe intentional?) side effect of allowing `undefined` as a valid value of an argument to filter events by. This was listed as a patch update and so I paid it little mind, but it broke my codebase :(

Passing `undefined` to an arg to filter by in strict mode will most likely mean your query will never return any events now. If this is intentional, I'd ask to include some notice of that change either in the functions' in-code docs or the [external docs](https://viem.sh/docs/actions/public/getLogs#arguments). If not, adding `|| value === undefined` to the same lines changed in that commit would bring back the old functionality.

For example, a function like this no longer works:
```ts
const getTokenTransferEvents = async (
  publicClient: PublicClient,
  tokenAddress: Address,
  options?: { from?: Address[]; to?: Address[] }
) => {
  return await publicClient.getLogs({
    address: tokenAddress,
    event: {
      inputs: [
        { indexed: true, internalType: 'address', name: 'from', type: 'address' },
        { indexed: true, internalType: 'address', name: 'to', type: 'address' },
        { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' }
      ],
      name: 'Transfer',
      type: 'event'
    },
    args: {
      from: options?.from,
      to: options?.to
      // Existing codebases like this would have to use the following:
      // from: options?.from ?? null,
      // to: options?.to ?? null
    },
    strict: true
  })
}
```

### Expected Behavior

The `parseEventLogs` function should ignore `undefined` as it does `null`, or this new behavior should be clarified in the docs if intended, since it's quite hard to find and debug as of now.

### Steps To Reproduce

Pass `undefined` to any `getLogs` function's indexed args to filter by. No events will be returned.

**Comment by jxom** [comment]
Got it. This is a bug. Will fix.
