### ISSUE TITLE
`TestClient.extend` does not expose overridden `client: TestClient` in extension callback

### ISSUE THREAD

**Issue by Rubilmax** [wevm/viem#2815]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.17

### Current Behavior

In the following expression: `createTestClient({ ... }).extend(extensionCallback)`, `extensionCallback` expects a `client: Client<transport, chain, account, rpcSchema, extended>` from [this type definition](https://github.com/wevm/viem/blob/03df7fbe0da3332a3ceee645d7ec6ede2a832010/src/clients/createClient.ts#L137)

Whereas the type could be more precise in the case of a `TestClient` which has an additional `mode` property: `TestClient<mode, transport, chain, account, includeActions, rpcSchema>`

This limits the composability of actions as I cannot extend the client with an action that requires a test client (including the mode property) without force casting

### Expected Behavior

In the previous example, I expect `extensionCallback` to have access to a `client: TestClient<mode, transport, chain, account, includeActions, rpcSchema>`

**Comment by Rubilmax** [comment]
Here is a real-world example where I need to force cast: https://github.com/Rubilmax/viem-deal/blob/727cf6b168f42ea111694372a381cd226db521e7/src/dealActions.ts#L37

**Comment by jxom** [comment]
Fixed: https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwFBzgYygUwIY0wYQBthMA7GAGhXS10wBVMBnGIk8q1PFgQTRmARSTTnAAWMGGFEwAnmExx8Y7MFIz5ivmggBXDtTkK49KNmGRYG44xZsylJAF84AMygQQcAEQA3EiDeANxwAPShcEbMAFzo5thQskiglvAIcOb+hHAu7p4+-pggoWgqakzBSEjhcADuERg4eLasxA5IyKg6wvBobeRwALw0TQzMrewwABSdqOhlpLGZwISiXGYW0DCxElJTAJRrcCAQACaYsd7LhN6iTvsAdJgAHnikp1Pn2IR8AkJM+yCziqNXqIzo9nIHWo3RY6H68GGjQhCJm1C6CyWpCyRxgGyYqR2kjABzu+3RcCerzIHwOQwAfHAZsczhcfNdvDl9uS5pSXm8PtwYL9BMJmSdzpcOVyeXMqQLPjgfvxRQCgU4QeEtdqdbq9dqqlETONITAALKsobs7ErTkAHx8KigpxUMHtPgA5vFSphKkgXqk3PoVUI4F9lX9hAAeGELOD8mlMJRxh36c6uNSYU5W5SqUhwVPvTAZ0hZ0TYNA6fTwBPvJPaPQDQvpzPZ4YN6sFuBp4utqj0qZ9SaxFqmqOjhEW84UEz41Iz0p5mcVqvken7RDULAwXRQfOzVDh2J0waM8ODhGHahOdVVVzByNhpUxjF5+PUuvJt-N3ul07lytGxrD9TnrQDOx-EsyyQAchwcEcTQRcdEMmKdMBnUxzAJLYFwWZdwI4NxviYTB103VBt13fM4PIB4sAAR10cY0V5EBMBgMQzliAADAASBAaJgB4JUwJwAH1Tl0cAAGUYDobiyVvIA
