### ISSUE TITLE
useSimulateContract with BigInt argument throws "TypeError: Do not know how to serialize a BigInt"

### ISSUE THREAD

**Issue by actuallymentor** [wevm/viem#2833]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.18

### Current Behavior

```javascript
const burn_amount = BigInt( Math.floor( burn_amount_float * 10 ** decimals ) )
const call = { abi, address, functionName: 'burn', args: [ burn_amount ] }
const { data: sim_result, error: sim_error } = useSimulateContract( call )
```

Throws with:

```
VM258 chunk-VZ7REHMU.js:124 Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at hashKey (VM258 chunk-VZ7REHMU.js:124:15)
    at hashQueryKeyByOptions (VM258 chunk-VZ7REHMU.js:121:10)
    at _a8.defaultQueryOptions (VM258 chunk-VZ7REHMU.js:1823:36)
    at _a8.getQueryState (VM258 chunk-VZ7REHMU.js:1676:26)
    at useBaseQuery (VM258 chunk-VZ7REHMU.js:2997:35)
    at useQuery (VM258 chunk-VZ7REHMU.js:3056:10)
    at useQuery2 (VM263 chunk-MEVJJSAC.js:4414:18)
    at useSimulateContract (VM263 chunk-MEVJJSAC.js:5045:10)
```

Somewhere in the source `JSON.stringify` is used, but that built-in method does not support the native BigInt. This is a known issue and the reason for libraries like [safe-stable-stringify](https://www.npmjs.com/package/safe-stable-stringify) (14m weekly downloads 😬).

### Expected Behavior

Should succeed.

### Steps To Reproduce

Run the cod above.

### Link to Minimal Reproducible Example

https://too_little_bandwidth_sorry.fyi

**Comment by actuallymentor** [comment]
Too busy. The issue source is clear and contained. Apologies.

**Comment by jxom** [comment]
Your stack trace sources `useSimulateContract`, which doesn’t exist in Viem. Best to raise this in Wagmi with a minimal reproducible example.
