### ISSUE TITLE
verifySiweMessage always returns false for zkSync AA signatures

### ISSUE THREAD

**Issue by Cali93** [wevm/viem#2872]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.26

### Current Behavior

Using `verifySiweMessage` to verify zkSync AA signatures incorrectly returns `false`.
This is because the [verifyHash](https://github.com/wevm/viem/blob/e87adfa5e2fcfa75fc809cb410718636112cde1c/src/actions/public/verifyHash.ts#L59) function always returns `false`. 

### Expected Behavior

 Signature validation returns `true` for a valid signature, reference implementation can be found [here](https://docs.zksync.io/build/developer-reference/account-abstraction/signature-validation#verifying-aa-signatures).

### Steps To Reproduce

- Create a SIWE message and sign it with a zkSync Smart account (eg: Clave) using wagmi's `signMessage`
- Validate the SIWE message using `verifySiweMessage` -> returns `false`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-xxtkea?file=index.ts,package.json

**Comment by jxom** [comment]
To confirm: is this a regression from a previous version? Or is this a newly identified issue?

**Comment by jxom** [comment]
cc @coffeexcoin if you have any ideas since you worked on the deployed universal verifier

**Comment by Cali93** [comment]
Pretty sure it's a newly identified issue.

**Comment by coffeexcoin** [comment]
@Cali93 @jxom it appears this signature returns as invalid before the recent validateHash changes:
https://stackblitz.com/edit/viem-getting-started-ehckrv?file=package.json

Can you share how the signature was generated? For clave it should be the signed representation of the Clave1271 typed data message encoded with the validator address.

An example of this is here for the Abstract fork of Clave (we are adding EIP6492 on top but this is not required):
https://github.com/Abstract-Foundation/agw-sdk/blob/2c575b28bd135fc267e3219b8a85777bceeefb37/packages/agw-client/src/transformEIP1193Provider.ts#L60C1-L112C2

**Comment by Cali93** [comment]
> Can you share how the signature was generated?

It was generated using [signMessage](https://wagmi.sh/core/api/actions/signMessage#usage).

So you're saying that we should use a specific method to generate signatures for Clave wallets ? What about other zkSync AA wallets ? It seems like we'd have to handle them case by case ?

**Comment by coffeexcoin** [comment]
It looks like this is in fact a valid signature, and viem is validating it properly?

I pushed the code up to a repo here https://github.com/coffeexcoin/viem-2872-repro - running this locally results in `isValid: true`

<img width="551" alt="image" src="https://github.com/user-attachments/assets/5c768ea7-db07-43a9-bf77-5f1c0c28ded2">
