### ISSUE TITLE
`fallback` `transport` rank with ssr on server and non-connected client

### ISSUE THREAD

**Issue by agsola** [wevm/viem#2886]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.29

### Current Behavior

When configuring a `fallback` `transport` with `ranking` which includes both `http` and `webSocket` `transports` for different chains and use that to `createConfig` as the input of `WagmiProvider`, despite having the `ssr` option set to `true` there are plently of request from both the server and the client to ALL of the `http` and `webSocket` `providers`, regardless of the connection status.

### Expected Behavior

IMHO the proper behaviour should be as follows:
- Server-side: No request to providers at all. When doing an 'npm run build' I get thousand of petitions that are totally useless to be made on the server side just to "rank" the transport that won't be used on the server side.
- Client-side: Only rank the servers once a connection is stablished and a chainId is established. There is no point to rank all chains that may not be ever used. We are a multichain dApp, and we have almost 100 different chains with their different RPCs each one. Only the one that the use is connected to should be used.

**Comment by jxom** [comment]
Please raise this as a feature request discussion on the Wagmi repo.

**Comment by jxom** [comment]
Go for it. Please include a minimal reproducible example as well.
