### ISSUE TITLE
isAddress function causes memory leak on iOS 18+

### ISSUE THREAD

**Issue by memoyil** [wevm/viem#2891]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.22

### Current Behavior

The isAddress function in the viem library appears to cause a memory leak on devices running iOS 18 or later. When repeatedly calling isAddress in an iOS environment (version 18+), memory consumption steadily increases and is not released, leading to degraded app performance and eventually crashing after prolonged usage.

### Steps To Reproduce

Steps to Reproduce:

    Use the isAddress function to validate addresses in a loop or with frequent calls in an iOS app (version 18+).

**Comment by jxom** [comment]
I am unable to reproduce as the steps to reproduce are too vague. Is this a React Native environment, or a web app in a particular iOS browser?

Can you please open a new issue with a minimal reproducible example?

**Comment by jxom** [comment]
Nevermind. I am able to reproduce. We may need to lax the cache size for RN.
