### ISSUE TITLE
`TransactionReceipt` is missing OP Stack-specific properties

### ISSUE THREAD

**Issue by 0xwetzo** [wevm/viem#2955]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.38

### Current Behavior

OP Stack-specific properties like `l1Fee` are flagged as non-existant by. the IDE.

### Expected Behavior

The OP Stack-specific properties should be present in the type `TransactionReceipt` as they are returned by `waitForTransactionReceipt` and `getTransactionReceipt`:
- For OP Mainnet:
```
        "l1Fee": "0x56dceff14c64",
        "l1FeeScalar": "1",
        "l1GasPrice": "0x339faf23b",
        "l1GasUsed": "0x1aec",
```
- For Base:
```
        "l1BaseFeeScalar": "0x8dd",
        "l1BlobBaseFee": "0x194b19aa",
        "l1BlobBaseFeeScalar": "0x101c12",
        "l1Fee": "0x14aaf0a42e",
        "l1GasPrice": "0xa2175a98",
        "l1GasUsed": "0xa25",
```

### Steps To Reproduce

```
import { createPublicClient, http } from 'viem';
import type { TransactionReceipt } from 'viem';
import { optimism } from 'viem/chains';

const client = createPublicClient({
  chain: optimism,
  transport: http(),
});

const run = async () => {
  const receipt: TransactionReceipt = await client.waitForTransactionReceipt({
    hash: '0x3f94f8d43feeaaa1ab2c16f1700f0b900fa8e0f6a47e1d94a3c94fb083389687',
  });
  console.log(receipt.l1Fee.toString());
};

run();
```
In this snippet, `l1Fee` will appear underscored in red.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-pifrph?file=index.ts

**Comment by Chirag-S-Kotian** [comment]
assign this to me.

**Comment by insulineru** [comment]
Hey, @0xwetzo. 

You can use existing type `OpStackTransactionReceipt` for OP-Stack specific tx receipt

<img width="665" alt="image" src="https://github.com/user-attachments/assets/b58f5be4-b322-40ba-aec9-94084cac5901">

**Comment by 0xwetzo** [comment]
Thanks a lot @insulineru, there is no mention of this type in the docs so I did not know about it.
