### ISSUE TITLE
watchBlock with fetching transactions doesn't work

### ISSUE THREAD

**Issue by franklee00** [wevm/viem#2960]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

latest

### Current Behavior

While set the options includeTransactions to true, onBlock fetch undefined instead of transactions arrays.

```
client.watchBlocks({
    includeTransactions: true, 
    onBlock: async (block) => {
        console.log(block.transactions)
    },
    onError: (error) => console.error(error),
});
```

### Expected Behavior

return array of transactions

**Comment by jxom** [comment]
Needs repro. We have a [test for this](https://github.com/wevm/viem/blob/main/src/actions/public/watchBlocks.test.ts).

**Comment by franklee00** [comment]
The answer is in the test file--adding options below and everything goes well. It works!

`onBlock: (block) => blocks.push(block),
      includeTransactions: true,
      poll: true,`
