### ISSUE TITLE
Unable to resolve ./Bytes.js

### ISSUE THREAD

**Issue by Amurmurmur** [wevm/viem#2987]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.43

### Current Behavior

![Simulator Screenshot - iPhone 16 - 2024-11-08 at 09 44 03](https://github.com/user-attachments/assets/cafabfb7-2dc0-40fb-b974-a92c0568b019)

### Expected Behavior

Rolling back to 2.21.42 resolved the issue

### Steps To Reproduce

1. Install viem 2.21.43

### Anything else?

Using React-native v0.75.4

**Comment by tmm** [comment]
Most likely related to React Native `package.json#exports` support.
