### ISSUE TITLE
`newHeads` block does not include array of transaction hashes

### ISSUE THREAD

**Issue by holic** [wevm/viem#2995]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.44

### Current Behavior

`watchBlocks` emits a `Block` type, which expects an array of transaction hashes when not using `includeTransactions: true`:
https://github.com/wevm/viem/blob/82633bda23780791fd5b70aa0a6d3bf7e250955a/src/utils/formatters/block.ts#L36

viem uses `newHeads` when subscribing to new blocks via websocket transport:
https://github.com/wevm/viem/blob/82633bda23780791fd5b70aa0a6d3bf7e250955a/src/actions/public/watchBlocks.ts#L238

However, these `newHeads` objects do not contain the list of transaction hashes, so I get runtime errors when attempting to use `block.transactions`:
https://docs.alchemy.com/reference/newheads

I can also see this behavior when using this against an OP Stack chain:

<img width="509" alt="image" src="https://github.com/user-attachments/assets/ccd4b415-14d0-4cb3-a112-27deb90edcf7">

### Expected Behavior

I would expect the `Block` type to not guarantee a list of transaction hashes or Viem to populate these transaction hashes for me.

### Steps To Reproduce

```ts
const unwatch = publicClient.watchBlocks({ 
  onBlock: (block) => console.log("block", block.number, block.transactions),
  pollingInterval: 1_000, 
});
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-wngn4c?file=index.ts

**Comment by holic** [comment]
Hmm, since our use case involves using those tx hashes, we were detecting the missing txs and calling `getBlock`. But this new change means it's harder for us to differentiate between missing txs and empty blocks.

**Comment by jxom** [comment]
:(

**Comment by jxom** [comment]
Can you `poll: true` instead? Tempted to remove `newHeads` functionality, as it is more semantically more a "header" than a "block".

**Comment by holic** [comment]
Listening to new heads is nice because its fast/responsive, then we just do `getBlock` with the new head block hash. Wonder if it makes sense to viem to do the same?

**Comment by jxom** [comment]
got it. can add it in.
