### ISSUE TITLE
fantomSonicTestnet chain informations are outdated.

### ISSUE THREAD

**Issue by Mejuck** [wevm/viem#3051]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.50

### Current Behavior

Current viem chain details of fantomSonicTestnet are outdated. Current informations can be obtained from https://testnet.soniclabs.com/account.

### Expected Behavior

id should be 64165
network name Sonic Testnet
currency Sonic
symbol S
rpcUrl https://rpc.testnet.soniclabs.com
blockExplorer https://testnet.soniclabs.com/

### Steps To Reproduce

import { defineChain } from '../../utils/chain/defineChain.js'

export const fantomSonicTestnet = /*#__PURE__*/ defineChain({
  id: 64_165,
  name: 'Sonic Testnet',
  network: 'fantom-sonic-testnet',
  nativeCurrency: {
    decimals: 18,
    name: 'Sonic',
    symbol: 'S',
  },
  rpcUrls: {
    default: { http: ['https://rpc.testnet.soniclabs.com'] },
  },
  blockExplorers: {
    default: {
      name: 'Sonic Testnet Explorer',
      url: 'https://testnet.soniclabs.com/',
    },
  },
  testnet: true,
})

**Comment by jxom** [comment]
Please raise a PR instead.
