### ISSUE TITLE
simulateContract does not return revertReason

### ISSUE THREAD

**Issue by zamrokk** [wevm/viem#3067]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.49

### Current Behavior

If I send this kind of transaction without passing any ETH on the value, but the deployed Solidity contract will check if the user has sent money, then I receive this error

`Execution reverted for an unknown reason`

Example of call : 

```
 const { request } = await publicClient!.simulateContract({
          account: walletClient?.account!,
          address: CONTRACT_ADDRESS,
          abi,
          functionName: "bet",
          args: [option, parseEther(amount.toString())],
          
        });
```

- if I pass the value => no error , obviously the tx is correct
- if I call writeContract directly => then I can see the revertReason on the failed tx on BlockScout explorer

I parsed the full error from the try catch, the typeof gives : ContractFunctionExecutionError 
There is no revertReason on it ...

I was expecting more a type of ContractFunctionRevertedError instead

Maybe the type cast made by viem is wrong and so, the revertReason data is lost  

### Expected Behavior

a ContractFunctionRevertedError object with a revertReason 

### Steps To Reproduce

simulate a tx with money to a contract endpoint that will use `require` to check that ETH have been sent 
Look at the returned error and check all fields, there is no revertReason on it

**Comment by jxom** [comment]
Please provide a minimal reproduction.
