### ISSUE TITLE
Action `sendTransaction` loses `type` field

### ISSUE THREAD

**Issue by GiovaniGuizzoYUB** [wevm/viem#3123]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.55

### Current Behavior

When sending a transaction with a explicit `type` field set as "legacy" (haven't tested with other types), the transaction that arrives to my custom transport (haven't tested with other transports) does not have the `type` field.
This does not happen with the `signTransaction` action.

### Expected Behavior

When sending a transaction with an explicit `type` field, the transaction type should be forwarded to the transport.

### Steps To Reproduce

* Create a custom transport that logs the transaction
* Create a transaction with `type` field set explicitly
* Use the action `sendTransaction` with a client using the custom transport
* Watch the transaction arrive on the custom transport without a `type` field

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/viem-getting-started-1mcmd6ry?file=index.ts,package.json

### Anything else?

The "type" information is very important, specially for the Ledger application that uses it to determine fees.

**Comment by jxom** [comment]
What is the issue? Why is it important? The Execution API specification [doesn't list it as required](c/schemas/transaction.yaml#L358) (note lack of `required` property) – so I wouldn't _bet_ on tooling to fill it in for you.

**Comment by GiovaniGuizzoYUB** [comment]
For sure, I think the wallets should infer the fees. However, this is a valid field in a transaction which is lost on serialization. If someone needs to inform the type, your serialization loses the value of the field.

I am not asking you to fit it in for me, I'm just pointing out that viem is losing information on serialization.
