### ISSUE TITLE
Add Multicall3 to sonic 

### ISSUE THREAD

**Issue by yogaajs** [wevm/viem#3129]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

Latest

### Current Behavior

Add this to sonic, multicall3 is deployed, thanks

`
export const sonic = /*#__PURE__*/ defineChain({
  id: 146,
  name: 'Sonic',
  nativeCurrency: {
    decimals: 18,
    name: 'Sonic',
    symbol: 'S',
  },
  rpcUrls: {
    default: { http: ['https://rpc.soniclabs.com'] },
  },
  blockExplorers: {
    default: {
      name: 'Sonic Explorer',
      url: 'https://explorer.soniclabs.com',
      apiUrl: 'https://api.sonicscan.org/api'
    },
  },
  contracts: {
    multicall3: {
      address: '0xcA11bde05977b3631167028862bE2a173976CA11',
      blockCreated: 60,
    },
  },
})
`

**Comment by yogaajs** [comment]
And API url :  'https://api.sonicscan.org/api'

**Comment by jxom** [comment]
Please open a PR instead.
