### ISSUE TITLE
Write Contract retries 3 times when UnknownRpcError code -1 received from Wallet Connect/Fireblocks

### ISSUE THREAD

**Issue by alexwalchli** [wevm/viem#3137]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

viem: 2.21.55, wagmi: 2.14.3

### Current Behavior

Contract writes retry three times in some cases. Potentially specific to Wallet Connect / Fireblocks and mishandling an exception thrown by during use of that combination.

### Expected Behavior

I think I would expect no retries at all for any contract write whatsoever. In the wagmi documentation it stays the default for retry count for mutations is 0 [here](https://wagmi.sh/react/api/hooks/useConnect#retry). 

It is quite dangerous and has caused confusion with us and our customers alike. In our context, it happens when a customer goes to use our app to buy or sell tokens. Transaction approvals land in Fireblocks, if they take too long to approve, or have insufficient funds for the network fee, it will retry three times, tripping up users trying to approve or deny these transactions. 

### Steps To Reproduce

1. Connect a Fireblocks account to a web app using Wallet Connect that does not have enough ETH to do a write.
2. Attempt to do a transaction that will result in a failure due to insufficient funds for network fee.
3. Note the screenshot below that captures the error: "Session Settlement Failed", code -1, this falls into a shouldRetry=true case.
4. This results in write contract's trying 3 times if they have insufficient funds.

We have seen this occur in some other cases as well, like taking too long to approve a transaction in Fireblocks, but the above is the easiest way to reproduce.

This may not be specific though to using Wallet Connect and Fireblocks, from a brief look, it's simply if an RPC error is thrown with code -1.

<img width="1681" alt="image" src="https://github.com/user-attachments/assets/6adb3eaf-6e53-4883-85fb-560eb1ab60f3" />

**Comment by jxom** [comment]
Hard to tell what’s going on without a minimal reproduction.

Regardless of if `shouldRetry` is true or false, it should not retry as `retryCount` is zero for all mutation actions, in this case, [`sendTransaction`](https://github.com/wevm/viem/blob/main/src/actions/wallet/sendTransaction.ts#L245) (which `writeContract` internally uses.

**Comment by jxom** [comment]
Attempted to reproduce, but cannot.

**Comment by alexwalchli** [comment]
@jxom  This may be an issue with Dynamic.xyz, I should have mentioned we are using that. Thanks for looking into it, I'll see what they say.
