### ISSUE TITLE
WaitForTransactionReceiptTimeoutError

### ISSUE THREAD

**Issue by ada20221024** [wevm/viem#3147]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.55

### Current Behavior

In base chain, wait for approve tx, It show timeout error always.

### Expected Behavior

Receive the receipt

### Steps To Reproduce

Call waitForTransactionReceipt for any tx hash

**Comment by ada20221024** [comment]
Oh, I got it, The okx wallet rpc is broken.

**Comment by quinnorson00967821** [comment]
Hello @ada20221024 
Has it been resolved?
