### ISSUE TITLE
bundlerClient.prepareUserOperation getBundlerError.ts expose data

### ISSUE THREAD

**Issue by 841660202** [wevm/viem#3149]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

latest

### -32521 Example

```json
{
    "jsonrpc": "2.0",
    "id": 3,
    "error": {
        "code": -32521,
        "message": "execution reverted",
        "data": {
            "revertData": "0xcf47918100000000000000000000000000000000000000000000000007e9e499c7a4dbe800000000000000000000000000000000000000000000000007e9e499c7a4dbe1"
        }
    }
}
```

```json
{
    "jsonrpc": "2.0",
    "id": 459,
    "error": {
        "code": -32521,
        "message": "execution reverted",
        "data": {
            "revertData": "0x"
        }
    }
}
```

[https://github.com/wevm/viem/blob/ec8f2e0356d97d05b65410ecee048add20519bb3/src/account-abstraction/utils/errors/getBundlerError.ts#L260](https://github.com/wevm/viem/blob/ec8f2e0356d97d05b65410ecee048add20519bb3/src/account-abstraction/utils/errors/getBundlerError.ts#L260)

[https://github.com/wevm/viem/blob/ec8f2e0356d97d05b65410ecee048add20519bb3/src/account-abstraction/errors/bundler.ts#L31](https://github.com/wevm/viem/blob/ec8f2e0356d97d05b65410ecee048add20519bb3/src/account-abstraction/errors/bundler.ts#L31)

**No data is exposed**

### Expected Behavior

I want to expose the revertData field in the error response so that I can parse it using the Ethereum Signature Database. This will allow me to extract meaningful information and provide clear feedback to the user.

### If I have data I will

```ts
import { decodeFunctionData, parseAbi } from 'viem';
import { describe, test } from 'vitest'

async function handleRevertData(result) {
  try {
    // Step 2: Extract the revertData prefix
    const revertData = result.error.data.revertData;
    const hexSignature = revertData.slice(0, 10);

    // Step 3: Fetch the signature from the API
    const response = await fetch(`https://www.4byte.directory/api/v1/signatures/?hex_signature=${hexSignature}`);
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    const apiData = await response.json();

    // Step 4: Extract the text signature from the API response
    if (apiData.count === 0) {
      throw new Error('Signature not found');
    }
    const textSignature = apiData.results[0].text_signature;

    // Step 5: Parse the ABI
    // @ts-ignore
    const abi = parseAbi([`function ${textSignature}`]);

    // Step 6: Decode the function data
    const decodedData = decodeFunctionData({
      abi,
      data: revertData,
    });

    // Step 7: Return decoded data

    return decodedData

  } catch (error) {
    console.error('Error handling revert data:', error);
  }
}



describe('chains', () => {
  test('default', async () => {
    // Example usage
    const result = {
      "jsonrpc": "2.0",
      "id": 3,
      "error": {
          "code": -32521,
          "message": "execution reverted",
          "data": {
              "revertData": "0xcf47918100000000000000000000000000000000000000000000000007e9e499c7a4dbe800000000000000000000000000000000000000000000000007e9e499c7a4dbe1"
          }
      }
    };

    const decodedData = await handleRevertData(result);
    console.log('Decoded Data:', decodedData);

  })
})

```

out

<img width="738" alt="image" src="https://github.com/user-attachments/assets/41093748-80f7-4e46-b6af-6c28588a4a2c" />

**Comment by 841660202** [comment]
**viem@2.21.57**

If revert occurs, get this data after estimateUserOperationGas ends. But I still can't get the raw data here [https://github.com/wevm/viem/blob/356db408f544bd655f8fc4ba556940669ed7c36c/src/account-abstraction/actions/bundler/estimateUserOperationGas.ts#L198](https://github.com/wevm/viem/blob/356db408f544bd655f8fc4ba556940669ed7c36c/src/account-abstraction/actions/bundler/estimateUserOperationGas.ts#L198)

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/bce81b1d-be56-43b7-bbd9-0e3a8b39583c" />


<img width="1345" alt="image" src="https://github.com/user-attachments/assets/5fa4b4b7-ae98-4ad5-be12-0f8c3c832f19" />

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/9f83562c-ffbc-44b0-8ae3-4e311a06c6c8" />

**Comment by 841660202** [comment]
@jxom

**Comment by jxom** [comment]
Screenshots are not helpful. Please open a new issue with a minimal reproducible example.

**Comment by 841660202** [comment]
minimal reproduction

[https://stackblitz.com/edit/viem-getting-started-lhkhfmxj?file=index.ts](https://stackblitz.com/edit/viem-getting-started-lhkhfmxj?file=index.ts)

**Comment by jxom** [comment]
Thank you.
