### ISSUE TITLE
Default RPC https://cloudflare-eth.com return internal error

### ISSUE THREAD

**Issue by wenzhongchi** [wevm/viem#3159]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.8

### Current Behavior

https://cloudlare-eth.com is returning internal error

### Expected Behavior

eth_call shall return correct response

### Steps To Reproduce

use above version and make any rpc call to eth mainnet

**Comment by tmm** [comment]
https://github.com/wevm/viem/discussions/3155#discussioncomment-11651155
