### ISSUE TITLE
Multicall3 not supported on Fraxtal

### ISSUE THREAD

**Issue by Clonescody** [wevm/viem#3166]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/viem/issues) for the bug I encountered.

### Viem Version

2.21.58

### Current Behavior

Trying to call the `multicall3.aggregate3` via `publicClient.multicall()` fails and raises an error on Fraxtal

```
Version: viem@2.21.58
 cause: {
  "details": "{\"code\":-32601,\"message\":\"Unsupported method on FRAX_MAINNET\"}",
  "metaMessages": [
    "Status: 400",
```

The contract exists on fraxtal and the implementation looks similar as other chains, the initial config on viem side looks fine as well but the call can't be made.

### Expected Behavior

Expected behavior is a classic multicall, my app reads on Mainnet & Arbitrum without trouble using the same code logic.

### Steps To Reproduce

I made a small gist that reproduces the issue, an RPC_URL will have to be added in the `index.ts` code.
The error occurred using a personal Alchemy RPC, I haven't tried any other
It tries to batch calls to multiple Curve Lending Vaults contracts deployed on Fraxtal

### Link to Minimal Reproducible Example

https://gist.github.com/Clonescody/dbd72eaa48f9cf4d09a886106944f35c

### Anything else?
Fraxtal Multicall contract configured in the viem chain definition [0xca11bde05977b3631167028862be2a173976ca11](https://fraxscan.com/address/0xca11bde05977b3631167028862be2a173976ca11#writeContract)

Feel free to close this if the issue is not viem related.

**Comment by jxom** [comment]
The error looks like the result of an unsupported JSON-RPC method. Unsure if this is Viem-related if this only occurs for Fraxtal and no other chains.
