### ISSUE TITLE
bug: separate WS connection opened for each filter created

### ISSUE THREAD

**Issue by kdembler** [wevm/viem#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.3.24

### Current Behavior

When you're using websocket transport, for every call to `publicClient.watchContractEvent`, a separate websocket connection is opened. Each connection will contain only a single call to `eth_newFilter` and then changes for every filter will actually be listened to in single "main" connection. In my usecase I'm using `wagmi` but I believe this is `viem` issue.

### Expected Behavior

I would expect all the filters to be created within a single websocket connection, so that unnecessary connections are not established.

### Steps To Reproduce

Using websocket, call `publicClient.watchContractEvent` for two different events to that 2 topics have to be created. 2 websocket connections will be opened.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/new-wagmi-5tmpgo?file=src/App.tsx

**Comment by jxom** [comment]
Think this could be a race condition with setting up sockets in which we should batch up  the watchers in a [zero delay](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Event_loop#zero_delays). Can take a look tomorrow.
