### ISSUE TITLE
bug: Fallback public client with WS transport doesn't use eth_subscribe

### ISSUE THREAD

**Issue by arjun-io** [wevm/viem#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.6

### Current Behavior

When using a fallback provider with a websocket transport underneath, the provider does not use subscriptions and instead reverts to polling over the websocket connection.

### Expected Behavior

If a fallback provider is used, and the attempted transport being used is websocket, use `eth_subscribe`

### Steps To Reproduce

See minimal repo -> Network Inspector -> Websocket connection

<img width="1002" alt="image" src="https://github.com/wagmi-dev/viem/assets/2940142/1c520823-788d-4c98-badb-79b17d28692b">

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-ynbq9a?file=index.ts

**Comment by arjun-io** [comment]
Since the `eth_subscribe` based functions only check for the top level transport (https://github.com/wagmi-dev/viem/blob/main/src/actions/public/watchBlocks.ts#L100) and the `fallback` transport doesn't have any ability to surface the type of transport it is attempting, it might take a bit of a refactor to handle this... Potentially the fix here is to give some level of introspection to the fallback transports currently used transport and use that in the `enablePolling` check?

**Comment by deHB6** [comment]
Experiencing this as well, when I add `webSocketPublicClient`, watch: true no longer works on my `useContractReads`

**Comment by wk0** [comment]
is this still a problem?

**Comment by arjun-io** [comment]
> is this still a problem?

It appears show, I just retried the stackblitz with an updated version of Viem.
