### ISSUE TITLE
bug: Offchain ENS resolution does not seem to work with a custom transport

### ISSUE THREAD

**Issue by Anonermous** [wevm/viem#973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.1.7

### Current Behavior

When Viem is setup using a custom transport, it errors when trying to request an ENS subdomain like `coinbase.cb.id`. When using the standard `http` transport, `coinbase.cb.id` resolves as expected.

### Expected Behavior

Expect subdomains like `coinbase.cb.id` to resolve to the expected address that is registered when using a custom transport.

### Steps To Reproduce

Instantiate the Viem client with a custom transport and try to resolve `coinbase.cb.id`. Example provided here:

https://stackblitz.com/edit/viem-getting-started-6ec5on?file=index.ts

Notice `vitalik.eth` works as expected, but `coinbase.cb.id` does not.

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-6ec5on?file=index.ts

**Comment by alexdwagner** [comment]
Hey, can I take this one?

**Comment by jxom** [comment]
@alexdwagner – Go for it.

**Comment by srihar5ha** [comment]
Is anybody working on it? I think the custom transport is wrongly implemented to resolve ` .cb.id.` 
I've gone through [https://stackblitz.com/edit/viem-getting-started-6ec5on?file=index.ts](url), I believe the custom url [https://rpc.ankr.com/eth](url) has nothing to do with the subdomains you are looking to resolve. Pls correct me if I'm wrong. Point me in the right direction.

**Comment by alexdwagner** [comment]
feel free @srihar5ha !

**Comment by TateB** [comment]
hey, the issue here is offchain ENS names use CCIP-read which relies on throwing a custom revert error from a contract.
since custom transports are expected to return the correct result, you need to implement an error to be thrown on rpc error.
see this example: https://stackblitz.com/edit/viem-getting-started-rs4tgv?file=index.ts

**Comment by jxom** [comment]
^ answer

**Comment by Anonermous** [comment]
Awesome, @TateB's solution works! Thank you all!
